| Generated by generate.py; edit events.c / core.h.
#NO_APP
	.file	"events.c"
	.text
	.align	2
	.type	convert, @function
convert:
	lea (-36,%sp),%sp
	movem.l #1036,(%sp)
	move.l 40(%sp),%a0
	tst.b 5(%a0)
	jeq .L1
	tst.l 48(%sp)
	sne %d1
	mvz.b 4(%a0),%d0
	move.l %d0,%a1
	move.l %d1,%d2
	neg.l %d2
	mvz.b %d2,%d0
	move.l %d2,28(%sp)
	cmp.l %a1,%d0
	jeq .L1
	move.l #635712,%d0
	mvz.b (%a0),%d1
	mvz.b 7(%a0),%d3
	move.l #36568,%d2
	muls.l %d1,%d0
	muls.l %d2,%d3
	moveq #3,%d2
	move.l %d0,%a1
	add.l #1074704439,%a1
	move.b (%a1,%d3.l),%d0
	move.l 44(%sp),-(%sp)
	and.l %d2,%d0
	move.b %d0,1(%a0)
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	move.l %a0,24(%sp)
	jsr hd_scale_c
	move.l 24(%sp),%a0
	lea (12,%sp),%sp
	move.b 8(%a0),%d1
	tst.l 48(%sp)
	jeq .L3
	tst.b %d1
	jeq .L13
	st %d0
	move.b %d0,2(%a0)
.L5:
	moveq #1,%d0
	move.b 31(%sp),4(%a0)
	move.b %d0,6(%a0)
.L1:
	movem.l (%sp),#1036
	lea (36,%sp),%sp
	rts
.L3:
	tst.b %d1
	jeq .L6
	mvz.b (%a0),%d1
	move.l #635712,%d3
	mvz.w 46(%sp),%d0
	mvz.b 1(%a0),%d2
	muls.l %d3,%d1
	lsl.l #5,%d0
	move.l %d1,20(%sp)
	move.w %d2,%d1
	move.l %d0,%a1
	add.l #1075254082,%a1
	moveq #1,%d0
	add.l 20(%sp),%a1
	muls.w #6322,%d1
	add.l %d1,%a1
	move.b (%a1),3(%a0)
	move.b 31(%sp),4(%a0)
	move.b %d0,6(%a0)
	jra .L1
.L13:
	mvz.b 3(%a0),%d3
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %a0,20(%sp)
	jsr hd_encode_c
	addq.l #8,%sp
	move.l 12(%sp),%a0
	move.b %d0,2(%a0)
	jra .L5
.L6:
	mvz.b 2(%a0),%d2
	move.l %d0,-(%sp)
	move.l %d2,-(%sp)
	move.l %d1,24(%sp)
	move.l %a0,20(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	move.l 16(%sp),%d1
	move.l 12(%sp),%a0
	tst.l %d0
	jlt .L7
	move.b %d0,%d1
.L8:
	move.b %d1,3(%a0)
.L14:
	moveq #1,%d0
	move.b 31(%sp),4(%a0)
	move.b %d0,6(%a0)
	jra .L1
.L7:
	mvz.b 2(%a0),%d0
	moveq #6,%d3
	cmp.l %d0,%d3
	jcc .L8
	moveq #127,%d1
	move.b %d1,3(%a0)
	jra .L14
	.size	convert, .-convert
	.align	2
	.globl	hd_events_reset_c
	.type	hd_events_reset_c, @function
hd_events_reset_c:
	move.l %a2,-(%sp)
	lea fired+5,%a1
	clr.l %d0
	lea staged+5,%a0
	lea hd_rebuild,%a2
.L16:
	clr.b %d1
	clr.b (%a1)
	clr.b (%a0)
	lea (9,%a1),%a1
	lea (9,%a0),%a0
	move.b %d1,(%a2,%d0.l)
	addq.l #1,%d0
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L16
	lea pending+5,%a0
.L17:
	clr.b (%a0)
	lea (9,%a0),%a0
	cmp.l #pending+293,%a0
	jne .L17
	move.l (%sp)+,%a2
	rts
	.size	hd_events_reset_c, .-hd_events_reset_c
	.align	2
	.globl	hd_event_stage_c
	.type	hd_event_stage_c, @function
hd_event_stage_c:
	lea (-12,%sp),%sp
	moveq #15,%d1
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.l 24(%sp),%d0
	or.l 28(%sp),%d0
	cmp.l %d0,%d1
	jcs .L22
	moveq #7,%d2
	cmp.l 32(%sp),%d2
	jcs .L22
	moveq #63,%d0
	cmp.l 36(%sp),%d0
	jcs .L22
	moveq #3,%d1
	cmp.l 40(%sp),%d1
	jlt .L22
	tst.l 40(%sp)
	jlt .L31
	move.l 40(%sp),%d0
	move.l 24(%sp),%d2
	move.l 28(%sp),%d1
	lsl.l #3,%d0
	add.l 32(%sp),%d0
	mulu.w #9,%d0
	move.l %d0,%a0
	move.l #635712,%d0
	muls.l %d0,%d2
	move.l 36(%sp),%d0
	add.l #pending,%a0
	lsl.l #5,%d0
	move.l %d2,%a1
	add.l #1074668000,%a1
	move.l %a1,12(%sp)
	move.l #36568,%d2
	muls.l %d2,%d1
	move.l #2224,%d2
	move.l %d0,%a1
	move.l 32(%sp),%d0
	add.l 12(%sp),%d1
	lea (18688,%a1),%a1
	muls.l %d2,%d0
	moveq #3,%d2
	add.l %d0,%a1
	move.l %d1,%d0
	add.l #36439,%d0
	move.l %d0,%a2
	move.b (%a2),%d0
	move.b (%a1,%d1.l),%d1
	and.l %d0,%d2
	move.l %d1,%d0
	not.l %d0
	tst.b %d0
	seq %d0
	move.l %d2,16(%sp)
	mvz.b %d1,%d2
	neg.l %d0
	move.b %d0,8(%a0)
	cmp.l #255,%d2
	jeq .L32
.L26:
	move.b 27(%sp),(%a0)
	move.b 19(%sp),1(%a0)
	move.b 31(%sp),7(%a0)
	move.b %d1,3(%a0)
	move.l 32(%sp),-(%sp)
	move.l %a0,12(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	tst.l %d0
	sne %d1
	move.l 8(%sp),%a0
	neg.l %d1
	move.b %d1,4(%a0)
	tst.l %d0
	jne .L33
	st %d0
	move.w #256,%a2
	move.b %d0,2(%a0)
	move.w %a2,5(%a0)
.L22:
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (12,%sp),%sp
	rts
.L31:
	move.l 32(%sp),%d0
	move.l 24(%sp),%d2
	move.l 32(%sp),%a0
	lsl.l #3,%d0
	move.l 28(%sp),%d1
	add.l %d0,%a0
	move.l #635712,%d0
	add.l #staged,%a0
	muls.l %d0,%d2
	move.l 36(%sp),%d0
	lsl.l #5,%d0
	move.l %d2,%a1
	add.l #1074668000,%a1
	move.l %a1,12(%sp)
	move.l #36568,%d2
	muls.l %d2,%d1
	move.l #2224,%d2
	move.l %d0,%a1
	move.l 32(%sp),%d0
	add.l 12(%sp),%d1
	lea (18688,%a1),%a1
	muls.l %d2,%d0
	moveq #3,%d2
	add.l %d0,%a1
	move.l %d1,%d0
	add.l #36439,%d0
	move.l %d0,%a2
	move.b (%a2),%d0
	move.b (%a1,%d1.l),%d1
	and.l %d0,%d2
	move.l %d1,%d0
	not.l %d0
	tst.b %d0
	seq %d0
	move.l %d2,16(%sp)
	mvz.b %d1,%d2
	neg.l %d0
	move.b %d0,8(%a0)
	cmp.l #255,%d2
	jne .L26
.L32:
	move.l 32(%sp),%d0
	move.l #6322,%d2
	move.l 16(%sp),%d1
	lsl.l #5,%d0
	muls.l %d2,%d1
	add.l #586082,%d0
	add.l 12(%sp),%d0
	move.l %d0,%a1
	move.b (%a1,%d1.l),%d1
	jra .L26
.L33:
	move.l 36(%sp),-(%sp)
	move.w #256,%a2
	move.l 36(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l %a0,24(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	move.l 8(%sp),%a0
	move.b %d0,2(%a0)
	move.w %a2,5(%a0)
	jra .L22
	.size	hd_event_stage_c, .-hd_event_stage_c
	.align	2
	.globl	hd_event_copy_c
	.type	hd_event_copy_c, @function
hd_event_copy_c:
	move.l 4(%sp),%d1
	moveq #7,%d0
	cmp.l %d1,%d0
	jcs .L34
	move.l %d1,%d0
	lsl.l #3,%d0
	move.l %d0,%a0
	add.l %d1,%a0
	move.l %a0,%a1
	add.l #pending,%a0
	add.l #staged,%a1
	move.l (%a1)+,(%a0)+
	move.l (%a1)+,(%a0)+
	move.b (%a1),(%a0)
.L34:
	rts
	.size	hd_event_copy_c, .-hd_event_copy_c
	.align	2
	.globl	hd_event_fire_c
	.type	hd_event_fire_c, @function
hd_event_fire_c:
	move.l %a2,-(%sp)
	moveq #31,%d0
	move.l %d2,-(%sp)
	move.l 12(%sp),%a0
	move.l 16(%sp),%a1
	cmp.l %a0,%d0
	jcs .L41
	moveq #7,%d1
	cmp.l %a1,%d1
	jcs .L41
	move.l %a1,%d1
	move.l %a0,%d0
	lsl.l #3,%d1
	lsl.l #3,%d0
	lea fired,%a2
	add.l %a1,%d1
	add.l %d0,%a0
	add.l #pending,%a0
	lea (%a2,%d1.l),%a1
	move.l (%a0)+,(%a1)+
	move.l (%a0)+,(%a1)+
	move.b (%a0),(%a1)
	lea (%a2,%d1.l),%a0
	tst.b 5(%a0)
	jeq .L41
	mvz.b (%a2,%d1.l),%d0
	mvz.b 7(%a0),%d1
	move.l #635712,%d2
	muls.l %d2,%d0
	move.l #36568,%d2
	muls.l %d2,%d1
	move.l %d0,%a1
	add.l #1074704439,%a1
	move.b (%a1,%d1.l),%d0
	moveq #3,%d1
	and.l %d1,%d0
	move.b %d0,1(%a0)
	tst.b 6(%a0)
	jeq .L41
	tst.b 4(%a0)
	jne .L41
	move.l (%sp)+,%d2
	mvz.b 3(%a0),%d0
	move.l (%sp)+,%a2
	rts
.L41:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	move.l (%sp)+,%a2
	rts
	.size	hd_event_fire_c, .-hd_event_fire_c
	.align	2
	.globl	hd_events_mode_c
	.type	hd_events_mode_c, @function
hd_events_mode_c:
	lea (-20,%sp),%sp
	moveq #7,%d0
	movem.l #1036,(%sp)
	move.l 24(%sp),%d3
	cmp.l %d3,%d0
	jcs .L44
	moveq #2,%d0
	cmp.l 28(%sp),%d0
	jcc .L53
.L44:
	movem.l (%sp),#1036
	lea (20,%sp),%sp
	rts
.L53:
	move.l %d3,%d0
	lsl.l #3,%d0
	move.l 28(%sp),-(%sp)
	move.l %d3,-(%sp)
	lea convert,%a2
	add.l %d3,%d0
	move.l %d0,24(%sp)
	add.l #staged,%d0
	move.l %d0,-(%sp)
	jsr (%a2)
	move.l 28(%sp),%a0
	add.l #pending+288,%a0
	move.l %a0,24(%sp)
	move.l 28(%sp),%d2
	add.l #pending,%d2
	lea (12,%sp),%sp
.L46:
	move.l 28(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr (%a2)
	add.l #72,%d2
	lea (12,%sp),%sp
	cmp.l 12(%sp),%d2
	jne .L46
	move.l 28(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l 24(%sp),%d2
	add.l #fired,%d2
	move.l %d2,-(%sp)
	jsr (%a2)
	lea (12,%sp),%sp
	move.l %d2,%a1
	move.b 5(%a1),%d0
	lea hd_rebuild,%a0
	move.b %d0,(%a0,%d3.l)
	tst.l 28(%sp)
	jne .L44
	tst.b %d0
	jeq .L44
	add.l #37108607,%d3
	lsl.l #5,%d3
	move.l %d3,%a0
	move.b 3(%a1),(%a0)
	movem.l (%sp),#1036
	lea (20,%sp),%sp
	rts
	.size	hd_events_mode_c, .-hd_events_mode_c
	.align	2
	.globl	hd_prepare_c
	.type	hd_prepare_c, @function
hd_prepare_c:
	lea (-16,%sp),%sp
	moveq #7,%d0
	move.l %d2,-(%sp)
	move.l 28(%sp),%d1
	move.l 24(%sp),%a0
	cmp.l %d1,%d0
	jcc .L55
.L57:
	move.l (%sp)+,%d2
	move.l %a0,%d0
	lea (16,%sp),%sp
	rts
.L55:
	move.l %d1,-(%sp)
	move.l %d1,8(%sp)
	move.l %a0,12(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	move.l 4(%sp),%d1
	move.l 8(%sp),%a0
	tst.l %d0
	jeq .L57
	lea hd_busy,%a0
	tst.b (%a0,%d1.l)
	jne .L61
	move.l %d1,%d2
	lsl.l #3,%d2
	lea fired,%a1
	move.l %d2,%a0
	add.l %d1,%a0
	add.l %a0,%a1
	tst.b 5(%a1)
	jeq .L58
	tst.b 4(%a1)
	jne .L67
.L58:
	mvz.b -2147483646,%d2
	move.b 269161679,%d0
	move.l %d1,-(%sp)
	move.l %d2,%a1
	moveq #3,%d2
	and.l %d0,%d2
	move.l %d2,-(%sp)
	move.l %a1,-(%sp)
	move.l %d1,16(%sp)
	move.l %d2,20(%sp)
	move.l %a1,24(%sp)
	jsr hd_scale_c
	move.l 16(%sp),%d1
	move.l %d0,28(%sp)
	move.l %d1,-(%sp)
	move.l 24(%sp),%a0
	move.l %a0,-(%sp)
	move.l 32(%sp),%a1
	move.l %a1,-(%sp)
	jsr hd_base_c
	lea (24,%sp),%sp
	move.l 16(%sp),28(%sp)
	move.l %d0,24(%sp)
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	jra hd_decode_c
.L67:
	tst.b 8(%a1)
	jne .L68
	mvz.b 2(%a1),%d2
	lea fired,%a1
	move.l %d2,16(%sp)
	move.l %d1,-(%sp)
	mvz.b 1(%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	mvz.b (%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	jsr hd_scale_c
	lea (12,%sp),%sp
	move.l 16(%sp),24(%sp)
	move.l %d0,28(%sp)
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	jra hd_decode_c
.L68:
	move.l %d1,-(%sp)
	mvz.b 1(%a1),%d0
	lea fired,%a1
	move.l %d0,-(%sp)
	mvz.b (%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	move.l %d1,16(%sp)
	move.l %a0,20(%sp)
	jsr hd_base_c
	lea fired,%a1
	move.l %d0,28(%sp)
	move.l 16(%sp),%d1
	move.l 20(%sp),%a0
	lea (12,%sp),%sp
	move.l %d1,-(%sp)
	mvz.b 1(%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	mvz.b (%a1,%a0.l),%d0
	move.l %d0,-(%sp)
	jsr hd_scale_c
	lea (12,%sp),%sp
	move.l 16(%sp),24(%sp)
	move.l %d0,28(%sp)
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	jra hd_decode_c
.L61:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	lea (16,%sp),%sp
	rts
	.size	hd_prepare_c, .-hd_prepare_c
	.globl	hd_rebuild
	.section	.bss
	.type	hd_rebuild, @object
	.size	hd_rebuild, 8
hd_rebuild:
	.zero	8
	.local	fired
	.comm	fired,72,1
	.local	pending
	.comm	pending,288,1
	.local	staged
	.comm	staged,72,1
