#!/usr/bin/env python3
"""Compile the freestanding core to checked-in ColdFire assembly; --check refuses drift.

Uses the existing WAVE LOAD / Euclid C-to-assembly pattern. No build-system
extension and no additional runtime dependency.
"""
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
FLAGS = ['-mcpu=54455', '-O2', '-ffreestanding', '-fno-builtin', '-fno-common',
         '-fno-jump-tables', '-fno-asynchronous-unwind-tables', '-fno-ident',
         '-fomit-frame-pointer', '-Wall', '-Wextra', '-Wmissing-prototypes',
         '-Wstrict-prototypes', '-Werror']


def main():
    generated = {}
    with tempfile.TemporaryDirectory(prefix='harmony-degrees-generate-') as tmp:
        for unit in ('core', 'storage', 'events', 'ui', 'operations', 'roots', 'recording'):
            dest = pathlib.Path(tmp)/f'{unit}.s'
            subprocess.run(['m68k-elf-gcc', *FLAGS, '-S', '-o', str(dest), f'{unit}.c'],
                           check=True, cwd=HERE)
            header = 'roots.h' if unit == 'roots' else 'core.h'
            body = f'| Generated by generate.py; edit {unit}.c / {header}.\n' + dest.read_text()
            generated[HERE/f'{unit}.s'] = body
    # A compiler error never leaves a mixture of old and new output units.
    for target, body in generated.items():
        if '--check' in sys.argv:
            if not target.exists() or target.read_text() != body:
                raise SystemExit(f'stale generated assembly: {target}')
        else:
            target.write_text(body)
    if '--check' in sys.argv:
        print('Harmony degree generated assembly matches')


if __name__ == '__main__':
    main()
