"""Opt-in production candidate for scale-degree Harmony roots."""
from remix.schema import Category, Claims, Detour, Gate, Kind, Linked, Module, Proof

MODULE = Module(
    name='harmony-degrees', key='HARMONY DEGREES', kind=Kind.CF_PATCH,
    category=Category.MIDI_USB, author='Mattias Wolff',
    author_url='https://github.com/mattiaswolff/octabam', proof=Proof.PORT,
    proof_note='D0 port: degree conversion, editing, recording, retention and project lifecycle; hardware untested',
    doc='Degree/register roots with explicit conversion across stock/Harmony mode boundaries.',
    requires=('MIDI HARMONY',),
    conflicts=(('KITS', 'The external Kit library does not carry degree defaults'),
               ('MIDI SCENES', 'Native NOTE interpolation has no degree representation contract')),
    claims=Claims(sram=((0x100fa620, 16528, 'Degree extension to the combined CHRD current-bank mirror'),)),
    linked=(Linked('degreecodec', 'modules/harmony-degrees/codec.s', dram=True),
            Linked('degreecore', 'modules/harmony-degrees/core.s', dram=True),
            Linked('degreestorage', 'modules/harmony-degrees/storage.s', dram=True),
            Linked('degreeevents', 'modules/harmony-degrees/events.s', dram=True),
            Linked('degreeui', 'modules/harmony-degrees/ui.s', dram=True),
            Linked('degreepanel', 'modules/harmony-degrees/panel.s', dram=True),
            Linked('degreeoperations', 'modules/harmony-degrees/operations.s', dram=True),
            Linked('degreeedit', 'modules/harmony-degrees/edit-hooks.s', dram=True),
            Linked('degreepool', 'modules/harmony-degrees/pool.s', dram=True),
            Linked('degreehooks', 'modules/harmony-degrees/hooks.s', dram=True)),
    detours=(Detour(0x4004a93e, bytes.fromhex('47f940020898'), 'degreeedit', 'hd_memcpy',
                    'Part Save degree defaults', kind='lea'),
             Detour(0x4004ab02, bytes.fromhex('45f940020898'), 'degreeedit', 'hd_memcpy',
                    'Part Reload degree defaults', kind='lea'),
             Detour(0x4004a9f8, bytes.fromhex('45f940005638'), 'degreeedit', 'hd_part_init',
                    'Part Clear degree defaults', kind='lea'),
             Detour(0x40029a7c, bytes.fromhex('45f940020898'), 'degreeedit', 'hd_memcpy',
                    'Part paste and undo degree defaults', kind='lea'),
             Detour(0x4002c76c, bytes.fromhex('103c0001e7a8'), 'degreeedit', 'hd_step_apply',
                    'Degree identity after native step paste'),
             Detour(0x4009f9c6, bytes.fromhex('206effdc7110'), 'degreepool', 'hd_tick',
                    'Rebuild a sequence arp pool after a mode boundary')),
    gates=(Gate('tools/verify/verify_harmony_degree_codec.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_core.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_integration.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_publication.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_files.py', stage='image', venv=True)),
)
