| Generated by generate.py; edit operations.c / core.h.
#NO_APP
	.file	"operations.c"
	.text
	.align	2
	.type	canonical, @function
canonical:
	move.l %d2,-(%sp)
	moveq #15,%d2
	mvz.b -2147483646,%d1
	move.l 8(%sp),%d0
	cmp.l %d1,%d2
	jcs .L1
	move.l #635712,%d2
	muls.l %d2,%d1
	move.l %d0,%a0
	add.l #-268525902,%a0
	add.l #1074668000,%d1
	cmp.l #610375,%a0
	jhi .L9
	move.l %a0,%d0
	add.l %d1,%d0
.L1:
	move.l (%sp)+,%d2
	rts
.L9:
	add.l #-610376,%a0
	cmp.l #25287,%a0
	jhi .L1
	move.l (%sp)+,%d2
	add.l #-268525900,%d0
	add.l %d1,%d0
	rts
	.size	canonical, .-canonical
	.align	2
	.type	capture, @function
capture:
	lea (-24,%sp),%sp
	move.l 28(%sp),%d0
	movem.l #1036,(%sp)
	move.l #635712,%d2
	muls.l %d2,%d0
	move.l 44(%sp),%d1
	move.l %a0,%a2
	add.l #1074668000,%d0
	tst.l %d1
	jlt .L11
	move.l #6322,%d2
	moveq #3,%d3
	muls.l %d1,%d2
	move.l %d1,20(%sp)
	move.l %d2,%a0
	cmp.l %d1,%d3
	jcs .L12
	move.l 36(%sp),%d2
	add.l #585088,%a0
	lsl.l #5,%d2
	move.l %d2,%a1
	lea (994,%a1),%a1
	add.l %d0,%a1
	move.b (%a1,%a0.l),%d2
	move.l 36(%sp),-(%sp)
	move.l %d1,16(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	move.l 12(%sp),%d1
	tst.l %d0
	jne .L24
.L20:
	st %d1
.L14:
	move.b %d1,(%a2)
	move.b %d2,1(%a2)
	move.l %a2,%d0
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
.L12:
	move.l 36(%sp),%d2
	add.l #585090,%a0
	lsl.l #5,%d2
	move.l %d2,%a1
	lea (994,%a1),%a1
	add.l %d0,%a1
	move.b (%a1,%a0.l),%d2
	move.l 36(%sp),-(%sp)
	move.l %d1,16(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	move.l 12(%sp),%d1
	tst.l %d0
	jeq .L20
.L24:
	move.l 36(%sp),-(%sp)
	move.l %d1,-(%sp)
	move.l 36(%sp),-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	move.b %d0,%d1
.L15:
	mvz.b %d2,%d0
	cmp.l #255,%d0
	jeq .L14
	mvz.b %d1,%d3
	moveq #83,%d0
	move.l %d3,16(%sp)
	cmp.l %d3,%d0
	jcs .L14
	move.l 36(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l %d1,24(%sp)
	jsr hd_scale_c
	addq.l #8,%sp
	move.l %d0,(%sp)
	move.l %d3,-(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	move.l 12(%sp),%d1
	tst.l %d0
	jlt .L18
	move.b %d0,%d2
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b %d2,1(%a2)
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
.L11:
	move.l 32(%sp),%d1
	move.l #36568,%d2
	move.l #2224,%d3
	muls.l %d2,%d1
	move.l 36(%sp),%d2
	muls.l %d3,%d2
	add.l %d1,%d0
	mvz.w 42(%sp),%d1
	move.l %d0,%a1
	add.l #36439,%a1
	move.b (%a1),23(%sp)
	lsl.l #5,%d1
	move.l %d1,%a0
	lea (18688,%a0),%a0
	add.l %d2,%a0
	move.b (%a0,%d0.l),%d2
	move.l 36(%sp),-(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L20
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	moveq #3,%d1
	move.b 39(%sp),%d0
	and.l %d1,%d0
	move.l %d0,36(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	move.b %d0,%d1
	jra .L15
.L18:
	moveq #6,%d2
	cmp.l 16(%sp),%d2
	jlt .L21
	clr.b %d2
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b %d2,1(%a2)
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
.L21:
	moveq #127,%d2
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b %d2,1(%a2)
	movem.l (%sp),#1036
	lea (24,%sp),%sp
	rts
	.size	capture, .-capture
	.align	2
	.type	locate, @function
locate:
	lea (-28,%sp),%sp
	move.l 32(%sp),%d0
	movem.l #28,(%sp)
	cmp.l #1175224610,%d0
	jeq .L26
	cmp.l #1175187992,%d0
	jeq .L26
	move.l %d0,-(%sp)
	move.l %a0,16(%sp)
	jsr canonical
	addq.l #4,%sp
	add.l #-1074668000,%d0
	move.l 12(%sp),%a0
	cmp.l #10171391,%d0
	jhi .L35
	move.l #635712,%d1
	remu.l %d1,%d2:%d0
	divu.l %d1,%d0
	move.l 36(%sp),%d3
	move.l %d2,%a1
	cmp.l #6322,%d3
	jeq .L44
	move.l #36568,%d3
	remu.l %d3,%d1:%d2
	divu.l %d3,%d2
	move.l %d2,20(%sp)
	cmp.l #585087,%a1
	jhi .L38
	cmp.l 36(%sp),%d3
	jeq .L45
	move.l 36(%sp),%d3
	cmp.l #2224,%d3
	jeq .L46
.L38:
	movem.l (%sp),#28
	sub.l %a1,%a1
	clr.l 24(%sp)
	clr.l 16(%sp)
	clr.l %d1
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l 20(%sp),8(%a0)
	move.l %d1,20(%a0)
	move.l 24(%sp),12(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L26:
	cmp.l #1175187992,%d0
	seq %d1
	movem.l (%sp),#28
	move.w #1,%a1
	clr.l %d0
	clr.l 20(%sp)
	clr.l 24(%sp)
	clr.l 16(%sp)
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	mvs.b %d1,%d1
	move.l 20(%sp),8(%a0)
	neg.l %d1
	move.l 24(%sp),12(%a0)
	move.l %d1,20(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L35:
	movem.l (%sp),#28
	clr.l %d0
	sub.l %a1,%a1
	clr.l 20(%sp)
	clr.l 24(%sp)
	clr.l 16(%sp)
	clr.l %d1
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l 20(%sp),8(%a0)
	move.l %d1,20(%a0)
	move.l 24(%sp),12(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L44:
	move.l %d2,%d1
	add.l #-610378,%d1
	cmp.l #25287,%d1
	jls .L47
	move.l %d2,%d1
	add.l #-585088,%d1
	cmp.l #25287,%d1
	jhi .L36
	move.l %d1,%d4
	move.l #6322,%d2
	divu.l %d2,%d4
	clr.l 20(%sp)
	clr.l 24(%sp)
	move.l %d4,16(%sp)
	move.l #6322,%d4
	remu.l %d4,%d2:%d1
	clr.l %d1
	tst.l %d2
	seq %d3
	mvs.b %d3,%d4
	neg.l %d4
	lsl.l #2,%d4
	move.l %d4,%a1
.L48:
	movem.l (%sp),#28
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l 20(%sp),8(%a0)
	move.l %d1,20(%a0)
	move.l 24(%sp),12(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L45:
	tst.l %d1
	seq %d1
	clr.l 24(%sp)
	clr.l 16(%sp)
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l 20(%sp),8(%a0)
	move.l 24(%sp),12(%a0)
	mvs.b %d1,%d2
	clr.l %d1
	move.l %d1,20(%a0)
	neg.l %d2
	add.l %d2,%d2
	move.l 16(%sp),16(%a0)
	move.l %d2,%a1
	movem.l (%sp),#28
	move.l %a1,(%a0)
	lea (28,%sp),%sp
	rts
.L46:
	add.l #-18640,%d1
	cmp.l #17791,%d1
	jhi .L38
	move.l %d1,%d4
	move.l #2224,%d2
	remu.l %d2,%d3:%d4
	divu.l %d2,%d4
	move.l %d3,%d1
	tst.l %d3
	jne .L38
	move.l %d4,24(%sp)
	movem.l (%sp),#28
	move.w #3,%a1
	clr.l 16(%sp)
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l %d1,20(%a0)
	move.l 20(%sp),8(%a0)
	move.l 24(%sp),12(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L36:
	movem.l (%sp),#28
	sub.l %a1,%a1
	clr.l 20(%sp)
	clr.l 24(%sp)
	clr.l 16(%sp)
	clr.l %d1
	move.l %d0,4(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l 20(%sp),8(%a0)
	move.l %d1,20(%a0)
	move.l 24(%sp),12(%a0)
	move.l 16(%sp),16(%a0)
	lea (28,%sp),%sp
	rts
.L47:
	move.l %d1,%d4
	move.l %d3,%d2
	divu.l %d2,%d4
	clr.l 20(%sp)
	clr.l 24(%sp)
	move.l %d4,%a1
	move.l #6322,%d4
	remu.l %d4,%d2:%d1
	addq.l #4,%a1
	move.l %a1,16(%sp)
	clr.l %d1
	tst.l %d2
	seq %d3
	mvs.b %d3,%d4
	neg.l %d4
	lsl.l #2,%d4
	move.l %d4,%a1
	jra .L48
	.size	locate, .-locate
	.align	2
	.globl	hd_copy_before_c
	.type	hd_copy_before_c, @function
hd_copy_before_c:
	lea (-88,%sp),%sp
	movem.l #19516,(%sp)
	move.l 92(%sp),%a6
	move.l 96(%sp),%d2
	move.l 100(%sp),%d3
	clr.l transfer+1028
	clr.l base_count
	cmp.l #1175224610,%a6
	jeq .L50
	cmp.l #1175187992,%a6
	jeq .L50
	cmp.l #36568,%d3
	jeq .L52
	cmp.l #2224,%d3
	jeq .L52
	cmp.l #6322,%d3
	jne .L53
.L52:
	move.l %d3,-(%sp)
	move.l %a6,-(%sp)
	lea destination,%a0
	lea locate,%a6
	jsr (%a6)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	lea (80,%sp),%a0
	jsr (%a6)
	move.l 80(%sp),%d2
	move.l destination,%d0
	lea (16,%sp),%sp
	tst.l %d2
	jeq .L69
	tst.l %d0
	jeq .L49
	moveq #1,%d0
	cmp.l %d2,%d0
	jeq .L129
	moveq #2,%d4
	cmp.l %d2,%d4
	jeq .L79
	moveq #3,%d5
	cmp.l %d2,%d5
	jeq .L130
	moveq #8,%d4
	sub.l %a6,%a6
	move.l %d4,42(%sp)
	move.l 68(%sp),%d4
	move.l 72(%sp),46(%sp)
	lea capture,%a2
	lea transfer,%a3
.L77:
	moveq #2,%d0
	cmp.l %d2,%d0
	jeq .L131
	moveq #3,%d1
	cmp.l %d2,%d1
	jeq .L132
	moveq #4,%d5
	cmp.l %d2,%d5
	jne .L81
	move.l 80(%sp),%d1
	move.l %a6,%d0
.L75:
	move.l %d1,-(%sp)
	moveq #63,%d5
	move.l %a6,%d1
	and.l %d5,%d1
	move.l %d1,-(%sp)
	lea (70,%sp),%a0
	move.l %d0,-(%sp)
	move.l 58(%sp),-(%sp)
	move.l %d4,-(%sp)
	jsr (%a2)
	lea (82,%sp),%a0
	move.w (%a0),(%a3,%a6.l*2)
	addq.l #1,%a6
	lea (20,%sp),%sp
	cmp.l 42(%sp),%a6
	jne .L77
	moveq #1,%d0
	move.l %d0,transfer+1028
	move.l %d3,transfer+1024
.L49:
	movem.l (%sp),#19516
	lea (88,%sp),%sp
	rts
.L50:
	cmp.l #1175187992,%a6
	seq %d0
	lea base_counts,%a0
	mvs.b %d0,%d0
	neg.l %d0
	clr.l (%a0,%d0.l*4)
	cmp.l #36568,%d3
	jeq .L52
	cmp.l #2224,%d3
	jeq .L52
	cmp.l #6322,%d3
	jeq .L52
	move.l #1032,%d1
	muls.l %d1,%d0
	move.l %d0,%a0
	add.l #clips+1028,%a0
	clr.l (%a0)
.L53:
	move.l %d2,%d0
	add.l #-1175224610,%d0
	cmp.l #36567,%d0
	jls .L78
	add.l #36618,%d0
	cmp.l #36567,%d0
	jls .L133
	move.l %d2,-(%sp)
	jsr canonical
	addq.l #4,%sp
	move.l %d0,%d1
	add.l #-1074668000,%d1
	cmp.l #10171391,%d1
	jhi .L49
	move.l %d1,%d2
	move.l #635712,%d4
	divu.l %d4,%d2
	clr.l %d1
	sub.l %a1,%a1
	lea base_transfer,%a2
	move.l %d2,50(%sp)
	move.l #1074668994,%d2
	move.l 50(%sp),%d5
	sub.l %d0,%d2
	move.l %d2,58(%sp)
	muls.l %d4,%d5
	move.l %d5,54(%sp)
.L62:
	move.w %a1,%d2
	move.l 58(%sp),%d4
	add.l 54(%sp),%d4
	move.l %d4,46(%sp)
	clr.l %d4
	mulu.w #6322,%d2
	add.l #585088,%d2
	add.l 46(%sp),%d2
.L67:
	move.l %d0,%a0
	add.l %d2,%a0
	cmp.l %d0,%a0
	jcs .L65
	cmp.l %d3,%d2
	jcs .L134
.L65:
	addq.l #1,%d4
	add.l #32,%d2
	moveq #8,%d1
	cmp.l %d4,%d1
	jeq .L66
	move.l base_count,%d1
	moveq #7,%d5
	cmp.l %d1,%d5
	jcc .L67
.L66:
	addq.l #1,%a1
	moveq #8,%d1
	cmp.l %a1,%d1
	jeq .L49
	move.l base_count,%d1
	moveq #7,%d2
	cmp.l %d1,%d2
	jcs .L49
	moveq #3,%d2
	cmp.l %a1,%d2
	jcc .L62
	move.w %a1,%d2
	clr.l %d4
	mulu.w #6322,%d2
	add.l #585090,%d2
	add.l 46(%sp),%d2
	jra .L67
.L69:
	subq.l #1,%d0
	tst.l %d0
	jne .L49
	move.l destination+20,%d0
	move.l #1032,%d5
	muls.l %d5,%d0
	movem.l (%sp),#19516
	move.l %d0,%a0
	add.l #clips+1028,%a0
	clr.l (%a0)
	lea (88,%sp),%sp
	rts
.L79:
	move.l #512,%d1
	sub.l %a6,%a6
	move.l 68(%sp),%d4
	move.l %d1,42(%sp)
	move.l 72(%sp),46(%sp)
	lea capture,%a2
	lea transfer,%a3
	jra .L77
.L131:
	move.l %a6,%d0
	moveq #-1,%d1
	lsr.l #6,%d0
	jra .L75
.L132:
	move.l 76(%sp),%d0
	moveq #-1,%d1
	jra .L75
.L81:
	move.l %a6,%d0
	moveq #-1,%d1
	jra .L75
.L129:
	move.l 84(%sp),%d0
	move.l #1032,%d1
	muls.l %d1,%d0
	move.l %d0,%a1
	add.l #clips,%a1
	move.l 1028(%a1),%d0
	tst.l %d0
	jeq .L49
	cmp.l 1024(%a1),%d3
	jne .L49
	lea transfer,%a0
.L72:
	move.w (%a1)+,(%a0)+
	cmp.l #transfer+1024,%a0
	jne .L72
	move.l %d3,transfer+1024
	movem.l (%sp),#19516
	move.l %d0,transfer+1028
	lea (88,%sp),%sp
	rts
.L130:
	moveq #64,%d0
	sub.l %a6,%a6
	move.l 68(%sp),%d4
	move.l %d0,42(%sp)
	move.l 72(%sp),46(%sp)
	lea capture,%a2
	lea transfer,%a3
	jra .L77
.L134:
	move.l %a1,-(%sp)
	clr.l -(%sp)
	move.l %d4,-(%sp)
	clr.l -(%sp)
	lea (%a6,%d2.l),%a0
	move.l %d1,%d5
	addq.l #1,%d5
	move.l 66(%sp),-(%sp)
	move.l %a0,62(%sp)
	lea (82,%sp),%a0
	move.l %d1,58(%sp)
	move.l %d0,50(%sp)
	move.l %a1,54(%sp)
	move.l %d5,base_count
	moveq #6,%d5
	jsr capture
	move.l 58(%sp),%d1
	move.w 82(%sp),%a0
	lea (20,%sp),%sp
	muls.l %d5,%d1
	move.l 42(%sp),%d5
	move.w %a0,4(%a2,%d1.l)
	move.l 34(%sp),%a1
	move.l %d5,(%a2,%d1.l)
	move.l 30(%sp),%d0
	jra .L65
.L78:
	clr.l %d1
.L54:
	lea base_counts,%a0
	move.l (%a0,%d1.l*4),%d0
	tst.l %d0
	jeq .L49
	clr.b %d4
	moveq #6,%d5
	mulu.w #48,%d1
	muls.l %d5,%d0
	lea base_clips,%a1
	move.l %a6,%d5
	sub.l %d2,%d5
	move.l %d5,46(%sp)
	lea base_transfer+4,%a6
	lea (%a1,%d1.l),%a0
	add.l %d0,%d1
	move.b %d4,42(%sp)
	clr.l %d4
	add.l %a1,%d1
.L60:
	move.l (%a0),%d0
	move.l %d0,%a1
	sub.l %d2,%a1
	cmp.l %d2,%d0
	jcs .L58
	moveq #6,%d5
	muls.l %d4,%d5
	move.l %d5,%a2
	cmp.l %d3,%a1
	jcc .L58
	moveq #1,%d5
	lea (4,%a0),%a1
	addq.l #1,%d4
	move.w (%a1),(%a6,%a2.l)
	add.l 46(%sp),%d0
	move.b %d5,42(%sp)
	move.l #base_transfer,%d5
	move.l %d0,(%a2,%d5.l)
.L58:
	addq.l #6,%a0
	cmp.l %a0,%d1
	jne .L60
	tst.b 42(%sp)
	jeq .L49
	move.l %d4,base_count
	movem.l (%sp),#19516
	lea (88,%sp),%sp
	rts
.L133:
	moveq #1,%d1
	jra .L54
	.size	hd_copy_before_c, .-hd_copy_before_c
	.align	2
	.globl	hd_copy_after_c
	.type	hd_copy_after_c, @function
hd_copy_after_c:
	move.l transfer+1028,%d0
	lea (-40,%sp),%sp
	movem.l #7292,(%sp)
	tst.l %d0
	jeq .L198
	lea destination,%a2
	moveq #1,%d1
	move.l (%a2),%a0
	cmp.l %a0,%d1
	jeq .L199
	moveq #2,%d0
	cmp.l %a0,%d0
	jeq .L174
	moveq #3,%d1
	cmp.l %a0,%d1
	jeq .L200
	moveq #8,%d3
	clr.l %d2
	lea transfer,%a4
	lea hd_copy_note_c,%a3
.L167:
	move.b 1(%a4),%d1
	move.b (%a4),%d0
	moveq #2,%d5
	cmp.l %a0,%d5
	jeq .L201
.L161:
	mvz.b %d0,%d0
	moveq #3,%d5
	cmp.l %a0,%d5
	jeq .L202
	moveq #83,%d5
	cmp.l %d0,%d5
	jcc .L164
	moveq #-1,%d0
.L164:
	moveq #4,%d6
	cmp.l %a0,%d6
	jne .L179
	mvz.b %d1,%d1
	lea hd_copy_base_c,%a0
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	move.l %d2,-(%sp)
	move.l destination+16,-(%sp)
	addq.l #1,%d2
	move.l destination+4,-(%sp)
	jsr (%a0)
	lea (20,%sp),%sp
	cmp.l %d3,%d2
	jeq .L166
.L203:
	addq.l #2,%a4
	move.l (%a2),%a0
	moveq #2,%d5
	move.b 1(%a4),%d1
	move.b (%a4),%d0
	cmp.l %a0,%d5
	jne .L161
.L201:
	mvz.b %d0,%d0
	move.l %d2,%d5
	moveq #83,%d6
	lsr.l #6,%d5
	cmp.l %d0,%d6
	jcs .L177
.L162:
	mvz.b %d1,%d1
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	moveq #63,%d0
	and.l %d2,%d0
	move.l %d0,-(%sp)
	move.l %d5,-(%sp)
	move.l destination+8,-(%sp)
	move.l destination+4,-(%sp)
	jsr (%a3)
	lea (24,%sp),%sp
.L204:
	addq.l #1,%d2
	cmp.l %d3,%d2
	jne .L203
.L166:
	move.l destination+4,%d4
	move.l %d4,%d0
	movem.l (%sp),#7292
	lea (40,%sp),%sp
	rts
.L202:
	move.l destination+12,%d5
	moveq #83,%d6
	cmp.l %d0,%d6
	jcc .L162
.L177:
	mvz.b %d1,%d1
	moveq #-1,%d0
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	moveq #63,%d0
	and.l %d2,%d0
	move.l %d0,-(%sp)
	move.l %d5,-(%sp)
	move.l destination+8,-(%sp)
	move.l destination+4,-(%sp)
	jsr (%a3)
	lea (24,%sp),%sp
	jra .L204
.L179:
	mvz.b %d1,%d1
	move.l %d2,%d5
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	moveq #63,%d0
	and.l %d2,%d0
	move.l %d0,-(%sp)
	move.l %d5,-(%sp)
	move.l destination+8,-(%sp)
	move.l destination+4,-(%sp)
	jsr (%a3)
	lea (24,%sp),%sp
	jra .L204
.L174:
	move.l #512,%d3
	clr.l %d2
	lea transfer,%a4
	lea hd_copy_note_c,%a3
	jra .L167
.L198:
	tst.l base_count
	jeq .L137
	moveq #-1,%d4
	clr.l %d2
	lea base_transfer,%a2
	move.l %d4,36(%sp)
.L156:
	move.l (%a2),%d1
	move.l %d1,%d0
	move.w 4(%a2),%a3
	add.l #-1175224610,%d0
	cmp.l #36567,%d0
	jls .L173
	add.l #36618,%d0
	cmp.l #36567,%d0
	jls .L205
	move.l %d1,-(%sp)
	jsr canonical
	addq.l #4,%sp
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jls .L206
.L154:
	addq.l #1,%d2
	addq.l #6,%a2
	cmp.l base_count.l,%d2
	jcs .L156
	move.l 36(%sp),%d4
	move.l %d4,%d0
	movem.l (%sp),#7292
	lea (40,%sp),%sp
	rts
.L206:
	move.l %d0,%d5
	move.l #635712,%d1
	remu.l %d1,%d4:%d5
	divu.l %d1,%d5
	move.l %a3,%d0
	lsr.l #8,%d0
	moveq #83,%d6
	mvz.b %d0,%d0
	cmp.l %d0,%d6
	jcs .L193
	move.l %d0,%a4
	clr.l %d3
	move.w %a3,%d0
	move.l %d4,%a3
	lea (-994,%a3),%a3
	mvz.b %d0,%d0
	move.l %d0,32(%sp)
.L155:
	moveq #3,%d1
	cmp.l %d3,%d1
	jcc .L150
.L148:
	move.w %d3,%d0
	mulu.w #6322,%d0
	move.l %d0,%d1
	add.l #586084,%d1
	cmp.l %d4,%d1
	jhi .L151
	add.l #256,%d1
	cmp.l %d4,%d1
	jls .L151
	add.l #585090,%d0
	move.l %a3,%d1
	sub.l %d0,%d1
	moveq #31,%d0
	and.l %d1,%d0
	tst.l %d0
	jne .L151
.L153:
	lsr.l #5,%d1
	move.l 32(%sp),-(%sp)
	move.l %a4,-(%sp)
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	jsr hd_copy_base_c
	move.l %d5,56(%sp)
	lea (20,%sp),%sp
.L151:
	addq.l #1,%d3
	moveq #8,%d0
	cmp.l %d3,%d0
	jeq .L154
	moveq #3,%d1
	cmp.l %d3,%d1
	jcs .L148
.L150:
	move.w %d3,%d0
	mulu.w #6322,%d0
	move.l %d0,%d1
	add.l #586082,%d1
	cmp.l %d4,%d1
	jhi .L207
	move.l %d0,%d1
	add.l #586338,%d1
	cmp.l %d4,%d1
	jls .L194
	add.l #585088,%d0
	move.l %a3,%d1
	sub.l %d0,%d1
	moveq #31,%d0
	and.l %d1,%d0
	tst.l %d0
	jeq .L153
.L194:
	addq.l #1,%d3
	jra .L155
.L200:
	moveq #64,%d3
	clr.l %d2
	lea transfer,%a4
	lea hd_copy_note_c,%a3
	jra .L167
.L173:
	clr.l %d5
.L138:
	lea base_counts,%a0
	move.l (%a0,%d5.l*4),%d3
	tst.l %d3
	jeq .L140
	move.w %d5,%d0
	mulu.w #48,%d0
	move.l %d0,%a1
	clr.l %d0
	move.l %a1,%a0
	add.l #base_clips,%a0
.L141:
	addq.l #6,%a0
	cmp.l -6(%a0),%d1
	jeq .L208
	addq.l #1,%d0
	cmp.l %d0,%d3
	jne .L141
	moveq #8,%d6
	cmp.l %d3,%d6
	jeq .L154
	moveq #6,%d0
	moveq #48,%d4
	muls.l %d3,%d0
	muls.l %d5,%d4
	lea base_clips,%a0
	addq.l #1,%d3
	move.l %d0,%a4
	add.l #base_clips+4,%a4
	add.l %d4,%d0
	move.l %d1,(%a0,%d0.l)
	move.w %a3,(%a4,%a1.l)
.L168:
	lea base_counts,%a0
	move.l %d3,(%a0,%d5.l*4)
	jra .L154
.L208:
	moveq #6,%d4
	moveq #48,%d6
	muls.l %d0,%d4
	muls.l %d5,%d6
	add.l #base_clips+4,%a1
	move.l %d4,%a4
	move.w %d0,%d4
	lea (%a4,%d6.l),%a0
	move.l #base_clips,%d6
	move.l %d1,(%a0,%d6.l)
	mulu.w #6,%d4
	move.w %a3,(%a1,%d4.l)
	cmp.l %d3,%d0
	jne .L154
	addq.l #1,%d3
	jra .L168
.L207:
	addq.l #1,%d3
	moveq #4,%d6
	cmp.l %d3,%d6
	jne .L150
	moveq #5,%d3
	jra .L155
.L205:
	moveq #1,%d5
	jra .L138
.L193:
	move.w %a3,%d0
	move.l %d4,%a3
	clr.l %d3
	move.w #-1,%a4
	lea (-994,%a3),%a3
	mvz.b %d0,%d0
	move.l %d0,32(%sp)
	jra .L155
.L140:
	moveq #48,%d0
	moveq #1,%d3
	muls.l %d5,%d0
	lea base_clips,%a0
	move.l %d1,(%a0,%d0.l)
	move.w %d5,%d0
	lea base_clips+4,%a0
	mulu.w #48,%d0
	move.w %a3,(%a0,%d0.l)
	lea base_counts,%a0
	move.l %d3,(%a0,%d5.l*4)
	jra .L154
.L199:
	move.l destination+20,%d1
	move.l #1032,%d2
	lea transfer,%a0
	muls.l %d2,%d1
	move.l %d1,%a1
	add.l #clips,%a1
.L159:
	move.w (%a0)+,(%a1)+
	cmp.l #transfer+1024,%a0
	jne .L159
	move.l %d1,%a0
	add.l #clips,%a0
	lea transfer+1024,%a1
	move.l (%a1),1024(%a0)
	move.l %d0,1028(%a0)
.L137:
	moveq #-1,%d4
	move.l %d4,%d0
	movem.l (%sp),#7292
	lea (40,%sp),%sp
	rts
	.size	hd_copy_after_c, .-hd_copy_after_c
	.align	2
	.globl	hd_operations_reset_c
	.type	hd_operations_reset_c, @function
hd_operations_reset_c:
	clr.l transfer+1028
	clr.l clips+2060
	clr.l clips+1028
	clr.l base_count
	clr.l base_counts+4
	clr.l base_counts
	rts
	.size	hd_operations_reset_c, .-hd_operations_reset_c
	.align	2
	.globl	hd_part_reset_c
	.type	hd_part_reset_c, @function
hd_part_reset_c:
	lea (-44,%sp),%sp
	movem.l #19468,(%sp)
	move.l 48(%sp),%a2
	pea 6322.w
	lea (24,%sp),%a0
	move.l %a2,-(%sp)
	jsr locate
	addq.l #8,%sp
	moveq #4,%d0
	cmp.l 20(%sp),%d0
	jne .L211
	move.l 36(%sp),%d3
	sub.l %a6,%a6
	move.l 24(%sp),%d2
	lea (994,%a2),%a2
	lea hd_copy_base_c,%a3
.L213:
	mvz.b (%a2),%d0
	lea (32,%a2),%a2
	move.l %d0,-(%sp)
	pea -1.w
	move.l %a6,-(%sp)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr (%a3)
	addq.l #1,%a6
	lea (20,%sp),%sp
	moveq #8,%d0
	cmp.l %a6,%d0
	jne .L213
.L211:
	movem.l (%sp),#19468
	lea (44,%sp),%sp
	rts
	.size	hd_part_reset_c, .-hd_part_reset_c
	.align	2
	.globl	hd_step_copy_c
	.type	hd_step_copy_c, @function
hd_step_copy_c:
	lea (-48,%sp),%sp
	move.l 52(%sp),%d0
	movem.l #17436,(%sp)
	move.l 56(%sp),%a1
	move.l 64(%sp),%a0
	move.l 68(%sp),%d1
	move.l 60(%sp),30(%sp)
	cmp.l #1175224610,%d0
	jeq .L219
	cmp.l #1175187992,%d0
	jeq .L219
	movem.l (%sp),#17436
	move.l %d0,52(%sp)
	lea (48,%sp),%sp
	jra canonical
.L219:
	moveq #15,%d2
	cmp.l %a1,%d2
	jcs .L218
	moveq #7,%d3
	cmp.l 30(%sp),%d3
	jcs .L218
	moveq #3,%d4
	cmp.l %a0,%d4
	jcs .L218
	move.l 1187521622,%a6
	add.l #-1074668000,%a6
	cmp.l #10171391,%a6
	jhi .L218
	move.l %a6,%d2
	move.l #635712,%d3
	divu.l %d3,%d2
	cmp.l #1175187992,%d0
	seq %d0
	move.l %d2,42(%sp)
	mvs.b %d0,%d2
	neg.l %d0
	neg.l %d2
	move.l %d2,%a6
	tst.b %d0
	jne .L237
	move.l %a0,%d4
	move.l %a6,%d0
	lsl.l #4,%d4
	move.l #1032,%d2
	muls.l %d2,%d0
	lea base_counts,%a0
	clr.l (%a0,%a6.l*4)
	clr.l 34(%sp)
	move.l 34(%sp),%a2
	add.l #clips,%a2
	move.l %a2,34(%sp)
	move.l %d0,%a0
	moveq #1,%d0
	add.l #clips,%a0
	move.l %d4,38(%sp)
	sub.l %a6,%a6
	move.l %d0,1028(%a0)
	clr.l 1024(%a0)
.L226:
	move.l %a6,%d2
	btst %d2,%d1
	jne .L238
	addq.l #1,%a6
	moveq #16,%d0
	cmp.l %a6,%d0
	jne .L226
.L218:
	movem.l (%sp),#17436
	lea (48,%sp),%sp
	rts
.L237:
	move.l %a0,%d4
	move.l %a6,%d0
	lsl.l #4,%d4
	move.l #1032,%d2
	muls.l %d2,%d0
	lea base_counts,%a0
	clr.l (%a0,%a6.l*4)
	move.l #1032,%d3
	move.l %d3,34(%sp)
	move.l 34(%sp),%a2
	add.l #clips,%a2
	move.l %a2,34(%sp)
	move.l %d0,%a0
	moveq #1,%d0
	add.l #clips,%a0
	move.l %d4,38(%sp)
	sub.l %a6,%a6
	move.l %d0,1028(%a0)
	clr.l 1024(%a0)
	jra .L226
.L238:
	pea -1.w
	move.l 42(%sp),%a0
	pea (%a0,%a6.l)
	move.l 38(%sp),-(%sp)
	move.l %a1,-(%sp)
	move.l 58(%sp),-(%sp)
	lea (66,%sp),%a0
	move.l %d1,42(%sp)
	move.l %a1,46(%sp)
	jsr capture
	move.l 54(%sp),%a2
	lea (66,%sp),%a0
	moveq #16,%d0
	move.w (%a0),(%a2,%a6.l*2)
	lea (20,%sp),%sp
	addq.l #1,%a6
	move.l 26(%sp),%a1
	move.l 22(%sp),%d1
	cmp.l %a6,%d0
	jne .L226
	jra .L218
	.size	hd_step_copy_c, .-hd_step_copy_c
	.align	2
	.globl	hd_step_paste_c
	.type	hd_step_paste_c, @function
hd_step_paste_c:
	lea (-40,%sp),%sp
	movem.l #16412,(%sp)
	clr.l -(%sp)
	lea (20,%sp),%a0
	move.l 48(%sp),-(%sp)
	jsr locate
	addq.l #8,%sp
	moveq #1,%d0
	cmp.l 16(%sp),%d0
	jne .L242
	move.l 48(%sp),%d0
	moveq #15,%d1
	or.l 52(%sp),%d0
	cmp.l %d0,%d1
	jcs .L242
	moveq #7,%d2
	cmp.l 56(%sp),%d2
	jcs .L242
	moveq #63,%d3
	cmp.l 60(%sp),%d3
	jcs .L242
	move.l 36(%sp),%d1
	move.l #1032,%d0
	lea clips,%a1
	muls.l %d1,%d0
	lea (%a1,%d0.l),%a0
	tst.l 1028(%a0)
	jeq .L242
	tst.l 1024(%a0)
	jne .L242
	move.l 1187521622,%d0
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jhi .L242
	move.l %d0,%d4
	move.l #635712,%d2
	divu.l %d2,%d4
	move.l 48(%sp),%d0
	moveq #83,%d2
	move.l %d4,%a6
	move.l #516,%d4
	muls.l %d4,%d1
	add.l %d1,%d0
	mvz.b (%a1,%d0.l*2),%d1
	mvz.b 1(%a1,%d0.l*2),%d0
	cmp.l %d1,%d2
	jcs .L247
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	move.l 68(%sp),-(%sp)
	move.l 68(%sp),-(%sp)
	move.l 68(%sp),-(%sp)
	move.l %a6,-(%sp)
	jsr hd_copy_note_c
	lea (24,%sp),%sp
	move.l %a6,%d0
.L239:
	movem.l (%sp),#16412
	lea (40,%sp),%sp
	rts
.L247:
	move.l %d0,-(%sp)
	moveq #-1,%d1
	move.l %d1,-(%sp)
	move.l 68(%sp),-(%sp)
	move.l 68(%sp),-(%sp)
	move.l 68(%sp),-(%sp)
	move.l %a6,-(%sp)
	jsr hd_copy_note_c
	lea (24,%sp),%sp
	move.l %a6,%d0
	jra .L239
.L242:
	movem.l (%sp),#16412
	moveq #-1,%d0
	lea (40,%sp),%sp
	rts
	.size	hd_step_paste_c, .-hd_step_paste_c
	.local	base_count
	.comm	base_count,4,2
	.local	base_counts
	.comm	base_counts,8,2
	.local	base_transfer
	.comm	base_transfer,48,2
	.local	base_clips
	.comm	base_clips,96,2
	.local	destination
	.comm	destination,24,2
	.local	transfer
	.comm	transfer,1032,2
	.local	clips
	.comm	clips,2064,2
