| Generated by generate.py; edit storage.c / core.h.
#NO_APP
	.file	"storage.c"
	.text
	.align	2
	.globl	hd_payload_valid_c
	.type	hd_payload_valid_c, @function
hd_payload_valid_c:
	move.l 4(%sp),%a0
	move.l %a0,%d1
	add.l #8192,%d1
.L3:
	move.b (%a0),%d0
	addq.l #1,%a0
	subq.l #8,%d0
	mvz.b %d0,%d0
	cmp.l #246,%d0
	jls .L2
	cmp.l %d1,%a0
	jne .L3
	move.l %d1,4(%sp)
	jra hd_validate_c
.L2:
	clr.l %d0
	rts
	.size	hd_payload_valid_c, .-hd_payload_valid_c
	.align	2
	.globl	hd_payload_hash_c
	.type	hd_payload_hash_c, @function
hd_payload_hash_c:
	move.l %d2,-(%sp)
	move.l #-2128831035,%d0
	move.l 8(%sp),%d1
	move.l %d1,%a1
	lea (24960,%a1),%a1
.L8:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l %d1,%a1
	jne .L8
	move.l (%sp)+,%d2
	rts
	.size	hd_payload_hash_c, .-hd_payload_hash_c
	.align	2
	.globl	hd_export_c
	.type	hd_export_c, @function
hd_export_c:
	lea (-24,%sp),%sp
	moveq #15,%d0
	movem.l #1148,(%sp)
	move.l 28(%sp),%d3
	move.l 32(%sp),%d6
	cmp.l %d3,%d0
	jcc .L21
.L12:
	movem.l (%sp),#1148
	lea (24,%sp),%sp
	rts
.L21:
	move.l %d3,-(%sp)
	move.l #16768,%d5
	jsr hd_checkpoint_c
	muls.l %d3,%d5
	addq.l #4,%sp
	move.l %d3,-(%sp)
	lea hd_revision_c,%a2
	jsr (%a2)
	addq.l #4,%sp
	add.l #hd_banks,%d5
	move.l %d5,%d2
	move.l %d5,%a0
	add.l #16768,%d2
	move.l %d0,%d4
	move.l %d6,%a1
.L14:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d2
	jne .L14
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	cmp.l %d0,%d4
	jeq .L12
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	move.l %d5,%a0
	move.l %d6,%a1
	move.l %d0,%d4
	jra .L14
	.size	hd_export_c, .-hd_export_c
	.align	2
	.globl	hd_import_c
	.type	hd_import_c, @function
hd_import_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #15,%d0
	move.l 16(%sp),%d1
	move.l 20(%sp),%a0
	cmp.l %d1,%d0
	jcc .L31
.L22:
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L31:
	move.l %a0,-(%sp)
	move.l %d1,12(%sp)
	move.l %a0,8(%sp)
	jsr hd_validate_c
	addq.l #4,%sp
	move.l 8(%sp),%d1
	move.l 4(%sp),%a0
	tst.l %d0
	jeq .L22
	move.l #16768,%d2
	muls.l %d1,%d2
	move.l %a0,%d0
	add.l #16768,%d0
	move.l %d2,%a1
	add.l #hd_banks,%a1
.L24:
	move.b (%a0)+,(%a1)+
	cmp.l %a0,%d0
	jne .L24
	move.l %d1,16(%sp)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra hd_bank_loaded_c
	.size	hd_import_c, .-hd_import_c
	.align	2
	.globl	hd_native_hash_c
	.type	hd_native_hash_c, @function
hd_native_hash_c:
	moveq #15,%d0
	cmp.l 4(%sp),%d0
	jcs .L34
	move.l 8(%sp),%d0
	rts
.L34:
	clr.l %d0
	rts
	.size	hd_native_hash_c, .-hd_native_hash_c
	.align	2
	.globl	hd_nv_save_c
	.type	hd_nv_save_c, @function
hd_nv_save_c:
	lea (-32,%sp),%sp
	moveq #15,%d0
	movem.l #3324,(%sp)
	move.l 36(%sp),%d2
	cmp.l %d2,%d0
	jcc .L50
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L50:
	move.l %d2,-(%sp)
	jsr hd_checkpoint_c
#APP
| 17 "storage.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l %d2,ch_nv_bank
	addq.l #1,generation
#APP
| 21 "storage.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	addq.l #4,%sp
	move.l generation,%d4
	clr.l %d2
	lea hd_revision_c,%a2
	move.l ch_nv_bank,%d5
	move.l #-2128831035,%d3
	move.l %d5,-(%sp)
	jsr (%a2)
	clr.l 269452800
	addq.l #4,%sp
	moveq #13,%d1
	move.l %d0,%d6
	move.l %d5,%d0
	lsl.l %d1,%d0
	move.l #16768,%d1
	muls.l %d5,%d1
	move.l %d1,%a1
	add.l #hd_banks-8192,%a1
	move.l %d0,%a3
	add.l #ch_lock_table,%a3
.L42:
	move.l %d2,%a0
	add.l #269452832,%a0
	cmp.l generation.l,%d4
	jne .L39
	cmp.l #8191,%d2
	jls .L51
	move.b (%a1,%d2.l),%d1
	addq.l #1,%d2
	mvz.b %d1,%d0
	move.b %d1,(%a0)
	move.l #16777619,%d1
	eor.l %d0,%d3
	muls.l %d1,%d3
	cmp.l #24960,%d2
	jne .L42
.L39:
#APP
| 17 "storage.c" 1
	move.w %sr,%d7
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	cmp.l #24960,%d2
	jeq .L52
.L43:
#APP
| 21 "storage.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	move.l generation,%d4
	clr.l %d2
	move.l ch_nv_bank,%d5
	move.l #-2128831035,%d3
	move.l %d5,-(%sp)
	jsr (%a2)
	clr.l 269452800
	addq.l #4,%sp
	moveq #13,%d1
	move.l %d0,%d6
	move.l %d5,%d0
	lsl.l %d1,%d0
	move.l #16768,%d1
	muls.l %d5,%d1
	move.l %d1,%a1
	add.l #hd_banks-8192,%a1
	move.l %d0,%a3
	add.l #ch_lock_table,%a3
	jra .L42
.L52:
	cmp.l generation.l,%d4
	jne .L43
	move.l %d5,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	cmp.l %d0,%d6
	jne .L43
	moveq #2,%d0
	move.l %d0,269452804
	move.l %d5,269452808
	move.l %d2,269452812
	move.l %d3,269452816
	move.l %d4,269452820
	lea ch_lock_status,%a0
	mvz.b (%a0,%d5.l),%d0
	move.l %d0,269452824
	move.l #1212436018,%d0
	move.l 269452824,%d1
	not.l %d1
	move.l %d1,269452828
	move.l %d0,269452800
#APP
| 21 "storage.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L51:
	move.b (%a3,%d2.l),%d1
	addq.l #1,%d2
	mvz.b %d1,%d0
	move.b %d1,(%a0)
	eor.l %d0,%d3
	move.l #16777619,%d0
	muls.l %d0,%d3
	jra .L42
	.size	hd_nv_save_c, .-hd_nv_save_c
	.align	2
	.globl	hd_nv_restore_c
	.type	hd_nv_restore_c, @function
hd_nv_restore_c:
	move.l %d2,-(%sp)
	moveq #15,%d0
	cmp.l 8(%sp),%d0
	jcs .L56
	move.l #1212436018,%d1
	cmp.l 269452800.l,%d1
	jeq .L70
.L56:
	clr.l %d0
.L53:
	move.l (%sp)+,%d2
	rts
.L70:
	moveq #2,%d2
	cmp.l 269452804.l,%d2
	jne .L56
	move.l 8(%sp),%d0
	cmp.l 269452808.l,%d0
	jne .L56
	move.l #24960,%d1
	cmp.l 269452812.l,%d1
	jne .L56
	moveq #4,%d2
	cmp.l 269452824.l,%d2
	jcs .L56
	move.l 269452828,%d1
	move.l 269452824,%d0
	not.l %d0
	cmp.l %d1,%d0
	jne .L56
	move.l 269452816,%a1
	move.l #-2128831035,%d0
	move.l #269452832,%d1
.L57:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l #269477792,%d1
	jne .L57
	cmp.l %a1,%d0
	jne .L56
	move.l #269452832,%a0
.L58:
	move.b (%a0),%d0
	addq.l #1,%a0
	subq.l #8,%d0
	mvz.b %d0,%d0
	cmp.l #246,%d0
	jls .L56
	cmp.l #269461024,%a0
	jne .L58
	move.l %a0,-(%sp)
	jsr hd_validate_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L53
	move.l 8(%sp),%d1
	moveq #13,%d0
	move.l #269452832,%a1
	lsl.l %d0,%d1
	move.l #ch_lock_table,%d0
	sub.l %d1,%a1
	move.l %d1,%a0
	sub.l %d0,%a1
	add.l %d0,%a0
	add.l #ch_lock_table+8192,%d1
.L59:
	move.b (%a1,%a0.l),%d0
	move.b %d0,(%a0)+
	cmp.l %a0,%d1
	jne .L59
	move.l 8(%sp),%d1
	move.l #16768,%d2
	move.l #269461024,%a1
	muls.l %d2,%d1
	move.l %d1,%a0
	add.l #hd_banks,%a0
	add.l #hd_banks+16768,%d1
	sub.l %a0,%a1
.L60:
	move.b (%a1,%a0.l),%d0
	move.b %d0,(%a0)+
	cmp.l %d1,%a0
	jne .L60
	move.l 8(%sp),%d1
	move.l 269452824,%d0
	lea ch_lock_status,%a0
	move.l %d1,ch_nv_bank
	move.b %d0,(%a0,%d1.l)
	move.l %d1,-(%sp)
	jsr hd_bank_loaded_c
	addq.l #4,%sp
	move.l (%sp)+,%d2
	moveq #1,%d0
	rts
	.size	hd_nv_restore_c, .-hd_nv_restore_c
	.local	generation
	.comm	generation,4,2
