| Generated by generate.py; edit ui.c / core.h.
#NO_APP
	.file	"ui.c"
	.text
	.align	2
	.globl	hd_ui_value_c
	.type	hd_ui_value_c, @function
hd_ui_value_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L5
	move.b 269161680,%d1
	move.l %d0,%d2
	lsr.l #2,%d2
	mvz.b 269161676,%d3
	tst.l 16(%sp)
	jlt .L8
	mvz.b %d1,%d1
	move.l %d1,8(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	tst.l %d0
	jlt .L4
	bset #8,%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L8:
	moveq #3,%d1
	and.l %d0,%d1
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L4:
	move.l 16(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L5:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
	.size	hd_ui_value_c, .-hd_ui_value_c
	.align	2
	.globl	hd_ui_edit_c
	.type	hd_ui_edit_c, @function
hd_ui_edit_c:
	lea (-36,%sp),%sp
	movem.l #1276,(%sp)
	move.l 40(%sp),%d7
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L10
	move.b 269161680,%d2
	mvz.b 269161676,%d6
	moveq #7,%d1
	cmp.l %d6,%d1
	jcc .L11
.L10:
	clr.l %d0
.L9:
	movem.l (%sp),#1276
	lea (36,%sp),%sp
	rts
.L11:
	moveq #3,%d3
	and.l %d0,%d3
	lsr.l #2,%d0
	move.l %d6,-(%sp)
	move.l %d0,%a2
	move.l %d3,-(%sp)
	move.l %d0,-(%sp)
	jsr hd_part_type_c
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L10
	move.l 44(%sp),%d0
	or.l %d7,%d0
	jeq .L9
	tst.l 48(%sp)
	jeq .L44
	mvz.b %d2,%d2
	mvz.w 1175263050,%d5
	move.l 1175263052,%d3
	clr.l %d0
	move.l %d2,32(%sp)
	clr.l %d2
.L31:
	move.l %d5,%d4
	lsr.l %d2,%d4
	btst #0,%d4
	jeq .L20
	moveq #63,%d1
	cmp.l %d3,%d1
	jcs .L20
	move.l %d3,-(%sp)
	move.l %d6,-(%sp)
	move.l 40(%sp),-(%sp)
	move.l %a2,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l %d0,%d1
	tst.l 44(%sp)
	jne .L22
.L26:
	tst.l %d1
	jlt .L45
	move.l %d7,%a0
	moveq #-83,%d0
	cmp.l %d7,%d0
	jle .L27
.L46:
	move.w #-83,%a0
.L28:
	move.l %a0,%d0
	add.l %d1,%d0
	moveq #83,%d1
	cmp.l %d0,%d1
	jge .L29
.L47:
	moveq #83,%d0
.L25:
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d6,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a2,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
.L20:
	addq.l #1,%d2
	addq.l #1,%d3
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L31
	movem.l (%sp),#1276
	lea (36,%sp),%sp
	rts
.L45:
	moveq #35,%d1
	moveq #-83,%d0
	move.l %d7,%a0
	cmp.l %d7,%d0
	jgt .L46
.L27:
	moveq #83,%d0
	cmp.l %d7,%d0
	jge .L28
	move.w #83,%a0
	move.l %a0,%d0
	add.l %d1,%d0
	moveq #83,%d1
	cmp.l %d0,%d1
	jlt .L47
.L29:
	tst.l %d0
	jge .L25
	clr.l %d0
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d6,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a2,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
	jra .L20
.L22:
	move.l %d3,-(%sp)
	move.l %d6,-(%sp)
	move.l 40(%sp),-(%sp)
	move.l %a2,-(%sp)
	move.l %d0,44(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	move.l 28(%sp),%d1
	tst.l %d0
	jlt .L26
	move.l #255,%d0
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d6,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a2,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
	jra .L20
.L44:
	move.l %d6,-(%sp)
	move.l %d3,-(%sp)
	move.l %a2,-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	tst.l %d0
	jlt .L48
.L14:
	moveq #-83,%d1
	cmp.l %d7,%d1
	jle .L15
	moveq #-83,%d7
.L16:
	add.l %d0,%d7
	moveq #83,%d0
	cmp.l %d7,%d0
	jge .L17
	moveq #83,%d7
.L18:
	move.l %d7,-(%sp)
	move.l %d6,-(%sp)
	move.l %d3,-(%sp)
	move.l %a2,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
.L49:
	movem.l (%sp),#1276
	lea (36,%sp),%sp
	rts
.L48:
	moveq #35,%d0
	jra .L14
.L17:
	tst.l %d7
	jge .L18
	clr.l %d7
	move.l %d7,-(%sp)
	move.l %d6,-(%sp)
	move.l %d3,-(%sp)
	move.l %a2,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
	jra .L49
.L15:
	moveq #83,%d1
	cmp.l %d7,%d1
	jge .L16
	moveq #83,%d7
	jra .L16
	.size	hd_ui_edit_c, .-hd_ui_edit_c
