| Generated by generate.py; edit ui.c / core.h.
#NO_APP
	.file	"ui.c"
	.text
	.align	2
	.globl	hd_ui_value_c
	.type	hd_ui_value_c, @function
hd_ui_value_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	mvz.b -2147483646,%d3
	move.b 269161680,%d0
	mvz.b 269161676,%d2
	move.b 269161679,%d1
	tst.l 16(%sp)
	jlt .L7
	mvz.b %d0,%d0
	move.l %d0,8(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	tst.l %d0
	jlt .L4
	bset #8,%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L7:
	moveq #3,%d0
	and.l %d1,%d0
	move.l %d2,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L4:
	move.l 16(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
	.size	hd_ui_value_c, .-hd_ui_value_c
	.align	2
	.globl	hd_ui_edit_c
	.type	hd_ui_edit_c, @function
hd_ui_edit_c:
	lea (-36,%sp),%sp
	moveq #7,%d0
	movem.l #3324,(%sp)
	move.l 40(%sp),%d6
	move.b -2147483646,%d7
	move.b 269161680,%d2
	mvz.b 269161676,%d5
	move.b 269161679,%d3
	cmp.l %d5,%d0
	jcc .L40
.L9:
	clr.l %d0
.L8:
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L40:
	move.l %d5,-(%sp)
	jsr hd_type_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L9
	move.l 44(%sp),%d0
	or.l %d6,%d0
	jeq .L8
	mvz.b %d7,%d7
	tst.l 48(%sp)
	jeq .L41
	mvz.w 1175263050,%d1
	mvz.b %d2,%d2
	move.l 1175263052,%d3
	clr.l %d0
	move.l %d1,%a3
	move.l %d2,%a2
	clr.l %d2
.L30:
	move.l %a3,%d4
	lsr.l %d2,%d4
	btst #0,%d4
	jeq .L19
	moveq #63,%d1
	cmp.l %d3,%d1
	jcs .L19
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %a2,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l %d0,%d1
	tst.l 44(%sp)
	jne .L21
.L25:
	tst.l %d1
	jlt .L42
	move.l %d6,%a0
	moveq #-83,%d0
	cmp.l %d6,%d0
	jle .L26
.L43:
	move.w #-83,%a0
.L27:
	move.l %a0,%d0
	add.l %d1,%d0
	moveq #83,%d1
	cmp.l %d0,%d1
	jge .L28
.L44:
	moveq #83,%d0
.L24:
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %a2,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
.L19:
	addq.l #1,%d2
	addq.l #1,%d3
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L30
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L42:
	moveq #35,%d1
	moveq #-83,%d0
	move.l %d6,%a0
	cmp.l %d6,%d0
	jgt .L43
.L26:
	moveq #83,%d0
	cmp.l %d6,%d0
	jge .L27
	move.w #83,%a0
	move.l %a0,%d0
	add.l %d1,%d0
	moveq #83,%d1
	cmp.l %d0,%d1
	jlt .L44
.L28:
	tst.l %d0
	jge .L24
	clr.l %d0
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %a2,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
	jra .L19
.L21:
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %a2,-(%sp)
	move.l %d7,-(%sp)
	move.l %d0,48(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	move.l 32(%sp),%d1
	tst.l %d0
	jlt .L25
	move.l #255,%d0
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %a2,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d4,%d0
	jra .L19
.L41:
	moveq #3,%d1
	and.l %d1,%d3
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	tst.l %d0
	jlt .L45
	moveq #-83,%d1
	cmp.l %d6,%d1
	jgt .L46
.L14:
	moveq #83,%d1
	cmp.l %d6,%d1
	jlt .L47
	add.l %d0,%d6
	moveq #83,%d0
	cmp.l %d6,%d0
	jlt .L48
.L16:
	tst.l %d6
	jlt .L49
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
.L50:
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L48:
	moveq #83,%d6
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
	jra .L50
.L47:
	moveq #83,%d6
	add.l %d0,%d6
	moveq #83,%d0
	cmp.l %d6,%d0
	jge .L16
	jra .L48
.L46:
	moveq #-83,%d6
	add.l %d0,%d6
	moveq #83,%d0
	cmp.l %d6,%d0
	jge .L16
	jra .L48
.L45:
	moveq #35,%d0
	moveq #-83,%d1
	cmp.l %d6,%d1
	jle .L14
	jra .L46
.L49:
	clr.l %d6
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %d7,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
	jra .L50
	.size	hd_ui_edit_c, .-hd_ui_edit_c
