#!/usr/bin/env python3
"""Generate the freestanding ColdFire codec, following Euclid's C workflow."""
import pathlib
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
FLAGS = ['-mcpu=5475', '-msoft-float', '-O2', '-ffreestanding', '-fno-builtin',
         '-fno-common', '-fno-jump-tables', '-fno-asynchronous-unwind-tables',
         '-fno-ident', '-fomit-frame-pointer', '-Wall', '-Wextra', '-Werror']


def generate():
    with tempfile.TemporaryDirectory() as td:
        asm = pathlib.Path(td) / 'retention.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S',
                        'modules/plocks-p2/retention.c', '-o', str(asm)], cwd=ROOT, check=True)
        source = asm.read_text()
        if '*8)' in source:
            raise RuntimeError('hardware-unsafe scaled-*8 ColdFire address mode')
        return '| Generated by generate_retention.py; edit retention.c.\n' + source


if __name__ == '__main__':
    source = generate()
    dest = HERE / 'retention.s'
    if '--check' in sys.argv:
        if not dest.exists() or source != dest.read_text():
            sys.exit('PLOCKS P2 retention.s is stale: run modules/plocks-p2/generate_retention.py')
        print('PLOCKS P2 ColdFire source matches retention.c')
    else:
        dest.write_text(source)
