"""MIDI SCENES -- MIDISC2.1 from bkkbrls-del/midisc.

MIDI-driven scene locks. Upstream submodule is midisc main after PR #8
(52eaab0): gas/msc21_*.s regenerated by tools/gas_port21.py from
release21.json (written bytes only; gaps are .skip). Stock-site rewrites
come from upstream/tools/midisc/hooks21.py. Octabam adds the playback
detour at 0x400a4ba0 -> engine_follow (not in hooks21; his boot redirect
site). Part-window claim at 0x90492 holds the MSC freeze twin + sparse blob.

Behaviour vs 8.2 / MIDISC2.0 (upstream TECH notes + release21):
- Pre-trig XF / scene activation on the published playback path
- Queued pattern/Part scene publish at the native first-step boundary;
  manual Part apply publishes immediately
- Sequencer ACT bank/pattern commit (0x400a44f4) follows play_bank/play_part
- due_unlocked respects the native active-lock mask
- Native CC loops before same-track note-ons
- Recorder/master descriptors restored; scene scratch off native clipboard

New / retained stock sites beyond the 2.0 MIDI SCENES port (one line each):
- 0x4004ABC0 -- part-window / apply path through his cave
- 0x40062216 -- bank/part helper jsr into his cave
- 0x40087EAC -- bank publish related move into his cave
- 0x4009FAAA -- MIDI/engine path jmp into his cave
- 0x4009FE4E -- poke: redirect into his continuation
- 0x400A169A -- MIDI sequencer path jmp into his cave
- 0x400A19DA -- MIDI sequencer path jmp into his cave
- 0x400A1D32 -- MIDI sequencer path jmp into his cave
- 0x400A3C2A -- MIDI/engine path jmp into his cave
- 0x400A44F4 -- pattern-commit sync (play_bank/play_part); RTS-safe cave
- 0x400A4BA0 -- octabam: engine_follow (playback step uses engine latch)

Exports for a later KITS PR: msc_follow, msc_kit_commit, engine_follow.
Nothing in octabam calls those yet; 2.1 runs beside KITS via stock Part
apply/reload the way 2.0 did.
"""

import importlib.util
import pathlib

from remix.schema import Gate, Category, Proof, Claims, Detour, Kind, Linked, Module, Poke

UP = "modules/midi-scenes/upstream/gas/"
H = bytes.fromhex

UNITS = (
    Linked("msc21_ram", UP + "msc21_ram.s", dram=True),
    Linked("msc21_a", UP + "msc21_a.s", dram=True),
    Linked("msc21_b", UP + "msc21_b.s", dram=True),
    Linked("msc21_c", UP + "msc21_c.s", dram=True),
    Linked("msc21", UP + "msc21.s", dram=True),  # engine_follow, msc_follow
)

_p = pathlib.Path(__file__).parent / "upstream/tools/midisc/hooks21.py"
_s = importlib.util.spec_from_file_location("midisc_hooks21", _p)
_h = importlib.util.module_from_spec(_s)
_s.loader.exec_module(_h)
_DETOURS, POKES = _h.hooks(Detour, Poke)

DETOURS = _DETOURS + (
    Detour(0x400A4BA0, H("45f9800065e4"), "msc21", "engine_follow",
           "playback step, following the engine's latched Part"),
)

MODULE = Module(
    name="midi-scenes",
    key="MIDI SCENES",
    kind=Kind.CF_PATCH,
    category=Category.PARTS,
    author="bkkbrls-del/midisc",
    author_url="https://github.com/bkkbrls-del/midisc",
    proof=Proof.PORT,
    proof_note="MIDISC2.1 clusters proven vs release21.json; pin 52eaab0",
    doc="MIDI-driven scene locks (MIDISC2.1), linker-placed msc21 units.",
    linked=UNITS,
    detours=DETOURS,
    pokes=POKES,
    claims=Claims(part_window=((0x90492, 288, "MSC freeze twin + sparse blob"),)),
    gates=(Gate("tools/verify/verify_midiscenes.py", remix_arg=False),),
)
