| Generated by generate.py; edit core.c / core.h.
#NO_APP
	.file	"core.c"
	.text
	.align	2
	.type	part_dirty, @function
part_dirty:
	move.l %d2,-(%sp)
	move.l #635712,%d1
	move.l 8(%sp),%d0
	move.l #610376,%a1
	move.l 12(%sp),%d2
	muls.l %d1,%d0
	moveq #1,%d1
	lsl.l %d2,%d1
	move.l %d0,%a0
	add.l #1074668000,%a0
	move.b (%a0,%a1.l),%d0
	or.l %d1,%d0
	move.b %d0,(%a0,%a1.l)
	cmp.l 1187521622.l,%a0
	jeq .L6
	move.l #635698,%a1
	moveq #1,%d0
	move.l %d0,(%a0,%a1.l)
	cmp.l 1187521622.l,%a0
	jeq .L7
.L1:
	move.l (%sp)+,%d2
	rts
.L7:
	move.l (%sp)+,%d2
	move.l %d0,269452696
	rts
.L6:
	move.b 269161566,%d0
	move.l #635698,%a1
	or.l %d0,%d1
	moveq #1,%d0
	move.b %d1,269161566
	move.l %d0,(%a0,%a1.l)
	cmp.l 1187521622.l,%a0
	jne .L1
	jra .L7
	.size	part_dirty, .-part_dirty
	.align	2
	.type	write_native, @function
write_native:
	move.l 4(%sp),-(%sp)
	jsr hd_nv_dirty_c
	move.l 12(%sp),%a0
	move.l 8(%sp),%d0
	move.l #635712,%d1
	move.b 19(%sp),(%a0)
	addq.l #4,%sp
	muls.l %d1,%d0
	add.l #1074668000,%d0
	move.l 1187521622,%d1
	cmp.l %d1,%d0
	jne .L8
	move.l %a0,%d0
	sub.l %d1,%d0
	cmp.l #585087,%d0
	jhi .L10
.L12:
	add.l #268525902,%d0
	move.l %d0,%a0
	move.b 15(%sp),(%a0)
.L8:
	rts
.L10:
	move.l %d0,%d1
	add.l #-585088,%d1
	cmp.l #25287,%d1
	jls .L12
	move.l %d0,%d1
	add.l #-610378,%d1
	cmp.l #25287,%d1
	jhi .L8
	add.l #268525900,%d0
	move.l %d0,%a0
	move.b 15(%sp),(%a0)
	rts
	.size	write_native, .-write_native
	.align	2
	.type	hd_scale_c.part.0, @function
hd_scale_c.part.0:
	lea (-28,%sp),%sp
	movem.l #1276,(%sp)
	move.l 32(%sp),%a2
	move.l 36(%sp),%d4
	move.l 40(%sp),%d6
	jsr hd_follow_c
	tst.l %d0
	jeq .L16
	moveq #1,%d7
	moveq #3,%d0
	lsl.l %d6,%d7
	cmp.l %d4,%d0
	jcc .L42
	move.w %d4,%d0
	move.w %d6,%d3
	move.l #635712,%d2
	move.l %a2,%d1
	muls.l %d2,%d1
	mulu.w #6322,%d0
	mulu.w #36,%d3
	move.l %d0,%a0
	add.l %d3,%a0
	add.l %d1,%a0
	add.l #1075254343,%a0
	mvz.b (%a0),%d2
	tst.l %d2
	jeq .L20
	moveq #8,%d5
	cmp.l %d2,%d5
	jcs .L20
	subq.l #1,%d2
	btst %d2,%d7
	jne .L20
.L21:
	move.l %d2,-(%sp)
	moveq #63,%d5
	jsr hd_play_context_c
	addq.l #4,%sp
	cmp.l %d0,%d5
	jcs .L16
	moveq #1,%d1
	moveq #3,%d3
	lsl.l %d2,%d1
	and.l %d0,%d3
	move.l %d0,%d5
	lsr.l #2,%d5
	or.l %d1,%d7
.L22:
	mvz.w %d5,%d0
	pea 3.w
	move.l %d3,%a0
	pea (%a0,%d0.l*4)
	move.l %d2,-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L43
	moveq #8,%d1
	cmp.l %d0,%d1
	jcs .L16
	move.l %d0,%d2
	subq.l #1,%d2
	btst %d2,%d7
	jeq .L21
.L16:
	moveq #3,%d0
	cmp.l %d4,%d0
	jcc .L18
	move.w %d4,%d0
	move.w %d6,%d3
	move.l %a2,%d1
	move.l #635712,%d2
	muls.l %d2,%d1
	mulu.w #6322,%d0
	mulu.w #36,%d3
.L20:
	move.l %d0,%a0
	add.l %d3,%a0
	add.l %d1,%a0
	add.l #1075254357,%a0
	mvz.b (%a0),%d2
	moveq #83,%d0
	move.l %d2,%d1
	subq.l #1,%d1
	cmp.l %d1,%d0
	jcs .L27
.L24:
	moveq #24,%d5
	cmp.l %d2,%d5
	jcs .L26
	moveq #1,%d0
	and.l %d1,%d0
	lsr.l #1,%d1
	movem.l (%sp),#1276
	mulu.w #80,%d0
	add.l %d1,%d0
	mvz.w %d0,%d0
	lsl.l #2,%d0
	lea (28,%sp),%sp
	rts
.L26:
	jsr hd_scales_c
	tst.l %d0
	jeq .L27
	moveq #5,%d1
	add.l #-25,%d2
	remu.l %d1,%d0:%d2
	divu.l %d1,%d2
	lea (modes.0),%a0
	move.l (%a0,%d0.l*4),%d0
	lsl.l #4,%d0
	add.l %d2,%d0
	mvz.w %d0,%d0
	movem.l (%sp),#1276
	lsl.l #2,%d0
	lea (28,%sp),%sp
	rts
.L43:
	move.l %d2,%d6
	move.l %d5,%a2
	move.l %d3,%d4
.L18:
	mvz.w %a2,%d5
	move.l %d4,%a0
	pea (%a0,%d5.l*4)
	move.l %d6,-(%sp)
	jsr hd_part_key_c
	addq.l #8,%sp
	move.l %d0,%d2
	moveq #83,%d0
	move.l %d2,%d1
	subq.l #1,%d1
	cmp.l %d1,%d0
	jcc .L24
.L27:
	movem.l (%sp),#1276
	clr.l %d0
	lea (28,%sp),%sp
	rts
.L42:
	move.l %d6,%d2
	move.l %a2,%d5
	move.l %d4,%d3
	jra .L22
	.size	hd_scale_c.part.0, .-hd_scale_c.part.0
	.align	2
	.type	hd_context_depends_c.part.0, @function
hd_context_depends_c.part.0:
	lea (-32,%sp),%sp
	movem.l #7292,(%sp)
	move.l 40(%sp),%d2
	moveq #1,%d4
	move.l 36(%sp),%d3
	move.l 44(%sp),%d5
	lsl.l %d2,%d4
	lea hd_follow_c,%a2
	lea hd_part_read_c,%a3
	lea hd_play_context_c,%a4
.L48:
	cmp.l %d3,%d5
	jeq .L49
	jsr (%a2)
	tst.l %d0
	jeq .L47
	pea 3.w
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr (%a3)
	lea (12,%sp),%sp
	moveq #7,%d1
	move.l %d0,%d2
	moveq #1,%d0
	subq.l #1,%d2
	lsl.l %d2,%d0
	cmp.l %d2,%d1
	jcs .L47
	btst %d2,%d4
	jne .L47
	move.l %d2,-(%sp)
	or.l %d0,%d4
	jsr (%a4)
	addq.l #4,%sp
	move.l %d0,%d3
	moveq #63,%d0
	cmp.l %d3,%d0
	jcc .L48
.L47:
	movem.l (%sp),#7292
	clr.l %d0
	lea (32,%sp),%sp
	rts
.L49:
	movem.l (%sp),#7292
	moveq #1,%d0
	lea (32,%sp),%sp
	rts
	.size	hd_context_depends_c.part.0, .-hd_context_depends_c.part.0
	.align	2
	.type	hd_bank_loaded_c.part.0, @function
hd_bank_loaded_c.part.0:
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	move.l 12(%sp),%d3
	move.l %d3,%d2
	lsl.l #7,%d2
	clr.l %d0
	lea revision,%a1
	move.w %d3,%d1
	mulu.w #16768,%d1
	move.l %d1,%a0
	add.l #hd_banks+130,%a0
.L53:
	move.l %d2,%d1
	add.l %d0,%d1
	move.b #-1,(%a0)
	addq.l #1,(%a1,%d1.l*4)
	addq.l #1,%d0
	lea (131,%a0),%a0
	cmp.l #128,%d0
	jne .L53
	move.l (%sp)+,%d2
	lea bank_revision,%a0
	addq.l #1,(%a0,%d3.l*4)
	move.l (%sp)+,%d3
	rts
	.size	hd_bank_loaded_c.part.0, .-hd_bank_loaded_c.part.0
	.align	2
	.type	hd_record_publish_c.part.0, @function
hd_record_publish_c.part.0:
	lea (-32,%sp),%sp
	mvz.w 42(%sp),%d1
	movem.l #1036,(%sp)
	move.l 52(%sp),%d0
	move.l %d0,%a0
	move.l 44(%sp),%d3
	lsl.l #3,%d1
	move.l 36(%sp),%d2
	lea (-128,%a0),%a0
	add.l %d1,%d3
	moveq #127,%d1
	cmp.l %a0,%d1
	jcc .L69
	moveq #83,%d1
	cmp.l %d0,%d1
	jcs .L57
.L72:
	move.l #16768,%d1
	muls.l %d2,%d1
	move.l %d1,%a1
	move.l #131,%d1
	muls.l %d3,%d1
	lea (%a1,%d1.l),%a0
	add.l #hd_banks,%a0
	mvz.b 128(%a0),%d1
	move.l %d1,%a1
	moveq #2,%d1
	cmp.l %a1,%d1
	jeq .L70
.L57:
	movem.l (%sp),#1036
	lea (32,%sp),%sp
	rts
.L69:
	move.l #635712,%d1
	muls.l %d2,%d1
	move.l %d1,%a1
	add.l #1074668000,%a1
	mvz.w 50(%sp),%d1
	move.l %a1,20(%sp)
	move.l %d1,%a0
	moveq #127,%d1
	and.l %d0,%d1
	move.w 42(%sp),%d0
	move.l %d1,24(%sp)
	mulu.w #36568,%d0
	move.w 46(%sp),%d1
	move.l %d0,28(%sp)
	move.l %a0,%d0
	lsl.l #5,%d0
	move.l 24(%sp),-(%sp)
	mulu.w #2224,%d1
	move.l %d0,%a0
	lea (18688,%a0),%a0
	add.l %d1,%a0
	add.l 32(%sp),%a0
	pea (%a1,%a0.l)
	move.l %d2,-(%sp)
	jsr write_native
	lea (12,%sp),%sp
	move.l #16768,%d0
	move.l #131,%d1
	muls.l %d2,%d0
	muls.l %d3,%d1
	move.l %d1,%a0
	add.l %d0,%a0
	add.l #hd_banks,%a0
	move.b 128(%a0),%d0
	mvz.b %d0,%d1
	move.l %d1,%a1
	moveq #2,%d1
	cmp.l %a1,%d1
	jeq .L71
	tst.b %d0
	jeq .L61
	st %d0
	move.l 48(%sp),%d1
	lea (27,%sp),%a2
	move.b (%a2),64(%a0,%d1.l)
	move.b %d0,(%a0,%d1.l)
.L61:
	move.l %d2,-(%sp)
	jsr hd_nv_dirty_c
	addq.l #4,%sp
	move.l %d2,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l %d3,%d0
	addq.l #1,(%a1,%d0.l*4)
	move.l 20(%sp),%a1
	moveq #1,%d0
	addq.l #1,(%a0,%d2.l*4)
	move.l #635698,%a0
	move.l %d0,(%a1,%a0.l)
	cmp.l 1187521622.l,%a1
	jne .L57
.L65:
	movem.l (%sp),#1036
	move.l %d0,269452696
	lea (32,%sp),%sp
	rts
.L70:
	move.l 48(%sp),%a1
	move.b %d0,(%a0,%a1.l)
	move.l %d0,-(%sp)
	move.l %a0,16(%sp)
	jsr hd_mirror_c
	move.l 52(%sp),%a2
	move.l #635712,%d1
	muls.l %d2,%d1
	move.l 16(%sp),%a0
	move.b %d0,64(%a2,%a0.l)
	mvz.b %d0,%d0
	move.l %d1,24(%sp)
	mvz.w 54(%sp),%d1
	lsl.l #5,%d1
	move.l %d0,-(%sp)
	move.w 54(%sp),%d0
	move.l 28(%sp),%a2
	add.l #1074668000,%a2
	move.l %a2,24(%sp)
	move.l %d1,%a1
	move.w 50(%sp),%d1
	lea (18688,%a1),%a1
	mulu.w #2224,%d0
	mulu.w #36568,%d1
	add.l %a1,%d0
	add.l %d1,%d0
	pea (%a2,%d0.l)
	move.l %d2,-(%sp)
	jsr write_native
	move.l %d2,-(%sp)
	jsr hd_nv_dirty_c
	lea (20,%sp),%sp
	move.l %d2,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l %d3,%d0
	addq.l #1,(%a1,%d0.l*4)
	addq.l #1,(%a0,%d2.l*4)
	moveq #1,%d0
	move.l #635698,%a0
	move.l %d0,(%a2,%a0.l)
	cmp.l 1187521622.l,%a2
	jeq .L65
	movem.l (%sp),#1036
	lea (32,%sp),%sp
	rts
.L71:
	move.l 28(%sp),%a0
	add.l #36439,%a0
	move.l 20(%sp),%a1
	moveq #3,%d1
	mvz.b (%a1,%a0.l),%d0
	cmp.l %d0,%d1
	jcs .L57
	and.l %d0,%d1
	move.l 44(%sp),-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr (hd_scale_c.part.0)
	move.l %d0,-(%sp)
	move.l 40(%sp),-(%sp)
	jsr hd_encode_c
	lea (20,%sp),%sp
	moveq #83,%d1
	cmp.l %d0,%d1
	jcc .L72
	jra .L57
	.size	hd_record_publish_c.part.0, .-hd_record_publish_c.part.0
	.align	2
	.globl	hd_revision_c
	.type	hd_revision_c, @function
hd_revision_c:
	move.l 4(%sp),%d0
	moveq #15,%d1
	cmp.l %d0,%d1
	jcs .L75
	lea bank_revision,%a0
	move.l (%a0,%d0.l*4),%d0
	rts
.L75:
	clr.l %d0
	rts
	.size	hd_revision_c, .-hd_revision_c
	.align	2
	.globl	hd_pattern_context_c
	.type	hd_pattern_context_c, @function
hd_pattern_context_c:
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 12(%sp),%d1
	move.l %d1,%d0
	or.l 16(%sp),%d0
	cmp.l %d0,%d2
	jcs .L81
	move.l 16(%sp),%d3
	move.l #635712,%d0
	move.l #36568,%d2
	muls.l %d1,%d0
	muls.l %d2,%d3
	move.l %d3,%a0
	add.l %d0,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d0
	moveq #3,%d3
	cmp.l %d0,%d3
	jcs .L81
	move.l %d0,%a0
	lea (%a0,%d1.l*4),%a0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	move.l %a0,%d0
	rts
.L81:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	move.l (%sp)+,%d3
	rts
	.size	hd_pattern_context_c, .-hd_pattern_context_c
	.align	2
	.globl	hd_part_type_c
	.type	hd_part_type_c, @function
hd_part_type_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	moveq #15,%d0
	move.l %d2,-(%sp)
	cmp.l 16(%sp),%d0
	jcs .L90
	move.l 20(%sp),%d0
	moveq #7,%d1
	or.l 24(%sp),%d0
	cmp.l %d0,%d1
	jcs .L90
	moveq #3,%d2
	cmp.l 20(%sp),%d2
	jcc .L93
	move.l 24(%sp),%d0
	moveq #36,%d1
	move.l #635712,%d2
	move.l 20(%sp),%d3
	muls.l %d1,%d0
	move.l 16(%sp),%d1
	muls.l %d2,%d1
	move.l #6322,%d2
	muls.l %d2,%d3
	move.l %d0,%a0
	add.l #586345,%a0
	move.l %d1,%a1
	add.l #1074668000,%a1
	add.l %d3,%a0
	moveq #2,%d3
	mvz.b (%a1,%a0.l),%d0
	cmp.l %d0,%d3
	jcs .L90
.L84:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L90:
	move.l (%sp)+,%d2
	clr.l %d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L93:
	pea 5.w
	moveq #2,%d3
	move.l 20(%sp),%d0
	move.l 24(%sp),%a0
	pea (%a0,%d0.l*4)
	move.l 32(%sp),-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	cmp.l %d0,%d3
	jcc .L84
	jra .L90
	.size	hd_part_type_c, .-hd_part_type_c
	.align	2
	.globl	hd_scale_c
	.type	hd_scale_c, @function
hd_scale_c:
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 8(%sp),%d0
	cmp.l %d0,%d2
	jcs .L96
	move.l 12(%sp),%d2
	or.l 16(%sp),%d2
	move.l %d2,%a0
	moveq #7,%d2
	cmp.l %a0,%d2
	jcs .L96
	move.l %d0,8(%sp)
	move.l (%sp)+,%d2
	jra (hd_scale_c.part.0)
.L96:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
	.size	hd_scale_c, .-hd_scale_c
	.align	2
	.globl	hd_context_depends_c
	.type	hd_context_depends_c, @function
hd_context_depends_c:
	move.l %d2,-(%sp)
	moveq #63,%d2
	move.l 8(%sp),%d0
	cmp.l %d0,%d2
	jcs .L102
	moveq #7,%d2
	cmp.l 12(%sp),%d2
	jcs .L102
	move.l %d0,8(%sp)
	move.l (%sp)+,%d2
	jra (hd_context_depends_c.part.0)
.L102:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
	.size	hd_context_depends_c, .-hd_context_depends_c
	.align	2
	.globl	hd_context_replacing_c
	.type	hd_context_replacing_c, @function
hd_context_replacing_c:
	move.l mp_snapshot_bank,%d0
	lea (-20,%sp),%sp
	movem.l #28,(%sp)
	tst.l %d0
	jeq .L107
	add.l #-1074668000,%d0
	move.l #635712,%d3
	clr.l %d1
	divu.l %d3,%d0
	move.l mp_snapshot_parts,%d2
	mvz.w %d0,%d0
	lsl.l #2,%d0
	move.l %d0,16(%sp)
.L110:
	btst %d1,%d2
	jne .L108
.L112:
	addq.l #1,%d1
	moveq #4,%d0
	cmp.l %d1,%d0
	jne .L110
.L107:
	clr.l %d0
.L106:
	movem.l (%sp),#28
	lea (20,%sp),%sp
	rts
.L108:
	moveq #63,%d3
	cmp.l 24(%sp),%d3
	jcs .L112
.L111:
	moveq #7,%d4
	cmp.l 28(%sp),%d4
	jcs .L134
	move.l 16(%sp),%a0
	pea (%a0,%d1.l)
	move.l 32(%sp),-(%sp)
	move.l 32(%sp),-(%sp)
	move.l %d1,24(%sp)
	jsr (hd_context_depends_c.part.0)
	lea (12,%sp),%sp
	move.l 12(%sp),%d1
	addq.l #1,%d1
	tst.l %d0
	jne .L106
	moveq #4,%d3
	cmp.l %d1,%d3
	jeq .L106
	btst %d1,%d2
	jne .L111
.L133:
	addq.l #1,%d1
	moveq #4,%d0
	cmp.l %d1,%d0
	jne .L110
	jra .L107
.L134:
	addq.l #1,%d1
	moveq #4,%d0
	cmp.l %d1,%d0
	jeq .L107
	btst %d1,%d2
	jeq .L133
	jra .L111
	.size	hd_context_replacing_c, .-hd_context_replacing_c
	.align	2
	.type	sync_context, @function
sync_context:
	lea (-328,%sp),%sp
	move.l 336(%sp),%d0
	move.l %d0,%d1
	lsl.l #3,%d1
	movem.l #31996,(%sp)
	move.l 332(%sp),%d3
	move.l #16768,%d4
	move.l 344(%sp),%a2
	muls.l %d3,%d4
	add.l 340(%sp),%d1
	move.l %d1,%d2
	move.l %d1,52(%sp)
	move.l #131,%d1
	muls.l %d1,%d2
	move.l %d2,%a0
	add.l %d4,%a0
	add.l #hd_banks,%a0
	move.b 128(%a0),%d1
	mvz.b %d1,%d1
	tst.l 348(%sp)
	jne .L136
	subq.l #2,%d1
	tst.l %d1
	jeq .L138
	movem.l (%sp),#31996
	clr.l %d0
	lea (328,%sp),%sp
	rts
.L136:
	subq.l #2,%d1
	tst.l %d1
	jeq .L139
.L138:
	move.l %d3,%d1
	move.l #635712,%d5
	lsl.l #7,%d1
	muls.l %d3,%d5
	add.l %d4,%d2
	lea (69,%sp),%a5
	move.l %d2,%a0
	add.l #hd_banks,%a0
	move.l %d3,64(%sp)
	move.l %a5,%d2
	move.l %a0,%d3
	lea (328,%sp),%a6
	add.l #64,%d2
	move.l %d5,56(%sp)
	move.l %d1,60(%sp)
	move.l #36568,%d1
	muls.l %d0,%d1
	move.w 342(%sp),%d0
	move.l 60(%sp),%d6
	add.l 52(%sp),%d6
	mulu.w #2224,%d0
	add.l %d0,%d1
	add.l %d5,%d1
	move.l %d1,%d4
	add.l #1074686688,%d4
#APP
| 18 "core.c" 1
	move.w %sr,%d1
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	lea revision,%a0
	lea (197,%sp),%a1
	move.l (%a0,%d6.l*4),%d7
	move.l %a1,48(%sp)
	move.l %a1,%a0
	move.l %d3,%a3
	move.l %d3,%a1
.L141:
	move.b (%a1)+,(%a0)+
	cmp.l %a0,%a6
	jne .L141
	move.l %a5,%a4
	move.l %a5,%a1
	move.l %d4,%a0
.L142:
	move.b (%a0),(%a1)+
	lea (32,%a0),%a0
	cmp.l %a1,%d2
	jne .L142
	mvz.b 325(%sp),%d5
	subq.l #2,%d5
	tst.l %d5
	jeq .L168
.L143:
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	move.l %a2,-(%sp)
	move.l 356(%sp),-(%sp)
	move.l 356(%sp),-(%sp)
	pea 145(%sp)
	move.l %a5,-(%sp)
	pea 217(%sp)
	jsr hd_roots_sync_c
	lea (24,%sp),%sp
	tst.l %d0
	jlt .L156
.L170:
	move.l 340(%sp),-(%sp)
	move.l %a2,-(%sp)
	jsr hd_context_replacing_c
	addq.l #8,%sp
	tst.l %d0
	jeq .L145
	st %d1
	move.b %d1,327(%sp)
.L145:
#APP
| 18 "core.c" 1
	move.w %sr,%d1
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	lea revision,%a0
	cmp.l (%a0,%d6.l*4),%d7
	jeq .L169
.L147:
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
| 18 "core.c" 1
	move.w %sr,%d1
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	lea revision,%a0
	lea (197,%sp),%a1
	move.l (%a0,%d6.l*4),%d7
	move.l %a1,48(%sp)
	move.l %a1,%a0
	move.l %d3,%a3
	move.l %d3,%a1
	jra .L141
.L168:
	move.b 327(%sp),%d5
	mvz.b %d5,%d0
	move.w %d5,%a0
	moveq #63,%d5
	move.l %d0,%a1
	cmp.l %d0,%d5
	jcs .L143
	move.l %a0,%d0
	moveq #3,%d5
	and.l %d5,%d0
	move.l 340(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %a1,%d0
	lsr.l #2,%d0
	move.l %d0,-(%sp)
	move.l %d1,56(%sp)
	jsr (hd_scale_c.part.0)
	lea (12,%sp),%sp
	move.l %d0,%d5
	lsr.l #6,%d0
	lsr.l #2,%d5
	move.l 44(%sp),%d1
	move.l %d0,%a1
	moveq #15,%d0
	and.l %d0,%d5
	move.w %a1,%d0
	mulu.w #12,%d0
	add.l %d5,%d0
	move.b %d0,326(%sp)
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	move.l %a2,-(%sp)
	move.l 356(%sp),-(%sp)
	move.l 356(%sp),-(%sp)
	pea 145(%sp)
	move.l %a5,-(%sp)
	pea 217(%sp)
	jsr hd_roots_sync_c
	lea (24,%sp),%sp
	tst.l %d0
	jge .L170
.L156:
	movem.l (%sp),#31996
	moveq #-1,%d0
	lea (328,%sp),%sp
	rts
.L169:
	move.l %d4,%a1
	move.l %a5,%a0
.L146:
	mvz.b (%a0),%d7
	mvz.b (%a1),%d0
	addq.l #1,%a0
	lea (32,%a1),%a1
	cmp.l %d7,%d0
	jne .L147
	cmp.l %a0,%d2
	jne .L146
	move.w %d1,%d7
	move.l 48(%sp),%a2
	move.l 64(%sp),%d3
	move.l 56(%sp),%d6
	add.l #1074668000,%d6
	lea (133,%sp),%a5
.L151:
	mvz.b (%a4)+,%d1
	mvz.b (%a5)+,%d0
	cmp.l %d1,%d0
	jeq .L150
	move.l %d0,-(%sp)
	move.l %d4,-(%sp)
	move.l %d3,-(%sp)
	lea write_native,%a1
	jsr (%a1)
	lea (12,%sp),%sp
.L150:
	add.l #32,%d4
	cmp.l %a4,%d2
	jne .L151
.L152:
	move.b (%a2)+,(%a3)+
	cmp.l %a2,%a6
	jne .L152
	move.l %d3,-(%sp)
	jsr hd_nv_dirty_c
	move.l 64(%sp),%d0
	lea revision,%a1
	add.l 56(%sp),%d0
	addq.l #4,%sp
	lea bank_revision,%a0
	addq.l #1,(%a1,%d0.l*4)
	addq.l #1,(%a0,%d3.l*4)
	moveq #1,%d0
	move.l #635698,%a0
	move.l %d0,(%a0,%d6.l)
	cmp.l 1187521622.l,%d6
	jeq .L171
#APP
| 22 "core.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	tst.l 348(%sp)
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
.L172:
	movem.l (%sp),#31996
	lea (328,%sp),%sp
	rts
.L171:
	move.l %d0,269452696
#APP
| 22 "core.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	tst.l 348(%sp)
	sne %d0
	mvs.b %d0,%d0
	neg.l %d0
	jra .L172
.L139:
	mvz.b 130(%a0),%d1
	cmp.l %d1,%a2
	jne .L138
	move.l 352(%sp),%d5
	lsr.l #2,%d5
	move.l 352(%sp),%d1
	moveq #15,%d7
	lsr.l #6,%d1
	mvz.b 129(%a0),%d6
	and.l %d7,%d5
	mulu.w #12,%d1
	add.l %d5,%d1
	cmp.l %d6,%d1
	jne .L138
	movem.l (%sp),#31996
	moveq #1,%d0
	lea (328,%sp),%sp
	rts
	.size	sync_context, .-sync_context
	.align	2
	.globl	hd_scene_part_byte_c
	.type	hd_scene_part_byte_c, @function
hd_scene_part_byte_c:
	lea (-16,%sp),%sp
	moveq #63,%d1
	move.l %d2,-(%sp)
	move.l 24(%sp),%d0
	cmp.l %d0,%d1
	jcs .L173
	move.l 28(%sp),%d1
	add.l #-6050,%d1
	cmp.l #143,%d1
	jhi .L173
	move.l 32(%sp),%d2
	cmp.l #255,%d2
	jls .L177
.L173:
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	rts
.L177:
	moveq #3,%d1
	and.l %d0,%d1
	lsr.l #2,%d0
	move.l %d1,14(%sp)
#APP
| 18 "core.c" 1
	move.w %sr,%d2
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.w %d2,18(%sp)
	move.w 16(%sp),%d2
	move.l #635712,%d1
	muls.l %d0,%d1
	move.l 28(%sp),%a0
	add.l #585088,%a0
	move.l 32(%sp),-(%sp)
	move.l %d1,%a1
	add.l #1074668000,%a1
	mulu.w #6322,%d2
	add.l %d2,%a0
	pea (%a1,%a0.l)
	move.l %d0,-(%sp)
	move.l %d0,18(%sp)
	jsr write_native
	move.l 26(%sp),-(%sp)
	move.l 22(%sp),%d0
	move.l %d0,-(%sp)
	jsr part_dirty
	move.w 38(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	lea (16,%sp),%sp
	rts
	.size	hd_scene_part_byte_c, .-hd_scene_part_byte_c
	.align	2
	.globl	hd_bank_reset_c
	.type	hd_bank_reset_c, @function
hd_bank_reset_c:
	lea (-24,%sp),%sp
	moveq #15,%d0
	movem.l #3132,(%sp)
	move.l 28(%sp),%d5
	cmp.l %d5,%d0
	jcs .L178
	move.l %d5,%d4
	move.l #16768,%d3
	lsl.l #7,%d4
	muls.l %d5,%d3
	clr.l %d2
	lea hd_roots_reset_c,%a3
	lea revision,%a2
	add.l #hd_banks,%d3
.L180:
	move.l %d3,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	add.l #131,%d3
	move.l %d4,%d0
	add.l %d2,%d0
	clr.l (%a2,%d0.l*4)
	addq.l #1,%d2
	cmp.l #128,%d2
	jne .L180
	lea bank_revision,%a0
	addq.l #1,(%a0,%d5.l*4)
.L178:
	movem.l (%sp),#3132
	lea (24,%sp),%sp
	rts
	.size	hd_bank_reset_c, .-hd_bank_reset_c
	.align	2
	.globl	hd_reset_c
	.type	hd_reset_c, @function
hd_reset_c:
	lea (-32,%sp),%sp
	movem.l #7292,(%sp)
	move.l #hd_banks,%d6
	clr.l %d5
	lea hd_roots_reset_c,%a3
	lea revision,%a2
	lea bank_revision,%a4
.L185:
	move.l %d5,%d4
	move.l %d6,%d3
	lsl.l #7,%d4
	clr.l %d2
.L186:
	move.l %d3,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	add.l #131,%d3
	move.l %d4,%d0
	add.l %d2,%d0
	clr.l (%a2,%d0.l*4)
	addq.l #1,%d2
	cmp.l #128,%d2
	jne .L186
	addq.l #1,(%a4,%d5.l*4)
	add.l #16768,%d6
	addq.l #1,%d5
	moveq #16,%d0
	cmp.l %d5,%d0
	jne .L185
	clr.l %d0
	lea hd_target,%a1
	lea hd_busy,%a0
.L187:
	clr.b %d1
	move.b %d1,(%a1,%d0.l)
	move.b %d1,(%a0,%d0.l)
	addq.l #1,%d0
	moveq #8,%d1
	cmp.l %d0,%d1
	jne .L187
	movem.l (%sp),#7292
	lea (32,%sp),%sp
	rts
	.size	hd_reset_c, .-hd_reset_c
	.align	2
	.globl	hd_bank_loaded_c
	.type	hd_bank_loaded_c, @function
hd_bank_loaded_c:
	moveq #15,%d0
	cmp.l 4(%sp),%d0
	jcs .L193
	jra (hd_bank_loaded_c.part.0)
.L193:
	rts
	.size	hd_bank_loaded_c, .-hd_bank_loaded_c
	.align	2
	.globl	hd_ready_all_c
	.type	hd_ready_all_c, @function
hd_ready_all_c:
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	clr.l %d2
	lea (hd_bank_loaded_c.part.0),%a2
.L198:
	move.l %d2,-(%sp)
	jsr (%a2)
	addq.l #1,%d2
	addq.l #4,%sp
	moveq #16,%d0
	cmp.l %d2,%d0
	jne .L198
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	rts
	.size	hd_ready_all_c, .-hd_ready_all_c
	.align	2
	.globl	hd_sync_c
	.type	hd_sync_c, @function
hd_sync_c:
	lea (-24,%sp),%sp
	moveq #7,%d0
	movem.l #60,(%sp)
	move.l 36(%sp),%d3
	move.l 28(%sp),%d2
	cmp.l %d3,%d0
	jcs .L205
	move.l 32(%sp),%d0
	moveq #15,%d1
	or.l %d2,%d0
	cmp.l %d0,%d1
	jcs .L205
	move.l 32(%sp),%d1
	move.l #635712,%d0
	move.l #36568,%d4
	muls.l %d2,%d0
	muls.l %d4,%d1
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d0
	moveq #3,%d1
	cmp.l %d0,%d1
	jcs .L205
	moveq #3,%d4
	and.l %d0,%d4
	move.l %d2,%d5
	lsl.l #2,%d5
	move.l %d3,-(%sp)
	move.l %d4,-(%sp)
	move.l %d2,-(%sp)
	add.l %d5,%d0
	move.l %d0,28(%sp)
	jsr (hd_scale_c.part.0)
	move.l %d5,%a0
	move.l %d0,32(%sp)
	pea 5.w
	pea (%a0,%d4.l)
	move.l %d3,-(%sp)
	jsr hd_part_read_c
	lea (24,%sp),%sp
	moveq #2,%d1
	cmp.l %d0,%d1
	jcs .L210
	move.l 20(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l 24(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l 48(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr sync_context
	lea (24,%sp),%sp
.L202:
	movem.l (%sp),#60
	lea (24,%sp),%sp
	rts
.L210:
	move.l 20(%sp),-(%sp)
	clr.l %d0
	move.l %d0,-(%sp)
	move.l 24(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l 48(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr sync_context
	lea (24,%sp),%sp
	jra .L202
.L205:
	movem.l (%sp),#60
	moveq #-1,%d0
	lea (24,%sp),%sp
	rts
	.size	hd_sync_c, .-hd_sync_c
	.align	2
	.globl	hd_base_c
	.type	hd_base_c, @function
hd_base_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	moveq #15,%d0
	move.l %d2,-(%sp)
	move.l 16(%sp),%d1
	move.l 20(%sp),%a0
	cmp.l %d1,%d0
	jcs .L214
	move.l %a0,%d0
	moveq #7,%d2
	or.l 24(%sp),%d0
	cmp.l %d0,%d2
	jcs .L214
	moveq #3,%d3
	cmp.l %a0,%d3
	jcc .L220
	move.l 24(%sp),%d0
	moveq #36,%d2
	move.l #635712,%d3
	muls.l %d3,%d1
	muls.l %d2,%d0
	move.l %a0,%d2
	move.l #6322,%d3
	muls.l %d3,%d2
	move.l %d1,%a1
	add.l #1074668000,%a1
	move.l %d0,%a0
	add.l #586359,%a0
	moveq #83,%d1
	add.l %d2,%a0
	mvz.b (%a1,%a0.l),%d0
	cmp.l %d0,%d1
	jcs .L221
.L211:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L221:
	move.l (%sp)+,%d2
	moveq #35,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L220:
	pea 19.w
	pea (%a0,%d1.l*4)
	move.l 32(%sp),-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	moveq #83,%d1
	cmp.l %d0,%d1
	jcc .L211
	jra .L221
.L214:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
	.size	hd_base_c, .-hd_base_c
	.align	2
	.globl	hd_lock_c
	.type	hd_lock_c, @function
hd_lock_c:
	lea (-48,%sp),%sp
	moveq #63,%d0
	movem.l #3324,(%sp)
	move.l 64(%sp),%a2
	move.l 52(%sp),%d2
	cmp.l %a2,%d0
	jcs .L225
	move.l 60(%sp),-(%sp)
	move.l 60(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr hd_sync_c
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jne .L225
	move.l 56(%sp),%d6
	lsl.l #3,%d6
	add.l 60(%sp),%d6
#APP
| 18 "core.c" 1
	move.w %sr,%d3
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l #635712,%d5
	muls.l %d2,%d5
	move.w %d3,46(%sp)
	move.l 60(%sp),%d3
	move.l %a2,%d1
	move.l #131,%d4
	move.l #16768,%d7
	lsl.l #5,%d1
	muls.l %d6,%d4
	move.l %d5,%a1
	move.l #2224,%d5
	muls.l %d5,%d3
	muls.l %d2,%d7
	move.l #36568,%d0
	add.l #1074668000,%a1
	move.l %d4,%a3
	move.l %d3,%a0
	move.l 56(%sp),%d3
	add.l %d7,%a3
	lea (18688,%a0),%a0
	muls.l %d3,%d0
	move.l #hd_banks,%d3
	add.l %d3,%a3
	mvz.b 64(%a2,%a3.l),%d5
	add.l %d0,%a0
	add.l %d1,%a0
	add.l %a1,%a0
	mvz.b (%a0),%d1
	cmp.l %d1,%d5
	jne .L235
.L226:
	add.l %d7,%d4
	add.l %d4,%d3
	move.b (%a2,%d3.l),%d0
	move.w 46(%sp),%d1
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	mvz.b %d0,%d0
	moveq #83,%d3
	cmp.l %d0,%d3
	jcs .L225
.L222:
	movem.l (%sp),#3324
	lea (48,%sp),%sp
	rts
.L235:
	moveq #15,%d5
	cmp.l %d2,%d5
	jcs .L232
	moveq #15,%d5
	cmp.l 56(%sp),%d5
	jcs .L231
	move.l %d0,%a3
	add.l #36439,%a3
	moveq #3,%d5
	mvz.b (%a1,%a3.l),%d0
	cmp.l %d0,%d5
	jcs .L231
	and.l %d5,%d0
	moveq #7,%d5
	cmp.l 60(%sp),%d5
	jcc .L236
.L232:
	clr.l %d0
.L228:
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	move.l %a1,42(%sp)
	move.l %a0,46(%sp)
	jsr hd_encode_c
	move.l %d4,%a3
	add.l %d7,%a3
	add.l %d3,%a3
	move.b %d0,(%a3,%a2.l)
	mvz.b %d0,%d0
	move.l %d0,-(%sp)
	jsr hd_mirror_c
	move.b %d0,64(%a2,%a3.l)
	mvz.b %d0,%d0
	lea revision,%a3
	move.l %d0,-(%sp)
	move.l 54(%sp),%a0
	move.l %a0,-(%sp)
	move.l %d2,-(%sp)
	jsr write_native
	move.l %d2,-(%sp)
	jsr hd_nv_dirty_c
	lea (28,%sp),%sp
	move.l %d2,%d0
	lsl.l #7,%d0
	lea bank_revision,%a0
	move.l 34(%sp),%a1
	add.l %d6,%d0
	addq.l #1,(%a3,%d0.l*4)
	addq.l #1,(%a0,%d2.l*4)
	moveq #1,%d0
	move.l #635698,%a0
	move.l %d0,(%a1,%a0.l)
	cmp.l 1187521622.l,%a1
	jne .L226
	add.l %d7,%d4
	move.l %d0,269452696
	add.l %d4,%d3
	move.b (%a2,%d3.l),%d0
	move.w 46(%sp),%d1
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	mvz.b %d0,%d0
	moveq #83,%d3
	cmp.l %d0,%d3
	jcc .L222
	jra .L225
.L236:
	move.l 60(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d2,-(%sp)
	move.l %d1,54(%sp)
	move.l %a0,50(%sp)
	move.l %a1,46(%sp)
	jsr (hd_scale_c.part.0)
	lea (12,%sp),%sp
	move.l 34(%sp),%a1
	move.l 38(%sp),%a0
	move.l 42(%sp),%d1
	jra .L228
.L225:
	movem.l (%sp),#3324
	moveq #-1,%d0
	lea (48,%sp),%sp
	rts
.L231:
	moveq #3,%d0
	moveq #7,%d5
	cmp.l 60(%sp),%d5
	jcs .L232
	jra .L236
	.size	hd_lock_c, .-hd_lock_c
	.align	2
	.globl	hd_degree_c
	.type	hd_degree_c, @function
hd_degree_c:
	lea (-12,%sp),%sp
	moveq #63,%d0
	movem.l #28,(%sp)
	move.l 16(%sp),%d3
	move.l 20(%sp),%d2
	cmp.l 28(%sp),%d0
	jcs .L240
	move.l 24(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr hd_sync_c
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jne .L240
	move.l 28(%sp),-(%sp)
	move.l 28(%sp),-(%sp)
	move.l %d2,-(%sp)
	moveq #15,%d4
	move.l %d3,-(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	cmp.l %d3,%d4
	jcs .L237
	cmp.l %d2,%d4
	jcs .L242
	move.l #635712,%d1
	move.l #36568,%d4
	muls.l %d3,%d1
	muls.l %d4,%d2
	move.l %d1,%a0
	add.l %d2,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d1
	moveq #3,%d2
	cmp.l %d1,%d2
	jcs .L243
	moveq #-1,%d4
	cmp.l %d0,%d4
	jeq .L252
.L237:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L252:
	and.l %d2,%d1
.L244:
	moveq #7,%d4
	cmp.l 24(%sp),%d4
	jcs .L240
	pea 19.w
	move.l %d1,%a0
	pea (%a0,%d3.l*4)
	move.l 32(%sp),-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	moveq #83,%d1
	cmp.l %d0,%d1
	jcc .L237
	movem.l (%sp),#28
	moveq #35,%d0
	lea (12,%sp),%sp
	rts
.L240:
	movem.l (%sp),#28
	moveq #-1,%d0
	lea (12,%sp),%sp
	rts
.L243:
	moveq #-1,%d1
	cmp.l %d0,%d1
	jne .L237
.L245:
	moveq #3,%d1
	jra .L244
.L242:
	moveq #-1,%d2
	cmp.l %d0,%d2
	jeq .L245
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
	.size	hd_degree_c, .-hd_degree_c
	.align	2
	.globl	hd_resolve_c
	.type	hd_resolve_c, @function
hd_resolve_c:
	lea (-16,%sp),%sp
	movem.l #28,(%sp)
	move.l 28(%sp),%d4
	move.l 24(%sp),%d2
	move.l 32(%sp),-(%sp)
	move.l 24(%sp),%d3
	move.l %d4,-(%sp)
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l %d0,%d1
	moveq #15,%d0
	cmp.l %d3,%d0
	jcs .L271
	moveq #15,%d0
	cmp.l %d2,%d0
	jcs .L258
	move.l #36568,%d0
	muls.l %d0,%d2
	move.l #635712,%d0
	muls.l %d3,%d0
	move.l %d0,%a0
	add.l %d2,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d0
	moveq #3,%d2
	cmp.l %d0,%d2
	jcs .L259
	moveq #-1,%d2
	cmp.l %d1,%d2
	jeq .L253
	moveq #3,%d2
	and.l %d2,%d0
	moveq #7,%d2
	cmp.l %d4,%d2
	jcc .L272
.L255:
	clr.l %d0
.L257:
	movem.l (%sp),#28
	move.l %d0,24(%sp)
	move.l %d1,20(%sp)
	lea (16,%sp),%sp
	jra hd_decode_c
.L272:
	move.l %d4,-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,-(%sp)
	move.l %d1,24(%sp)
	jsr (hd_scale_c.part.0)
	lea (12,%sp),%sp
	movem.l (%sp),#28
	move.l 12(%sp),%d1
	move.l %d0,24(%sp)
	move.l %d1,20(%sp)
	lea (16,%sp),%sp
	jra hd_decode_c
.L259:
	moveq #-1,%d0
	cmp.l %d1,%d0
	jne .L262
.L253:
	movem.l (%sp),#28
	moveq #-1,%d0
	lea (16,%sp),%sp
	rts
.L258:
	moveq #-1,%d2
	cmp.l %d1,%d2
	jeq .L253
.L262:
	moveq #3,%d0
	moveq #7,%d2
	cmp.l %d4,%d2
	jcs .L255
	jra .L272
.L271:
	moveq #-1,%d2
	cmp.l %d1,%d2
	jeq .L253
	clr.l %d0
	jra .L257
	.size	hd_resolve_c, .-hd_resolve_c
	.align	2
	.globl	hd_ui_observe_c
	.type	hd_ui_observe_c, @function
hd_ui_observe_c:
	lea (-12,%sp),%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_ui_context_c
	move.b 269161680,%d1
	tst.l %d0
	jlt .L273
	move.l %d0,%d2
	moveq #63,%d3
	lsr.l #2,%d2
	cmp.l %d0,%d3
	jcs .L273
	mvz.b %d1,%d3
	move.l %d3,16(%sp)
	moveq #15,%d3
	cmp.l 16(%sp),%d3
	jcs .L273
	ext.w %d1
	move.l #635712,%d3
	muls.l %d2,%d3
	mulu.w #36568,%d1
	move.l %d3,%a0
	moveq #3,%d3
	add.l %d1,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d1
	cmp.l %d1,%d3
	jcs .L273
	move.l %d1,%a1
	lea (%a1,%d2.l*4),%a0
	cmp.l %d0,%a0
	jne .L273
	clr.l %d1
	lea hd_busy,%a0
.L276:
	tst.b (%a0,%d1.l)
	jeq .L280
	addq.l #1,%d1
	moveq #8,%d0
	cmp.l %d1,%d0
	jne .L276
.L273:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (12,%sp),%sp
	rts
.L280:
	move.l %d1,-(%sp)
	move.l 20(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d1,24(%sp)
	move.l %a0,20(%sp)
	jsr hd_sync_c
	lea (12,%sp),%sp
	moveq #8,%d0
	move.l 12(%sp),%d1
	addq.l #1,%d1
	move.l 8(%sp),%a0
	cmp.l %d1,%d0
	jne .L276
	jra .L273
	.size	hd_ui_observe_c, .-hd_ui_observe_c
	.align	2
	.globl	hd_part_before_c
	.type	hd_part_before_c, @function
hd_part_before_c:
	lea (-52,%sp),%sp
	movem.l #31996,(%sp)
	move.l 56(%sp),%d2
	move.l %d2,%d0
	add.l #-269110990,%d0
	cmp.l #25287,%d0
	jls .L295
.L282:
	add.l #-1074668000,%d2
	cmp.l #10171391,%d2
	jhi .L281
	move.l #635712,%d3
	remu.l %d3,%d0:%d2
	divu.l %d3,%d2
	add.l #-585088,%d0
	cmp.l #25287,%d0
	jhi .L281
	move.l %d0,%d1
	move.l #6322,%d4
	remu.l %d4,%d3:%d1
	divu.l %d4,%d1
	tst.l %d3
	jeq .L296
.L281:
	movem.l (%sp),#31996
	lea (52,%sp),%sp
	rts
.L295:
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L281
	lsr.l #2,%d0
	move.l #635712,%d1
	add.l #806142098,%d2
	muls.l %d1,%d0
	add.l %d0,%d2
	jra .L282
.L296:
	mvz.w %d2,%d2
	move.l %d1,%a0
	clr.l %d3
	lea (hd_context_depends_c.part.0),%a4
	lea (hd_scale_c.part.0),%a5
	lea (%a0,%d2.l*4),%a3
	jsr hd_ui_observe_c
	lea hd_banks+128,%a0
	move.l %a0,48(%sp)
.L284:
	move.l %d3,%d5
	clr.l %d7
	lsl.l #7,%d5
	move.l 48(%sp),%a2
	lea bank_revision,%a6
.L287:
	move.b 2(%a2),%d2
	moveq #63,%d0
	mvz.b %d2,%d6
	cmp.l %d6,%d0
	jcs .L285
	mvz.b (%a2),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L297
.L285:
	addq.l #1,%d7
	lea (131,%a2),%a2
	cmp.l #128,%d7
	jne .L287
.L299:
	move.l #16768,%d0
	addq.l #1,%d3
	add.l %d0,48(%sp)
	moveq #16,%d1
	cmp.l %d3,%d1
	jne .L284
	move.l %a3,56(%sp)
	movem.l (%sp),#31996
	lea (52,%sp),%sp
	jra hd_events_part_before_c
.L297:
	moveq #7,%d4
	and.l %d7,%d4
	move.l %a3,-(%sp)
	move.l %d4,-(%sp)
	move.l %d6,-(%sp)
	jsr (%a4)
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L285
	move.l %d4,-(%sp)
	moveq #3,%d4
	and.l %d2,%d4
	move.l %d6,%d0
	lsr.l #2,%d0
	move.l %d4,-(%sp)
	move.l %d0,-(%sp)
	jsr (%a5)
#APP
| 18 "core.c" 1
	move.w %sr,%d2
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	lea (12,%sp),%sp
	mvz.b 2(%a2),%d1
	cmp.l %d6,%d1
	jeq .L298
#APP
| 22 "core.c" 1
	move.w %d2,%sr
| 0 "" 2
#NO_APP
.L300:
	addq.l #1,%d7
	lea (131,%a2),%a2
	cmp.l #128,%d7
	jne .L287
	jra .L299
.L298:
	st %d4
	move.l %d3,-(%sp)
	move.l %d0,48(%sp)
	jsr hd_nv_dirty_c
	move.l 48(%sp),%d0
	move.l %d0,%d1
	lsr.l #2,%d1
	lsr.l #6,%d0
	move.b %d4,2(%a2)
	moveq #15,%d4
	addq.l #4,%sp
	and.l %d4,%d1
	mulu.w #12,%d0
	move.l %d5,%a1
	add.l %d7,%a1
	lea revision,%a0
	addq.l #1,(%a0,%a1.l*4)
	addq.l #1,(%a6,%d3.l*4)
	add.l %d1,%d0
	move.b %d0,1(%a2)
#APP
| 22 "core.c" 1
	move.w %d2,%sr
| 0 "" 2
#NO_APP
	jra .L300
	.size	hd_part_before_c, .-hd_part_before_c
	.align	2
	.globl	hd_checkpoint_c
	.type	hd_checkpoint_c, @function
hd_checkpoint_c:
	lea (-36,%sp),%sp
	moveq #15,%d0
	movem.l #15484,(%sp)
	move.l 40(%sp),%d5
	cmp.l %d5,%d0
	jcs .L301
	move.l %d5,%d4
	move.l #16768,%d0
	lsl.l #7,%d4
	muls.l %d5,%d0
	clr.l %d2
	lea (hd_scale_c.part.0),%a3
	lea revision,%a5
	lea bank_revision,%a4
	move.l %d0,%a2
	add.l #hd_banks+128,%a2
.L304:
#APP
| 18 "core.c" 1
	move.w %sr,%d3
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	mvz.b (%a2),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L308
.L303:
#APP
| 22 "core.c" 1
	move.w %d3,%sr
| 0 "" 2
#NO_APP
	addq.l #1,%d2
	lea (131,%a2),%a2
	cmp.l #128,%d2
	jne .L304
.L301:
	movem.l (%sp),#15484
	lea (36,%sp),%sp
	rts
.L308:
	move.b 2(%a2),%d1
	moveq #63,%d6
	mvz.b %d1,%d0
	cmp.l %d0,%d6
	jcs .L303
	moveq #7,%d6
	lsr.l #2,%d0
	and.l %d2,%d6
	move.l %d6,-(%sp)
	moveq #3,%d6
	and.l %d1,%d6
	move.l %d6,-(%sp)
	moveq #15,%d6
	move.l %d0,-(%sp)
	jsr (%a3)
	lea (12,%sp),%sp
	move.l %d4,%a0
	add.l %d2,%a0
	move.l %d0,%d1
	lsr.l #2,%d1
	lsr.l #6,%d0
	addq.l #1,(%a5,%a0.l*4)
	and.l %d6,%d1
	mulu.w #12,%d0
	addq.l #1,(%a4,%d5.l*4)
	add.l %d1,%d0
	move.b %d0,1(%a2)
#APP
| 22 "core.c" 1
	move.w %d3,%sr
| 0 "" 2
#NO_APP
	addq.l #1,%d2
	lea (131,%a2),%a2
	cmp.l #128,%d2
	jne .L304
	jra .L301
	.size	hd_checkpoint_c, .-hd_checkpoint_c
	.align	2
	.globl	hd_mode_c
	.type	hd_mode_c, @function
hd_mode_c:
	lea (-44,%sp),%sp
	movem.l #60,(%sp)
	move.l 48(%sp),%d3
	jsr hd_ui_context_c
	move.l %d0,%d2
	moveq #7,%d0
	cmp.l %d3,%d0
	jcs .L309
	moveq #2,%d1
	cmp.l 52(%sp),%d1
	jcs .L309
	tst.l %d2
	jlt .L309
	moveq #3,%d5
	moveq #63,%d0
	and.l %d2,%d5
	move.l %d2,%d4
	lsr.l #2,%d4
	move.l %d5,26(%sp)
	cmp.l %d2,%d0
	jcs .L311
	move.l %d5,%a0
	lea (%a0,%d4.l*4),%a0
	move.l %a0,38(%sp)
	pea 5.w
	move.l %a0,-(%sp)
	move.l %d3,-(%sp)
	jsr hd_part_read_c
	moveq #2,%d1
	move.l %d0,46(%sp)
	lea (12,%sp),%sp
	cmp.l %d0,%d1
	jcc .L341
	move.l %d3,-(%sp)
	move.l 30(%sp),-(%sp)
	move.l %d4,-(%sp)
	jsr (hd_scale_c.part.0)
	moveq #1,%d1
	lea hd_busy_context,%a0
	move.b %d2,(%a0,%d3.l)
	lea (67,%sp),%a1
	lea hd_target,%a0
	move.b (%a1),(%a0,%d3.l)
	lea hd_busy,%a0
	move.l %d0,42(%sp)
	move.b %d1,(%a0,%d3.l)
	move.l %d0,-(%sp)
	move.l 68(%sp),-(%sp)
	clr.l -(%sp)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_scene_mode_c
	lea (32,%sp),%sp
	tst.l 52(%sp)
	jne .L314
	move.b 269161680,%d1
	clr.l 34(%sp)
	mvz.b %d1,%d1
.L322:
	moveq #15,%d5
	cmp.l %d1,%d5
	jcs .L316
	move.w %d1,%d0
	move.l #635712,%d5
	muls.l %d4,%d5
	move.l %d5,%a0
	moveq #3,%d5
	mulu.w #36568,%d0
	add.l %d0,%a0
	add.l #1074704439,%a0
	mvz.b (%a0),%d0
	cmp.l %d0,%d5
	jcs .L316
	move.l %d0,%a1
	lea (%a1,%d4.l*4),%a0
	cmp.l %d2,%a0
	jne .L316
	move.l 30(%sp),-(%sp)
	move.l 38(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d4,-(%sp)
	jsr sync_context
	lea (24,%sp),%sp
.L316:
	move.l #131,%d1
	sub.l %a1,%a1
	muls.l %d3,%d1
	move.l #16768,%d0
	muls.l %d4,%d0
	move.l %d1,%a0
	add.l #hd_banks+130,%a0
	add.l %d0,%a0
.L329:
	mvz.b (%a0),%d1
	cmp.l %d2,%d1
	jeq .L342
	addq.l #1,%a1
	lea (1048,%a0),%a0
	moveq #16,%d0
	cmp.l %a1,%d0
	jne .L329
.L309:
	movem.l (%sp),#60
	lea (44,%sp),%sp
	rts
.L311:
	moveq #1,%d0
	lea hd_busy_context,%a0
	move.b %d2,(%a0,%d3.l)
	lea (55,%sp),%a1
	lea hd_target,%a0
	move.b (%a1),(%a0,%d3.l)
	lea hd_busy,%a0
	move.b %d0,(%a0,%d3.l)
	clr.l -(%sp)
	move.l 56(%sp),-(%sp)
	clr.l -(%sp)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_scene_mode_c
	lea (20,%sp),%sp
	tst.l 52(%sp)
	jne .L343
	move.b 269161680,%d0
	move.l #131,%d1
	sub.l %a1,%a1
	muls.l %d3,%d1
	clr.l 30(%sp)
	move.l #16768,%d0
	muls.l %d4,%d0
	move.l %d1,%a0
	add.l #hd_banks+130,%a0
	add.l %d0,%a0
	jra .L329
.L342:
	move.l 30(%sp),-(%sp)
	move.l 56(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	move.l %a1,-(%sp)
	move.l %d4,-(%sp)
	move.l %a0,46(%sp)
	move.l %a1,42(%sp)
	jsr sync_context
	lea (24,%sp),%sp
	moveq #16,%d0
	move.l 22(%sp),%a0
	move.l 18(%sp),%a1
	addq.l #1,%a1
	lea (1048,%a0),%a0
	cmp.l %a1,%d0
	jne .L329
	jra .L309
.L341:
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l %d4,-(%sp)
	jsr (hd_scale_c.part.0)
	moveq #1,%d1
	lea hd_busy_context,%a0
	move.b %d2,(%a0,%d3.l)
	lea (67,%sp),%a1
	lea hd_target,%a0
	move.b (%a1),(%a0,%d3.l)
	lea hd_busy,%a0
	move.l %d0,42(%sp)
	move.b %d1,(%a0,%d3.l)
	move.l %d0,-(%sp)
	move.l 68(%sp),-(%sp)
	move.l 54(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_scene_mode_c
	lea (32,%sp),%sp
	tst.l 34(%sp)
	jeq .L344
	tst.l 52(%sp)
	jeq .L345
	move.b 269161680,%d1
.L348:
	mvz.b %d1,%d1
	jra .L322
.L345:
#APP
| 18 "core.c" 1
	move.w %sr,%d1
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.w %d1,42(%sp)
	pea 19.w
	moveq #83,%d5
	move.l 42(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	cmp.l %d0,%d5
	jcs .L346
	move.l 30(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d0,30(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L347
.L325:
	move.w 28(%sp),%d5
	move.l %d3,%d1
	lsl.l #5,%d1
	move.l %d0,-(%sp)
	move.l #635712,%d0
	muls.l %d4,%d0
	mulu.w #6322,%d5
	move.l %d0,%a1
	add.l #1074668000,%a1
	move.l %d1,%a0
	add.l #586082,%a0
	add.l %d5,%a0
	pea (%a1,%a0.l)
	move.l %d4,-(%sp)
	jsr write_native
	move.l 38(%sp),-(%sp)
	move.l %d4,-(%sp)
	jsr part_dirty
	move.w 62(%sp),%d1
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	lea (20,%sp),%sp
.L350:
	move.b 269161680,%d1
	jra .L348
.L343:
	clr.l 30(%sp)
.L314:
	move.l %d3,%d0
	move.l #635712,%d5
	lsl.l #5,%d0
	muls.l %d4,%d5
	move.l %d5,%a1
	add.l #1074668000,%a1
	move.l %d0,%a0
	add.l #586082,%a0
	move.w 28(%sp),%d0
	mulu.w #6322,%d0
	add.l %d0,%a0
	move.b (%a1,%a0.l),%d0
	move.l 30(%sp),-(%sp)
	mvz.b %d0,%d0
	move.l %d0,-(%sp)
	jsr hd_encode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L349
	moveq #15,%d1
	cmp.l %d4,%d1
	jcs .L318
	moveq #83,%d5
	cmp.l %d0,%d5
	jge .L319
	mvz.b 269161680,%d1
	clr.l 34(%sp)
	jra .L322
.L347:
	clr.l %d0
	moveq #6,%d5
	cmp.l 22(%sp),%d5
	jge .L325
.L332:
	move.w 28(%sp),%d5
	move.l %d3,%d1
	moveq #127,%d0
	lsl.l #5,%d1
	move.l %d0,-(%sp)
	move.l #635712,%d0
	muls.l %d4,%d0
	mulu.w #6322,%d5
	move.l %d0,%a1
	add.l #1074668000,%a1
	move.l %d1,%a0
	add.l #586082,%a0
	add.l %d5,%a0
	pea (%a1,%a0.l)
	move.l %d4,-(%sp)
	jsr write_native
	move.l 38(%sp),-(%sp)
	move.l %d4,-(%sp)
	jsr part_dirty
	move.w 62(%sp),%d1
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	lea (20,%sp),%sp
	jra .L350
.L349:
	moveq #15,%d0
	cmp.l %d4,%d0
	jcs .L318
	moveq #35,%d0
.L319:
	move.l %d0,-(%sp)
	pea 19.w
	move.l 34(%sp),%a0
	pea (%a0,%d4.l*4)
	move.l %d3,-(%sp)
	jsr hd_part_write_c
	mvz.b 269161680,%d1
	clr.l 50(%sp)
	lea (16,%sp),%sp
	jra .L322
.L318:
	move.b 269161680,%d0
	move.l #131,%d1
	sub.l %a1,%a1
	muls.l %d3,%d1
	move.l #16768,%d0
	muls.l %d4,%d0
	move.l %d1,%a0
	add.l #hd_banks+130,%a0
	add.l %d0,%a0
	jra .L329
.L346:
	move.l 30(%sp),-(%sp)
	pea 35.w
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L332
	move.w 28(%sp),%d5
	move.l %d3,%d1
	lsl.l #5,%d1
	move.l %d0,-(%sp)
	move.l #635712,%d0
	muls.l %d4,%d0
	mulu.w #6322,%d5
	move.l %d0,%a1
	add.l #1074668000,%a1
	move.l %d1,%a0
	add.l #586082,%a0
	add.l %d5,%a0
	pea (%a1,%a0.l)
	move.l %d4,-(%sp)
	jsr write_native
	move.l 38(%sp),-(%sp)
	move.l %d4,-(%sp)
	jsr part_dirty
	move.w 62(%sp),%d1
#APP
| 22 "core.c" 1
	move.w %d1,%sr
| 0 "" 2
#NO_APP
	lea (20,%sp),%sp
	jra .L350
.L344:
	tst.l 52(%sp)
	jne .L314
	move.b 269161680,%d1
	jra .L348
	.size	hd_mode_c, .-hd_mode_c
	.align	2
	.globl	hd_edit_base_c
	.type	hd_edit_base_c, @function
hd_edit_base_c:
	lea (-16,%sp),%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 28(%sp),%d1
	move.l 32(%sp),%a0
	move.l 36(%sp),%d0
	move.l 40(%sp),%a1
	cmp.l %d1,%d2
	jcs .L351
	move.l %a0,%d3
	moveq #7,%d2
	or.l %d0,%d3
	cmp.l %d3,%d2
	jcs .L351
	moveq #83,%d3
	cmp.l %a1,%d3
	jcs .L351
	moveq #3,%d2
	cmp.l %a0,%d2
	jcc .L357
#APP
| 18 "core.c" 1
	move.w %sr,%d2
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.w %d2,12(%sp)
	move.l #635712,%d2
	moveq #36,%d3
	muls.l %d1,%d2
	muls.l %d3,%d0
	move.l %a0,%d3
	move.l %d2,16(%sp)
	move.l #6322,%d2
	muls.l %d2,%d3
	move.l %a1,-(%sp)
	move.l %d0,%a0
	add.l #586359,%a0
	move.l 20(%sp),%d0
	add.l #1074668000,%d0
	add.l %d3,%a0
	pea (%a0,%d0.l)
	moveq #1,%d3
	move.l %d1,-(%sp)
	move.l %d0,20(%sp)
	jsr write_native
	move.l 20(%sp),%d0
	move.l #635698,%a0
	lea (12,%sp),%sp
	move.l %d3,(%a0,%d0.l)
	cmp.l 1187521622.l,%d0
	jeq .L358
	move.w 12(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
.L351:
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (16,%sp),%sp
	rts
.L357:
	lea (%a0,%d1.l*4),%a0
	moveq #19,%d3
	move.l %a1,40(%sp)
	move.l %d3,36(%sp)
	move.l %d0,28(%sp)
	move.l %a0,32(%sp)
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	lea (16,%sp),%sp
	jra hd_part_write_c
.L358:
	move.w 12(%sp),%d0
	move.l %d3,269452696
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	jra .L351
	.size	hd_edit_base_c, .-hd_edit_base_c
	.align	2
	.globl	hd_edit_step_c
	.type	hd_edit_step_c, @function
hd_edit_step_c:
	lea (-32,%sp),%sp
	moveq #63,%d0
	movem.l #3076,(%sp)
	cmp.l 48(%sp),%d0
	jcs .L359
	move.l 52(%sp),%d1
	cmp.l #255,%d1
	jeq .L361
	moveq #83,%d2
	cmp.l %d1,%d2
	jcs .L359
.L361:
	move.l 44(%sp),-(%sp)
	move.l 44(%sp),-(%sp)
	move.l 44(%sp),-(%sp)
	jsr hd_sync_c
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L368
.L359:
	movem.l (%sp),#3076
	lea (32,%sp),%sp
	rts
.L368:
	move.l 52(%sp),-(%sp)
	jsr hd_mirror_c
	move.l %d0,22(%sp)
	move.l 44(%sp),%d0
	lsl.l #3,%d0
	add.l 48(%sp),%d0
	move.l %d0,26(%sp)
#APP
| 18 "core.c" 1
	move.w %sr,%d2
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.w %d2,30(%sp)
	move.l 40(%sp),%d0
	move.l #635712,%d1
	move.l 52(%sp),%d2
	muls.l %d1,%d0
	move.l 48(%sp),%d1
	lsl.l #5,%d2
	move.l %d0,%a1
	move.l #2224,%d0
	muls.l %d0,%d1
	move.l 44(%sp),%d0
	add.l #1074668000,%a1
	move.l %d2,32(%sp)
	move.l #36568,%d2
	muls.l %d2,%d0
	move.l 22(%sp),-(%sp)
	move.l %d1,%a0
	move.l #16768,%d2
	lea (18688,%a0),%a0
	add.l %d0,%a0
	add.l 36(%sp),%a0
	pea (%a1,%a0.l)
	move.l 48(%sp),-(%sp)
	move.l %a1,30(%sp)
	jsr write_native
	lea (71,%sp),%a2
	move.l 38(%sp),%d0
	move.l #131,%d1
	move.l 64(%sp),%a3
	muls.l %d1,%d0
	move.l 52(%sp),%d1
	muls.l %d2,%d1
	moveq #1,%d2
	move.l %d0,%a0
	add.l %d1,%a0
	add.l #hd_banks,%a0
	move.b (%a2),(%a0,%a3.l)
	lea (37,%sp),%a2
	move.b (%a2),64(%a3,%a0.l)
	lea revision,%a3
	move.l 52(%sp),-(%sp)
	jsr hd_nv_dirty_c
	move.l 56(%sp),%d0
	lea (20,%sp),%sp
	lea bank_revision,%a0
	lsl.l #7,%d0
	move.l 36(%sp),%d1
	move.l 14(%sp),%a1
	add.l 22(%sp),%d0
	addq.l #1,(%a3,%d0.l*4)
	addq.l #1,(%a0,%d1.l*4)
	move.l #635698,%a0
	move.l %d2,(%a1,%a0.l)
	cmp.l 1187521622.l,%a1
	jeq .L369
	move.w 26(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
.L370:
	movem.l (%sp),#3076
	lea (32,%sp),%sp
	rts
.L369:
	move.w 26(%sp),%d0
	move.l %d2,269452696
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	jra .L370
	.size	hd_edit_step_c, .-hd_edit_step_c
	.align	2
	.type	hd_copy_note_c.part.0, @function
hd_copy_note_c.part.0:
	lea (-40,%sp),%sp
	movem.l #3196,(%sp)
	move.l 48(%sp),%d4
	move.l #635712,%d0
	move.l 44(%sp),%d3
	move.l 52(%sp),%d5
	move.w %d4,%d6
	muls.l %d3,%d0
	move.l 56(%sp),36(%sp)
	move.l 60(%sp),28(%sp)
	move.l 64(%sp),32(%sp)
	move.l %d0,%a2
	add.l #1074668000,%a2
	moveq #3,%d0
	mulu.w #36568,%d6
	move.l %d6,%a0
	add.l #36439,%a0
	mvz.b (%a2,%a0.l),%d2
	cmp.l %d2,%d0
	jcs .L371
	and.l %d0,%d2
	mvz.w %d3,%d0
	pea 5.w
	move.l %d2,%a0
	pea (%a0,%d0.l*4)
	move.l %d5,-(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	moveq #1,%d1
	subq.l #1,%d0
	cmp.l %d0,%d1
	jcs .L373
	move.l 32(%sp),%d1
	cmp.l #255,%d1
	jeq .L377
	tst.l 28(%sp)
	jlt .L380
	move.l %d5,52(%sp)
	move.l %d4,48(%sp)
	move.l %d3,44(%sp)
	movem.l (%sp),#3196
	move.l 28(%sp),60(%sp)
	move.l 36(%sp),56(%sp)
	lea (40,%sp),%sp
	jra hd_edit_step_c
.L373:
	move.l %d5,-(%sp)
	move.l %d4,-(%sp)
	mvz.w %d4,%d4
	move.l %d3,-(%sp)
	jsr hd_sync_c
	lsl.l #3,%d4
	add.l %d5,%d4
#APP
| 18 "core.c" 1
	move.w %sr,%d2
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	mvz.w 50(%sp),%d0
	mulu.w #2224,%d5
	move.l 44(%sp),-(%sp)
	lsl.l #5,%d0
	move.l %d0,%a0
	lea (18688,%a0),%a0
	add.l %d5,%a0
	add.l %d6,%a0
	pea (%a2,%a0.l)
	move.l %d3,-(%sp)
	jsr write_native
	lea (24,%sp),%sp
	move.l #131,%d0
	move.l #16768,%d1
	muls.l %d4,%d0
	muls.l %d3,%d1
	move.l %d1,%a0
	add.l %d0,%a0
	add.l #hd_banks,%a0
	tst.b 128(%a0)
	jeq .L375
	st %d0
	move.l 36(%sp),%d1
	lea (35,%sp),%a3
	move.b (%a3),64(%a0,%d1.l)
	move.b %d0,(%a0,%d1.l)
.L375:
	move.l %d3,-(%sp)
	jsr hd_nv_dirty_c
	addq.l #4,%sp
	move.l %d3,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l %d4,%d0
	addq.l #1,(%a1,%d0.l*4)
	addq.l #1,(%a0,%d3.l*4)
	moveq #1,%d0
	move.l #635698,%a0
	move.l %d0,(%a2,%a0.l)
	cmp.l 1187521622.l,%a2
	jeq .L381
#APP
| 22 "core.c" 1
	move.w %d2,%sr
| 0 "" 2
#NO_APP
.L371:
	movem.l (%sp),#3196
	lea (40,%sp),%sp
	rts
.L380:
	move.l %d5,-(%sp)
	move.l %d2,-(%sp)
	move.l %d3,-(%sp)
	jsr (hd_scale_c.part.0)
	move.l %d0,-(%sp)
	move.l 48(%sp),-(%sp)
	jsr hd_encode_c
	move.l %d0,48(%sp)
	lea (20,%sp),%sp
	move.l %d5,52(%sp)
	move.l %d4,48(%sp)
	move.l %d3,44(%sp)
	movem.l (%sp),#3196
	move.l 28(%sp),60(%sp)
	move.l 36(%sp),56(%sp)
	lea (40,%sp),%sp
	jra hd_edit_step_c
.L381:
	move.l %d0,269452696
#APP
| 22 "core.c" 1
	move.w %d2,%sr
| 0 "" 2
#NO_APP
	jra .L371
.L377:
	move.l %d5,52(%sp)
	move.l %d4,48(%sp)
	move.l %d3,44(%sp)
	movem.l (%sp),#3196
	move.l 32(%sp),28(%sp)
	move.l 28(%sp),60(%sp)
	move.l 36(%sp),56(%sp)
	lea (40,%sp),%sp
	jra hd_edit_step_c
	.size	hd_copy_note_c.part.0, .-hd_copy_note_c.part.0
	.align	2
	.globl	hd_record_c
	.type	hd_record_c, @function
hd_record_c:
	subq.l #4,%sp
	move.l 8(%sp),%d0
	moveq #15,%d1
	or.l 12(%sp),%d0
	cmp.l %d0,%d1
	jcs .L382
	moveq #7,%d0
	cmp.l 16(%sp),%d0
	jcs .L382
	moveq #63,%d1
	cmp.l 20(%sp),%d1
	jcs .L382
	move.l 24(%sp),%d0
	moveq #127,%d1
	add.l #-128,%d0
	cmp.l %d0,%d1
	jcc .L387
	moveq #83,%d1
	cmp.l 24(%sp),%d1
	jcs .L382
	move.l 16(%sp),-(%sp)
	move.l 16(%sp),-(%sp)
	move.l 16(%sp),-(%sp)
	jsr hd_sync_c
	lea (12,%sp),%sp
	subq.l #1,%d0
	tst.l %d0
	jeq .L388
.L382:
	addq.l #4,%sp
	rts
.L388:
#APP
| 18 "core.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l 24(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l %d0,20(%sp)
	jsr (hd_record_publish_c.part.0)
	move.l 20(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	lea (20,%sp),%sp
	addq.l #4,%sp
	rts
.L387:
	moveq #127,%d0
	and.l 24(%sp),%d0
	move.l %d0,-(%sp)
	pea -1.w
	move.l 28(%sp),-(%sp)
	move.l 28(%sp),-(%sp)
	move.l 28(%sp),-(%sp)
	move.l 28(%sp),-(%sp)
	jsr (hd_copy_note_c.part.0)
	lea (24,%sp),%sp
	addq.l #4,%sp
	rts
	.size	hd_record_c, .-hd_record_c
	.align	2
	.globl	hd_record_publish_c
	.type	hd_record_publish_c, @function
hd_record_publish_c:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	move.l 16(%sp),%d1
	move.l 12(%sp),%d0
	move.l %d0,%d2
	move.l 20(%sp),%a1
	or.l %d1,%d2
	move.l 24(%sp),4(%sp)
	move.l %d2,%a0
	moveq #15,%d2
	cmp.l %a0,%d2
	jcs .L389
	moveq #7,%d2
	cmp.l %a1,%d2
	jcs .L389
	moveq #63,%d2
	cmp.l 4(%sp),%d2
	jcs .L389
	move.l 4(%sp),24(%sp)
	move.l %a1,20(%sp)
	move.l %d1,16(%sp)
	move.l %d0,12(%sp)
	move.l (%sp)+,%d2
	addq.l #4,%sp
	jra (hd_record_publish_c.part.0)
.L389:
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
	.size	hd_record_publish_c, .-hd_record_publish_c
	.align	2
	.globl	hd_copy_note_c
	.type	hd_copy_note_c, @function
hd_copy_note_c:
	lea (-12,%sp),%sp
	move.l %d2,-(%sp)
	move.l 24(%sp),%d1
	move.l 20(%sp),%d0
	move.l %d0,%d2
	move.l 28(%sp),%a1
	or.l %d1,%d2
	move.l 32(%sp),8(%sp)
	move.l 36(%sp),12(%sp)
	move.l 40(%sp),4(%sp)
	move.l %d2,%a0
	moveq #15,%d2
	cmp.l %a0,%d2
	jcs .L393
	moveq #7,%d2
	cmp.l %a1,%d2
	jcs .L393
	moveq #63,%d2
	cmp.l 8(%sp),%d2
	jcs .L393
	move.l 4(%sp),%a0
	cmp.l #255,%a0
	jeq .L395
	moveq #127,%d2
	cmp.l %a0,%d2
	jcs .L393
.L395:
	move.l 4(%sp),40(%sp)
	move.l 12(%sp),36(%sp)
	move.l 8(%sp),32(%sp)
	move.l %a1,28(%sp)
	move.l %d1,24(%sp)
	move.l %d0,20(%sp)
	move.l (%sp)+,%d2
	lea (12,%sp),%sp
	jra (hd_copy_note_c.part.0)
.L393:
	move.l (%sp)+,%d2
	lea (12,%sp),%sp
	rts
	.size	hd_copy_note_c, .-hd_copy_note_c
	.align	2
	.globl	hd_validate_c
	.type	hd_validate_c, @function
hd_validate_c:
	lea (-12,%sp),%sp
	movem.l #1036,(%sp)
	move.l 16(%sp),%d2
	move.l %d2,%d3
	lea hd_roots_valid_c,%a2
	add.l #16768,%d3
.L403:
	move.l %d2,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	add.l #131,%d2
	tst.l %d0
	jeq .L401
	cmp.l %d2,%d3
	jne .L403
	moveq #1,%d0
.L401:
	movem.l (%sp),#1036
	lea (12,%sp),%sp
	rts
	.size	hd_validate_c, .-hd_validate_c
	.align	2
	.globl	hd_forget_c
	.type	hd_forget_c, @function
hd_forget_c:
	lea (-48,%sp),%sp
	move.l 52(%sp),%d1
	move.l 56(%sp),%d0
	movem.l #1036,(%sp)
	moveq #15,%d2
	or.l %d1,%d0
	cmp.l %d0,%d2
	jcs .L410
	moveq #7,%d3
	cmp.l 60(%sp),%d3
	jcs .L410
	moveq #63,%d0
	cmp.l 64(%sp),%d0
	jcc .L418
.L410:
	movem.l (%sp),#1036
	lea (48,%sp),%sp
	rts
.L418:
	move.l 56(%sp),%d3
	move.l #36568,%d0
	move.l #635712,%d2
	muls.l %d1,%d2
	muls.l %d0,%d3
	move.l 56(%sp),%d0
	lsl.l #3,%d0
	move.l %d2,%a0
	add.l #1074668000,%a0
	move.l %a0,40(%sp)
	moveq #3,%d2
	move.l 40(%sp),%a1
	move.l %d3,%a0
	add.l #36439,%a0
	move.l %d3,44(%sp)
	add.l 60(%sp),%d0
	move.l %d0,26(%sp)
	mvz.b (%a1,%a0.l),%d0
	cmp.l %d0,%d2
	jcs .L412
	and.l %d2,%d0
	pea 5.w
	moveq #1,%d2
	move.l %d0,%a0
	pea (%a0,%d1.l*4)
	move.l 68(%sp),-(%sp)
	move.l %d1,26(%sp)
	jsr hd_part_read_c
	lea (12,%sp),%sp
	subq.l #1,%d0
	move.l 14(%sp),%d1
	cmp.l %d0,%d2
	jcs .L412
#APP
| 18 "core.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l 26(%sp),%d3
	move.l #131,%d2
	move.w %d0,38(%sp)
	lea hd_banks,%a0
	muls.l %d2,%d3
	move.l %d3,%a1
	move.l #16768,%d3
	muls.l %d1,%d3
	move.l %d3,%d0
	add.l %a1,%d0
	add.l #hd_banks+128,%d0
	move.l %d0,%a2
	mvz.b (%a2),%d0
	move.l %d3,34(%sp)
	subq.l #2,%d0
	tst.l %d0
	jeq .L419
	move.l 34(%sp),%d0
	add.l %a1,%d0
	add.l %d0,%a0
	st %d0
	move.l 64(%sp),%a1
	move.b %d0,64(%a1,%a0.l)
	move.b %d0,(%a0,%a1.l)
	move.l %d1,-(%sp)
	move.l %d1,18(%sp)
	jsr hd_nv_dirty_c
	move.l 18(%sp),%d1
	move.l %d1,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l 30(%sp),%d0
	addq.l #1,(%a1,%d0.l*4)
	move.w 42(%sp),%d0
	addq.l #1,(%a0,%d1.l*4)
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	addq.l #4,%sp
.L420:
	movem.l (%sp),#1036
	lea (48,%sp),%sp
	rts
.L412:
#APP
| 18 "core.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l 26(%sp),%d3
	move.l #16768,%d2
	move.w %d0,38(%sp)
	muls.l %d1,%d2
	move.l #131,%d0
	muls.l %d0,%d3
	lea hd_banks,%a0
	move.l %d2,34(%sp)
	move.l 34(%sp),%d0
	move.l %d3,%a1
	add.l %a1,%d0
	add.l %d0,%a0
	st %d0
	move.l 64(%sp),%a1
	move.b %d0,64(%a1,%a0.l)
	move.b %d0,(%a0,%a1.l)
	move.l %d1,-(%sp)
	move.l %d1,18(%sp)
	jsr hd_nv_dirty_c
	move.l 18(%sp),%d1
	move.l %d1,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l 30(%sp),%d0
	addq.l #1,(%a1,%d0.l*4)
	addq.l #1,(%a0,%d1.l*4)
	move.w 42(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	addq.l #4,%sp
	jra .L420
.L419:
	move.l 64(%sp),%d0
	move.l #2224,%d2
	move.l 60(%sp),%d3
	pea 255.w
	lsl.l #5,%d0
	muls.l %d2,%d3
	move.l 44(%sp),%a2
	add.l #18688,%d0
	add.l %d3,%d0
	add.l 48(%sp),%d0
	pea (%a2,%d0.l)
	move.l %d1,-(%sp)
	move.l %d1,26(%sp)
	move.l %a0,34(%sp)
	move.l %a1,30(%sp)
	jsr write_native
	lea (12,%sp),%sp
	move.l 18(%sp),%a1
	move.l 34(%sp),%d0
	add.l %a1,%d0
	move.l 22(%sp),%a0
	add.l %d0,%a0
	st %d0
	move.l 64(%sp),%a1
	move.l 14(%sp),%d1
	move.b %d0,64(%a1,%a0.l)
	move.b %d0,(%a0,%a1.l)
	move.l %d1,-(%sp)
	move.l %d1,18(%sp)
	jsr hd_nv_dirty_c
	move.l 18(%sp),%d1
	move.l %d1,%d0
	lsl.l #7,%d0
	lea revision,%a1
	lea bank_revision,%a0
	add.l 30(%sp),%d0
	addq.l #1,(%a1,%d0.l*4)
	addq.l #1,(%a0,%d1.l*4)
	move.w 42(%sp),%d0
#APP
| 22 "core.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	addq.l #4,%sp
	jra .L420
	.size	hd_forget_c, .-hd_forget_c
	.section	.rodata
	.align	2
	.type	modes.0, @object
	.size	modes.0, 20
modes.0:
	.long	1
	.long	2
	.long	3
	.long	4
	.long	6
	.local	bank_revision
	.comm	bank_revision,64,2
	.local	revision
	.comm	revision,8192,2
	.globl	hd_busy_context
	.section	.bss
	.type	hd_busy_context, @object
	.size	hd_busy_context, 8
hd_busy_context:
	.zero	8
	.globl	hd_target
	.type	hd_target, @object
	.size	hd_target, 8
hd_target:
	.zero	8
	.globl	hd_busy
	.type	hd_busy, @object
	.size	hd_busy, 8
hd_busy:
	.zero	8
	.globl	hd_banks
	.type	hd_banks, @object
	.size	hd_banks, 268288
hd_banks:
	.zero	268288
