| Generated by generate.py; edit operations.c / core.h.
#NO_APP
	.file	"operations.c"
	.text
	.align	2
	.type	capture, @function
capture:
	lea (-16,%sp),%sp
	move.l %a2,-(%sp)
	move.l %d2,-(%sp)
	move.l 32(%sp),-(%sp)
	move.l 32(%sp),-(%sp)
	move.l %a0,%a2
	jsr hd_pattern_context_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L6
	move.l 36(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l %d0,20(%sp)
	move.l #2224,%d2
	jsr hd_sync_c
	move.l 48(%sp),%d0
	mvz.w 54(%sp),%d1
	muls.l %d2,%d0
	moveq #3,%d2
	lsl.l #5,%d1
	move.l %d0,28(%sp)
	move.l 20(%sp),%d0
	and.l %d2,%d0
	move.l #36568,%d2
	move.l %d1,%a1
	add.l #1074686688,%a1
	add.l 28(%sp),%a1
	move.l %d0,32(%sp)
	move.l 44(%sp),%d0
	muls.l %d2,%d0
	move.l #635712,%d2
	move.l %d0,%a0
	add.l %a0,%a1
	move.l 40(%sp),%d0
	muls.l %d2,%d0
	add.l %d0,%a1
	move.b (%a1),28(%sp)
	move.l 48(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l 48(%sp),-(%sp)
	jsr hd_part_type_c
	lea (24,%sp),%sp
	tst.l %d0
	jne .L14
	st %d1
.L2:
	move.b %d1,(%a2)
	move.b 16(%sp),1(%a2)
	move.l %a2,%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
.L6:
	st %d2
	st %d1
	move.l %a2,%d0
	move.b %d2,16(%sp)
	move.b %d1,(%a2)
	move.b 16(%sp),1(%a2)
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
.L14:
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	move.l 40(%sp),-(%sp)
	jsr hd_lock_c
	move.l %d0,28(%sp)
	move.b %d0,%d1
	mvz.b 32(%sp),%d0
	lea (16,%sp),%sp
	cmp.l #255,%d0
	jeq .L2
	mvz.b 15(%sp),%d0
	moveq #83,%d2
	cmp.l %d0,%d2
	jcs .L2
	move.l 36(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	move.l 36(%sp),-(%sp)
	move.l %d1,20(%sp)
	jsr hd_scale_c
	move.l 24(%sp),%d2
	mvz.b %d2,%d2
	move.l %d2,24(%sp)
	move.l %d0,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_decode_c
	lea (20,%sp),%sp
	move.l 8(%sp),%d1
	tst.l %d0
	jlt .L5
	move.b %d0,16(%sp)
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b 16(%sp),1(%a2)
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
.L5:
	moveq #6,%d0
	cmp.l 12(%sp),%d0
	jlt .L8
	clr.b %d2
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b %d2,16(%sp)
	move.b 16(%sp),1(%a2)
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
.L8:
	moveq #127,%d2
	move.b %d1,(%a2)
	move.l %a2,%d0
	move.b %d2,16(%sp)
	move.b 16(%sp),1(%a2)
	move.l (%sp)+,%d2
	move.l (%sp)+,%a2
	lea (16,%sp),%sp
	rts
	.size	capture, .-capture
	.align	2
	.type	locate, @function
locate:
	lea (-20,%sp),%sp
	move.l 24(%sp),%d1
	movem.l #28,(%sp)
	cmp.l #1175224610,%d1
	jeq .L16
	cmp.l #1175187992,%d1
	jeq .L16
	move.l 1187521622,%d0
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jhi .L19
	move.l %d0,%d2
	move.l #635712,%d3
	remu.l %d3,%d4:%d2
	move.l %d1,%a1
	add.l #-268525902,%a1
	sub.l %d4,%d0
	add.l #1074668000,%d0
	cmp.l #610375,%a1
	jls .L20
	add.l #-610376,%a1
	cmp.l #25287,%a1
	jhi .L19
	add.l #-1343193900,%d1
	add.l %d0,%d1
.L22:
	move.l #635712,%d0
	remu.l %d0,%d2:%d1
	divu.l %d0,%d1
	move.l #36568,%d3
	move.l %d2,%a1
	remu.l %d3,%d0:%d2
	divu.l %d3,%d2
	move.l %d2,16(%sp)
	cmp.l #585087,%a1
	jhi .L28
	cmp.l 28(%sp),%d3
	jeq .L34
	move.l 28(%sp),%d3
	cmp.l #2224,%d3
	jne .L28
	add.l #-18640,%d0
	cmp.l #17791,%d0
	jhi .L28
	move.l %d0,%d4
	move.l #2224,%d2
	remu.l %d2,%d3:%d4
	divu.l %d2,%d4
	move.l %d3,%d0
	tst.l %d3
	jne .L28
	move.l %d4,12(%sp)
	movem.l (%sp),#28
	move.w #3,%a1
	move.l %d0,16(%a0)
	move.l %a0,%d0
	move.l %d1,4(%a0)
	move.l %a1,(%a0)
	move.l 16(%sp),8(%a0)
	move.l 12(%sp),12(%a0)
	lea (20,%sp),%sp
	rts
.L19:
	add.l #-1074668000,%d1
	cmp.l #10171391,%d1
	jls .L22
	movem.l (%sp),#28
	clr.l %d0
	sub.l %a1,%a1
	clr.l %d1
	clr.l 16(%sp)
	clr.l 12(%sp)
	move.l %d0,16(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l %d1,4(%a0)
	move.l 16(%sp),8(%a0)
	move.l 12(%sp),12(%a0)
	lea (20,%sp),%sp
	rts
.L16:
	cmp.l #1175187992,%d1
	seq %d0
	movem.l (%sp),#28
	move.w #1,%a1
	clr.l %d1
	clr.l 16(%sp)
	clr.l 12(%sp)
	move.l %a1,(%a0)
	move.l %d1,4(%a0)
	mvs.b %d0,%d0
	move.l 16(%sp),8(%a0)
	move.l 12(%sp),12(%a0)
	neg.l %d0
	move.l %d0,16(%a0)
	move.l %a0,%d0
	lea (20,%sp),%sp
	rts
.L28:
	movem.l (%sp),#28
	clr.l %d0
	sub.l %a1,%a1
	clr.l 12(%sp)
	move.l %d0,16(%a0)
	move.l %a0,%d0
	move.l %a1,(%a0)
	move.l %d1,4(%a0)
	move.l 16(%sp),8(%a0)
	move.l 12(%sp),12(%a0)
	lea (20,%sp),%sp
	rts
.L20:
	add.l #-1343193902,%d1
	add.l %d0,%d1
	jra .L22
.L34:
	tst.l %d0
	seq %d0
	clr.l 12(%sp)
	move.l %d1,4(%a0)
	move.l 16(%sp),8(%a0)
	move.l 12(%sp),12(%a0)
	mvs.b %d0,%d2
	clr.l %d0
	move.l %d0,16(%a0)
	move.l %a0,%d0
	neg.l %d2
	add.l %d2,%d2
	move.l %d2,%a1
	movem.l (%sp),#28
	move.l %a1,(%a0)
	lea (20,%sp),%sp
	rts
	.size	locate, .-locate
	.align	2
	.globl	hd_copy_before_c
	.type	hd_copy_before_c, @function
hd_copy_before_c:
	lea (-60,%sp),%sp
	move.l 64(%sp),%d0
	movem.l #19484,(%sp)
	move.l 72(%sp),%d2
	clr.l transfer+1028
	cmp.l #1175224610,%d0
	jeq .L36
	cmp.l #1175187992,%d0
	jeq .L36
	cmp.l #36568,%d2
	jeq .L38
	cmp.l #2224,%d2
	jne .L35
.L38:
	move.l %d2,-(%sp)
	lea destination,%a6
	move.l %d0,-(%sp)
	move.l %a6,%a0
	lea locate,%a2
	jsr (%a2)
	move.l %d2,-(%sp)
	move.l 80(%sp),-(%sp)
	lea (56,%sp),%a0
	jsr (%a2)
	move.l 56(%sp),%d3
	move.l (%a6),%d0
	lea (16,%sp),%sp
	tst.l %d3
	jeq .L40
	tst.l %d0
	jeq .L35
	moveq #1,%d4
	cmp.l %d3,%d4
	jeq .L72
	moveq #2,%d4
	cmp.l %d3,%d4
	jeq .L73
	moveq #64,%d1
	sub.l %a6,%a6
	move.l %d1,26(%sp)
	move.l 48(%sp),34(%sp)
	move.l 44(%sp),30(%sp)
	lea transfer,%a3
	lea capture,%a2
.L47:
	moveq #2,%d1
	cmp.l %d3,%d1
	jeq .L74
	move.l 52(%sp),%d0
.L46:
	move.l %a6,%d4
	moveq #63,%d1
	and.l %d1,%d4
	move.l %d4,-(%sp)
	lea (42,%sp),%a0
	move.l %d0,-(%sp)
	move.l 42(%sp),-(%sp)
	move.l 42(%sp),-(%sp)
	jsr (%a2)
	lea (54,%sp),%a0
	move.w (%a0),(%a3,%a6.l*2)
	addq.l #1,%a6
	lea (16,%sp),%sp
	cmp.l 26(%sp),%a6
	jne .L47
	moveq #1,%d0
	move.l %d0,transfer+1028
	move.l %d2,transfer+1024
.L35:
	movem.l (%sp),#19484
	lea (60,%sp),%sp
	rts
.L36:
	cmp.l #36568,%d2
	jeq .L38
	cmp.l #2224,%d2
	jeq .L38
	cmp.l #1175187992,%d0
	seq %d0
	move.l #-1032,%d1
	movem.l (%sp),#19484
	mvs.b %d0,%d0
	muls.l %d1,%d0
	move.l %d0,%a0
	add.l #clips+1028,%a0
	clr.l (%a0)
	lea (60,%sp),%sp
	rts
.L40:
	subq.l #1,%d0
	tst.l %d0
	jne .L35
	move.l destination+16,%d0
	move.l #1032,%d1
	movem.l (%sp),#19484
	muls.l %d1,%d0
	move.l %d0,%a0
	add.l #clips+1028,%a0
	clr.l (%a0)
	lea (60,%sp),%sp
	rts
.L73:
	move.l #512,%d0
	sub.l %a6,%a6
	move.l %d0,26(%sp)
	move.l 48(%sp),34(%sp)
	move.l 44(%sp),30(%sp)
	lea transfer,%a3
	lea capture,%a2
	jra .L47
.L74:
	move.l %a6,%d0
	lsr.l #6,%d0
	jra .L46
.L72:
	move.l 56(%sp),%d0
	move.l #1032,%d1
	muls.l %d1,%d0
	move.l %d0,%a1
	add.l #clips,%a1
	move.l 1028(%a1),%d0
	tst.l %d0
	jeq .L35
	cmp.l 1024(%a1),%d2
	jne .L35
	lea transfer,%a0
.L43:
	move.w (%a1)+,(%a0)+
	cmp.l #transfer+1024,%a0
	jne .L43
	move.l %d2,transfer+1024
	movem.l (%sp),#19484
	move.l %d0,transfer+1028
	lea (60,%sp),%sp
	rts
	.size	hd_copy_before_c, .-hd_copy_before_c
	.align	2
	.globl	hd_copy_after_c
	.type	hd_copy_after_c, @function
hd_copy_after_c:
	move.l transfer+1028,%d1
	lea (-28,%sp),%sp
	movem.l #7228,(%sp)
	tst.l %d1
	jeq .L76
	lea destination,%a4
	moveq #1,%d2
	move.l (%a4),%d0
	cmp.l %d0,%d2
	jeq .L94
	moveq #2,%d1
	cmp.l %d0,%d1
	jeq .L95
	moveq #64,%d4
	clr.l %d2
	lea transfer,%a2
	lea hd_copy_note_c,%a3
.L85:
	subq.l #2,%d0
	tst.l %d0
	jeq .L96
.L81:
	move.l destination+12,%a0
.L82:
	mvz.b (%a2),%d3
	move.b 1(%a2),%d0
	moveq #-1,%d1
	moveq #83,%d5
	cmp.l %d3,%d5
	jcs .L83
	move.l %d3,%d1
.L83:
	mvz.b %d0,%d0
	addq.l #2,%a2
	move.l %d0,-(%sp)
	moveq #63,%d0
	and.l %d2,%d0
	move.l %d1,-(%sp)
	addq.l #1,%d2
	move.l %d0,-(%sp)
	move.l %a0,-(%sp)
	move.l destination+8,-(%sp)
	move.l destination+4,-(%sp)
	jsr (%a3)
	lea (24,%sp),%sp
	cmp.l %d4,%d2
	jeq .L84
	move.l (%a4),%d0
	subq.l #2,%d0
	tst.l %d0
	jne .L81
.L96:
	move.l %d2,%d0
	lsr.l #6,%d0
	move.l %d0,%a0
	jra .L82
.L84:
	movem.l (%sp),#7228
	move.l destination+4,%d0
	lea (28,%sp),%sp
	rts
.L95:
	move.l #512,%d4
	clr.l %d2
	lea transfer,%a2
	lea hd_copy_note_c,%a3
	jra .L85
.L94:
	move.l destination+16,%d0
	move.l #1032,%d5
	lea transfer,%a0
	muls.l %d5,%d0
	move.l %d0,%a1
	add.l #clips,%a1
.L78:
	move.w (%a0)+,(%a1)+
	cmp.l #transfer+1024,%a0
	jne .L78
	move.l %d0,%a0
	add.l #clips,%a0
	lea transfer+1024,%a1
	move.l (%a1),1024(%a0)
	move.l %d1,1028(%a0)
.L76:
	movem.l (%sp),#7228
	moveq #-1,%d0
	lea (28,%sp),%sp
	rts
	.size	hd_copy_after_c, .-hd_copy_after_c
	.align	2
	.globl	hd_operations_reset_c
	.type	hd_operations_reset_c, @function
hd_operations_reset_c:
	clr.l transfer+1028
	clr.l clips+2060
	clr.l clips+1028
	rts
	.size	hd_operations_reset_c, .-hd_operations_reset_c
	.align	2
	.globl	hd_step_copy_c
	.type	hd_step_copy_c, @function
hd_step_copy_c:
	lea (-48,%sp),%sp
	movem.l #16396,(%sp)
	clr.l -(%sp)
	lea (32,%sp),%a0
	move.l 56(%sp),-(%sp)
	jsr locate
	addq.l #8,%sp
	moveq #1,%d0
	cmp.l 28(%sp),%d0
	jne .L99
	moveq #15,%d1
	cmp.l 56(%sp),%d1
	jcs .L99
	moveq #7,%d2
	cmp.l 60(%sp),%d2
	jcs .L99
	moveq #3,%d3
	cmp.l 64(%sp),%d3
	jcs .L99
	move.l 1187521622,%d0
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jhi .L99
	move.l %d0,%d1
	move.l #635712,%d2
	divu.l %d2,%d1
	move.l 64(%sp),%d0
	sub.l %a6,%a6
	lsl.l #4,%d0
	move.l %d1,22(%sp)
	move.l #1032,%d1
	move.l %d0,14(%sp)
	move.l 44(%sp),%d0
	muls.l %d1,%d0
	move.l %d0,%a1
	moveq #1,%d0
	add.l #clips,%a1
	move.l %a1,18(%sp)
	move.l %d0,1028(%a1)
	clr.l 1024(%a1)
.L102:
	move.l 68(%sp),%d1
	move.l %a6,%d2
	btst %d2,%d1
	jne .L109
	addq.l #1,%a6
	moveq #16,%d0
	cmp.l %a6,%d0
	jne .L102
.L99:
	movem.l (%sp),#16396
	lea (48,%sp),%sp
	rts
.L109:
	move.l 14(%sp),%a1
	pea (%a1,%a6.l)
	move.l 64(%sp),-(%sp)
	move.l 64(%sp),-(%sp)
	move.l 34(%sp),-(%sp)
	lea (42,%sp),%a0
	jsr capture
	move.l 34(%sp),%a0
	lea (42,%sp),%a1
	moveq #16,%d0
	lea (16,%sp),%sp
	move.w (%a1),(%a0,%a6.l*2)
	addq.l #1,%a6
	cmp.l %a6,%d0
	jne .L102
	jra .L99
	.size	hd_step_copy_c, .-hd_step_copy_c
	.align	2
	.globl	hd_step_paste_c
	.type	hd_step_paste_c, @function
hd_step_paste_c:
	lea (-36,%sp),%sp
	movem.l #16412,(%sp)
	clr.l -(%sp)
	lea (20,%sp),%a0
	move.l 44(%sp),-(%sp)
	jsr locate
	addq.l #8,%sp
	moveq #1,%d0
	cmp.l 16(%sp),%d0
	jne .L113
	move.l 44(%sp),%d0
	moveq #15,%d1
	or.l 48(%sp),%d0
	cmp.l %d0,%d1
	jcs .L113
	moveq #7,%d2
	cmp.l 52(%sp),%d2
	jcs .L113
	moveq #63,%d3
	cmp.l 56(%sp),%d3
	jcs .L113
	move.l 32(%sp),%d1
	move.l #1032,%d0
	lea clips,%a1
	muls.l %d1,%d0
	lea (%a1,%d0.l),%a0
	tst.l 1028(%a0)
	jeq .L113
	tst.l 1024(%a0)
	jne .L113
	move.l 1187521622,%d0
	add.l #-1074668000,%d0
	cmp.l #10171391,%d0
	jhi .L113
	move.l %d0,%d4
	move.l #635712,%d2
	divu.l %d2,%d4
	move.l 44(%sp),%d0
	moveq #83,%d2
	move.l %d4,%a6
	move.l #516,%d4
	muls.l %d4,%d1
	add.l %d1,%d0
	mvz.b (%a1,%d0.l*2),%d1
	mvz.b 1(%a1,%d0.l*2),%d0
	cmp.l %d1,%d2
	jcs .L118
	move.l %d0,-(%sp)
	move.l %d1,-(%sp)
	move.l 64(%sp),-(%sp)
	move.l 64(%sp),-(%sp)
	move.l 64(%sp),-(%sp)
	move.l %a6,-(%sp)
	jsr hd_copy_note_c
	lea (24,%sp),%sp
	move.l %a6,%d0
.L110:
	movem.l (%sp),#16412
	lea (36,%sp),%sp
	rts
.L118:
	move.l %d0,-(%sp)
	moveq #-1,%d1
	move.l %d1,-(%sp)
	move.l 64(%sp),-(%sp)
	move.l 64(%sp),-(%sp)
	move.l 64(%sp),-(%sp)
	move.l %a6,-(%sp)
	jsr hd_copy_note_c
	lea (24,%sp),%sp
	move.l %a6,%d0
	jra .L110
.L113:
	movem.l (%sp),#16412
	moveq #-1,%d0
	lea (36,%sp),%sp
	rts
	.size	hd_step_paste_c, .-hd_step_paste_c
	.local	destination
	.comm	destination,20,2
	.local	transfer
	.comm	transfer,1032,2
	.local	clips
	.comm	clips,2064,2
