| Generated by generate.py; edit packed.c / packed.h.
#NO_APP
	.file	"packed.c"
	.text
	.align	2
	.type	decode, @function
decode:
	lea (-52,%sp),%sp
	movem.l #31996,(%sp)
	move.l 56(%sp),%a0
	move.l 56(%sp),%a4
	move.l 60(%sp),%d7
	move.l 64(%sp),%a2
	lea (16896,%a0),%a0
	lea (128,%a4),%a4
	move.l %a0,48(%sp)
	lea hd_mirror_c,%a3
.L16:
	mvz.b (%a2),%d0
	cmp.l #251,%d0
	jhi .L7
	move.l %d0,%d1
	moveq #84,%d2
	remu.l %d2,%d3:%d1
	divu.l %d2,%d1
	addq.l #1,%a2
	move.l %d1,%a6
	tst.l 56(%sp)
	jeq .L17
	st %d5
	move.b %d1,(%a4)
	move.l %a4,%d4
	add.l #-128,%d4
	move.l %d4,%a0
	move.l %d4,%a5
	move.b %d3,1(%a4)
	lea (64,%a0),%a0
	clr.l %d3
	move.l %a0,44(%sp)
	clr.l %d2
	move.b %d5,2(%a4)
.L5:
	moveq #9,%d0
	cmp.l %d3,%d0
	jcs .L15
	lsl.l #8,%d2
	mvz.b (%a2),%d0
	move.l %d3,%d1
	addq.l #8,%d1
	or.l %d0,%d2
	moveq #9,%d0
	cmp.l %d1,%d0
	jcs .L6
	lsl.l #8,%d2
	mvz.b 1(%a2),%d0
	or.l %d0,%d2
.L6:
	moveq #9,%d0
	moveq #-8,%d5
	sub.l %d3,%d0
	move.l %d0,%d3
	lsr.l #3,%d3
	and.l %d5,%d0
	lea 1(%a2,%d3.l),%a2
	move.l %d0,%d3
	add.l %d1,%d3
.L15:
	add.l #-10,%d3
	move.l %d2,%d6
	lsr.l %d3,%d6
	and.l #1023,%d6
	cmp.l #764,%d6
	jhi .L7
	move.l %d6,%d0
	moveq #9,%d5
	divu.l %d5,%d0
	moveq #2,%d1
	cmp.l %a6,%d1
	jeq .L8
	moveq #84,%d5
	cmp.l %d0,%d5
	jne .L7
	move.l #255,%d0
.L9:
	tst.l %d4
	jeq .L10
	move.b %d0,(%a5)
	move.l %d0,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	move.b %d0,64(%a5)
.L10:
	tst.l %d7
	jeq .L11
	moveq #9,%d5
	remu.l %d5,%d0:%d6
	moveq #8,%d6
	cmp.l %d0,%d6
	jeq .L29
	move.l %d7,%a0
	move.b %d0,(%a0)+
	move.l %a0,%d7
.L11:
	addq.l #1,%a5
	cmp.l 44(%sp),%a5
	jne .L5
	lea (131,%a4),%a4
	cmp.l 48(%sp),%a4
	jne .L16
	movem.l (%sp),#31996
	moveq #1,%d0
	lea (52,%sp),%sp
	rts
.L29:
	move.l %d7,%a0
	move.l #255,%d0
	move.b %d0,(%a0)+
	move.l %a0,%d7
	jra .L11
.L7:
	movem.l (%sp),#31996
	clr.l %d0
	lea (52,%sp),%sp
	rts
.L8:
	moveq #84,%d1
	cmp.l %d0,%d1
	jne .L9
	move.l #255,%d0
	jra .L9
.L17:
	clr.l %d4
	move.l %d4,%a0
	move.l %d4,%a5
	lea (64,%a0),%a0
	clr.l %d3
	move.l %a0,44(%sp)
	clr.l %d2
	jra .L5
	.size	decode, .-decode
	.align	2
	.globl	hd_pack_c
	.type	hd_pack_c, @function
hd_pack_c:
	lea (-56,%sp),%sp
	movem.l #31996,(%sp)
	move.l 60(%sp),%d1
	move.l %d1,%a0
	move.l 64(%sp),%a4
	move.l %d1,%a6
	move.l 68(%sp),%a2
	lea (16896,%a0),%a0
	move.l %d1,48(%sp)
	lea (128,%a6),%a6
	move.l %a0,52(%sp)
	lea hd_mirror_c,%a5
.L64:
	move.l 48(%sp),-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L30
	move.b (%a6),%d0
	move.b 1(%a6),%d1
	lea (81,%a2),%a0
	move.l 48(%sp),%a3
	move.l %a0,44(%sp)
	muls.w #84,%d0
	add.l %d1,%d0
	move.b %d0,(%a2)+
.L63:
	mvz.b (%a4),%d2
	mvz.b (%a3),%d3
	moveq #7,%d0
	cmp.l %d2,%d0
	jcs .L32
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L33
	cmp.l #255,%d3
	jeq .L115
	mulu.w #9,%d3
	mvz.b 1(%a3),%d4
	moveq #7,%d1
	add.l %d3,%d2
	mvz.b 1(%a4),%d3
	cmp.l %d3,%d1
	jcc .L70
.L69:
	cmp.l #255,%d3
	jne .L75
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L43
	cmp.l %d4,%d3
	jeq .L74
	mulu.w #9,%d4
	mvz.b 2(%a3),%d6
	moveq #7,%d0
	move.l %d4,%d3
	addq.l #8,%d3
	mvz.b 2(%a4),%d4
	cmp.l %d4,%d0
	jcc .L68
.L67:
	cmp.l #255,%d4
	jne .L79
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L50
	cmp.l %d6,%d4
	jeq .L78
	mulu.w #9,%d6
	mvz.b 3(%a4),%d7
	moveq #7,%d1
	move.l %d6,%d4
	addq.l #8,%d4
	mvz.b 3(%a3),%d6
	cmp.l %d7,%d1
	jcc .L66
.L65:
	cmp.l #255,%d7
	jne .L60
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L57
	cmp.l %d6,%d7
	jeq .L81
	mulu.w #9,%d6
	move.l %d6,%d0
	addq.l #8,%d0
	move.l %d0,%d6
.L58:
	move.l %d3,%d1
	or.l %d2,%d1
	or.l %d4,%d1
	or.l %d6,%d1
	jmi .L60
.L119:
	move.l %d2,%d7
	move.l %d3,%d6
	lsl.l #6,%d7
	move.l %d4,%d1
	move.l %d3,%d5
	lsl.l #4,%d6
	lsl.l #2,%d1
	lsr.l #4,%d5
	lsr.l #6,%d4
	move.l %d0,%d3
	lsr.l #8,%d3
	lsr.l #2,%d2
	addq.l #5,%a2
	addq.l #4,%a4
	or.l %d5,%d7
	move.b %d2,-5(%a2)
	or.l %d6,%d4
	or.l %d3,%d1
	addq.l #4,%a3
	move.b %d7,-4(%a2)
	move.b %d4,-3(%a2)
	move.b %d1,-2(%a2)
	move.b %d0,-1(%a2)
	cmp.l 44(%sp),%a2
	jne .L63
	move.l #131,%d0
	add.l %d0,48(%sp)
	add.l %d0,%a6
	cmp.l 52(%sp),%a6
	jne .L64
	moveq #1,%d0
.L30:
	movem.l (%sp),#31996
	lea (56,%sp),%sp
	rts
.L33:
	mvz.b 64(%a3),%d4
	move.l %d3,-(%sp)
	jsr (%a5)
	addq.l #4,%sp
	cmp.l %d4,%d0
	jne .L36
	cmp.l #255,%d3
	jeq .L72
	mulu.w #9,%d3
	cmp.l #255,%d2
	jeq .L40
.L121:
	add.l %d3,%d2
.L38:
	mvz.b 1(%a4),%d3
	mvz.b 1(%a3),%d4
	moveq #7,%d0
	cmp.l %d3,%d0
	jcs .L69
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L43
.L70:
	cmp.l #255,%d4
	jeq .L116
	mulu.w #9,%d4
	mvz.b 2(%a3),%d6
	moveq #7,%d0
	add.l %d4,%d3
	mvz.b 2(%a4),%d4
	cmp.l %d4,%d0
	jcs .L67
	jra .L68
.L43:
	mvz.b 65(%a3),%d6
	move.l %d4,-(%sp)
	jsr (%a5)
	addq.l #4,%sp
	cmp.l %d6,%d0
	jne .L75
	cmp.l #255,%d4
	jeq .L76
	mulu.w #9,%d4
	cmp.l #255,%d3
	jeq .L47
.L120:
	add.l %d4,%d3
.L42:
	mvz.b 2(%a4),%d4
	mvz.b 2(%a3),%d6
	moveq #7,%d0
	cmp.l %d4,%d0
	jcs .L67
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L50
.L68:
	cmp.l #255,%d6
	jeq .L117
	mulu.w #9,%d6
	mvz.b 3(%a4),%d7
	moveq #7,%d1
	add.l %d6,%d4
	mvz.b 3(%a3),%d6
	cmp.l %d7,%d1
	jcs .L65
	jra .L66
.L50:
	mvz.b 66(%a3),%d7
	move.l %d6,-(%sp)
	jsr (%a5)
	addq.l #4,%sp
	cmp.l %d7,%d0
	jne .L79
	cmp.l #255,%d6
	jeq .L80
	mulu.w #9,%d6
	cmp.l #255,%d4
	jeq .L54
.L122:
	add.l %d6,%d4
.L49:
	mvz.b 3(%a4),%d7
	mvz.b 3(%a3),%d6
	moveq #7,%d0
	cmp.l %d7,%d0
	jcs .L65
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L57
.L66:
	cmp.l #255,%d6
	jeq .L118
	move.l %d3,%d1
	or.l %d2,%d1
	mulu.w #9,%d6
	move.l %d6,%d0
	add.l %d7,%d0
	move.l %d0,%d6
	or.l %d4,%d1
	or.l %d6,%d1
	jpl .L119
.L60:
	movem.l (%sp),#31996
	clr.l %d0
	lea (56,%sp),%sp
	rts
.L32:
	cmp.l #255,%d2
	jne .L36
	mvz.b (%a6),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L33
	cmp.l %d3,%d2
	jeq .L71
	mulu.w #9,%d3
	mvz.b 1(%a3),%d4
	moveq #7,%d1
	move.l %d3,%d2
	addq.l #8,%d2
	mvz.b 1(%a4),%d3
	cmp.l %d3,%d1
	jcs .L69
	jra .L70
.L57:
	mvz.b 67(%a3),%d5
	move.l %d6,-(%sp)
	jsr (%a5)
	addq.l #4,%sp
	cmp.l %d5,%d0
	jne .L60
	cmp.l #255,%d6
	jeq .L82
	mulu.w #9,%d6
	cmp.l #255,%d7
	jeq .L62
.L123:
	move.l %d7,%d0
	add.l %d6,%d0
	move.l %d0,%d6
	jra .L58
.L115:
	mvz.b 1(%a4),%d3
	mvz.b 1(%a3),%d4
	add.l #756,%d2
	moveq #7,%d1
	cmp.l %d3,%d1
	jcs .L69
	jra .L70
.L118:
	move.l %d7,%d0
	add.l #756,%d0
	move.l %d0,%d6
	jra .L58
.L116:
	mvz.b 2(%a4),%d4
	mvz.b 2(%a3),%d6
	add.l #756,%d3
	moveq #7,%d0
	cmp.l %d4,%d0
	jcs .L67
	jra .L68
.L117:
	mvz.b 3(%a4),%d7
	mvz.b 3(%a3),%d6
	add.l #756,%d4
	moveq #7,%d1
	cmp.l %d7,%d1
	jcs .L65
	jra .L66
.L74:
	mvz.b 2(%a4),%d4
	mvz.b 2(%a3),%d6
	move.l #764,%d3
	moveq #7,%d0
	cmp.l %d4,%d0
	jcs .L67
	jra .L68
.L81:
	move.l #764,%d6
	move.l %d6,%d0
	jra .L58
.L78:
	mvz.b 3(%a4),%d7
	mvz.b 3(%a3),%d6
	move.l #764,%d4
	moveq #7,%d1
	cmp.l %d7,%d1
	jcs .L65
	jra .L66
.L71:
	mvz.b 1(%a4),%d3
	mvz.b 1(%a3),%d4
	move.l #764,%d2
	moveq #7,%d1
	cmp.l %d3,%d1
	jcs .L69
	jra .L70
.L76:
	move.l #756,%d4
	cmp.l #255,%d3
	jne .L120
.L47:
	move.l %d4,%d3
	addq.l #8,%d3
	jra .L42
.L72:
	move.l #756,%d3
	cmp.l #255,%d2
	jne .L121
.L40:
	move.l %d3,%d2
	addq.l #8,%d2
	jra .L38
.L80:
	move.l #756,%d6
	cmp.l #255,%d4
	jne .L122
.L54:
	move.l %d6,%d4
	addq.l #8,%d4
	jra .L49
.L82:
	move.l #756,%d6
	cmp.l #255,%d7
	jne .L123
.L62:
	move.l %d6,%d0
	addq.l #8,%d0
	move.l %d0,%d6
	jra .L58
.L79:
	moveq #-1,%d4
	jra .L49
.L36:
	moveq #-1,%d2
	jra .L38
.L75:
	moveq #-1,%d3
	jra .L42
	.size	hd_pack_c, .-hd_pack_c
	.align	2
	.globl	hd_packed_valid_c
	.type	hd_packed_valid_c, @function
hd_packed_valid_c:
	move.l 4(%sp),-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	jsr decode
	lea (12,%sp),%sp
	rts
	.size	hd_packed_valid_c, .-hd_packed_valid_c
	.align	2
	.globl	hd_unpack_c
	.type	hd_unpack_c, @function
hd_unpack_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	move.l 24(%sp),%d2
	move.l 16(%sp),4(%sp)
	move.l 20(%sp),8(%sp)
	move.l %d2,-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	jsr decode
	lea (12,%sp),%sp
	tst.l %d0
	jne .L130
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L130:
	move.l %d2,24(%sp)
	move.l 8(%sp),20(%sp)
	move.l 4(%sp),16(%sp)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra decode
	.size	hd_unpack_c, .-hd_unpack_c
