| Generated by generate.py; edit packed.c / packed.h.
#NO_APP
	.file	"packed.c"
	.text
	.align	2
	.type	decode, @function
decode:
	lea (-52,%sp),%sp
	movem.l #31996,(%sp)
	move.l 56(%sp),%a0
	move.l 56(%sp),%a4
	move.l 60(%sp),%d7
	move.l 64(%sp),%a2
	lea (16896,%a0),%a0
	lea (128,%a4),%a4
	move.l %a0,48(%sp)
	lea hd_mirror_c,%a3
.L16:
	mvz.b (%a2),%d0
	cmp.l #251,%d0
	jhi .L7
	move.l %d0,%d1
	moveq #84,%d2
	remu.l %d2,%d3:%d1
	divu.l %d2,%d1
	addq.l #1,%a2
	move.l %d1,%a6
	tst.l 56(%sp)
	jeq .L17
	st %d5
	move.b %d1,(%a4)
	move.l %a4,%d4
	add.l #-128,%d4
	move.l %d4,%a0
	move.l %d4,%a5
	move.b %d3,1(%a4)
	lea (64,%a0),%a0
	clr.l %d3
	move.l %a0,44(%sp)
	clr.l %d2
	move.b %d5,2(%a4)
.L5:
	moveq #9,%d0
	cmp.l %d3,%d0
	jcs .L15
	lsl.l #8,%d2
	mvz.b (%a2),%d0
	move.l %d3,%d1
	addq.l #8,%d1
	or.l %d0,%d2
	moveq #9,%d0
	cmp.l %d1,%d0
	jcs .L6
	lsl.l #8,%d2
	mvz.b 1(%a2),%d0
	or.l %d0,%d2
.L6:
	moveq #9,%d0
	moveq #-8,%d5
	sub.l %d3,%d0
	move.l %d0,%d3
	lsr.l #3,%d3
	and.l %d5,%d0
	lea 1(%a2,%d3.l),%a2
	move.l %d0,%d3
	add.l %d1,%d3
.L15:
	add.l #-10,%d3
	move.l %d2,%d6
	lsr.l %d3,%d6
	and.l #1023,%d6
	cmp.l #764,%d6
	jhi .L7
	move.l %d6,%d0
	moveq #9,%d5
	divu.l %d5,%d0
	moveq #2,%d1
	cmp.l %a6,%d1
	jeq .L8
	moveq #84,%d5
	cmp.l %d0,%d5
	jne .L7
	move.l #255,%d0
.L9:
	tst.l %d4
	jeq .L10
	move.b %d0,(%a5)
	move.l %d0,-(%sp)
	jsr (%a3)
	addq.l #4,%sp
	move.b %d0,64(%a5)
.L10:
	tst.l %d7
	jeq .L11
	moveq #9,%d5
	remu.l %d5,%d0:%d6
	moveq #8,%d6
	cmp.l %d0,%d6
	jeq .L29
	move.l %d7,%a0
	move.b %d0,(%a0)+
	move.l %a0,%d7
.L11:
	addq.l #1,%a5
	cmp.l 44(%sp),%a5
	jne .L5
	lea (131,%a4),%a4
	cmp.l 48(%sp),%a4
	jne .L16
	movem.l (%sp),#31996
	moveq #1,%d0
	lea (52,%sp),%sp
	rts
.L29:
	move.l %d7,%a0
	move.l #255,%d0
	move.b %d0,(%a0)+
	move.l %a0,%d7
	jra .L11
.L7:
	movem.l (%sp),#31996
	clr.l %d0
	lea (52,%sp),%sp
	rts
.L8:
	moveq #84,%d1
	cmp.l %d0,%d1
	jne .L9
	move.l #255,%d0
	jra .L9
.L17:
	clr.l %d4
	move.l %d4,%a0
	move.l %d4,%a5
	lea (64,%a0),%a0
	clr.l %d3
	move.l %a0,44(%sp)
	clr.l %d2
	jra .L5
	.size	decode, .-decode
	.align	2
	.globl	hd_pack_c
	.type	hd_pack_c, @function
hd_pack_c:
	lea (-48,%sp),%sp
	movem.l #31996,(%sp)
	move.l 56(%sp),%a6
	move.l 60(%sp),%a3
	move.l 52(%sp),%d0
	move.l %d0,%d4
	move.l %d0,%a5
	add.l #16896,%d0
	add.l #64,%d4
	lea (128,%a5),%a5
	move.l %d0,44(%sp)
	lea hd_mirror_c,%a4
.L41:
	lea (-128,%a5),%a2
	move.l %a2,-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L30
	move.b (%a5),%d0
	move.b 1(%a5),%d1
	clr.l %d3
	clr.l %d2
	muls.w #84,%d0
	add.l %d1,%d0
	move.b %d0,(%a3)+
.L40:
	mvz.b (%a6),%d6
	mvz.b (%a2)+,%d7
	moveq #7,%d0
	cmp.l %d6,%d0
	jcs .L32
	mvz.b (%a5),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L33
	cmp.l #255,%d7
	jeq .L58
	moveq #10,%d0
	addq.l #1,%a6
	lsl.l %d0,%d2
	mulu.w #9,%d7
	move.l %d3,%d0
	move.l %a3,%d1
	add.l #10,%d0
	add.l %d7,%d6
	or.l %d6,%d2
.L39:
	subq.l #8,%d0
	move.l %d2,%d5
	lsr.l %d0,%d5
	move.l %d1,%a0
	addq.l #1,%d1
	move.b %d5,(%a0)
	moveq #7,%d5
	cmp.l %d0,%d5
	jcs .L39
	addq.l #2,%d3
	move.l %d3,%d1
	lsr.l #3,%d1
	moveq #-8,%d5
	move.l %d1,%d0
	neg.l %d0
	and.l %d5,%d0
	lea 1(%a3,%d1.l),%a3
	add.l %d0,%d3
	cmp.l %a2,%d4
	jne .L40
	add.l #131,%d4
	lea (131,%a5),%a5
	cmp.l 44(%sp),%a5
	jne .L41
	moveq #1,%d0
.L30:
	movem.l (%sp),#31996
	lea (48,%sp),%sp
	rts
.L32:
	cmp.l #255,%d6
	jne .L36
	mvz.b (%a5),%d0
	subq.l #2,%d0
	tst.l %d0
	jeq .L33
	cmp.l %d7,%d6
	jeq .L42
	moveq #10,%d0
	addq.l #1,%a6
	lsl.l %d0,%d2
	mulu.w #9,%d7
	move.l %d3,%d0
	move.l %a3,%d1
	add.l #10,%d0
	move.l %d7,%d6
	addq.l #8,%d6
	or.l %d6,%d2
	jra .L39
.L33:
	mvz.b 63(%a2),%d5
	move.l %d7,-(%sp)
	jsr (%a4)
	addq.l #4,%sp
	cmp.l %d5,%d0
	jne .L36
	cmp.l #255,%d7
	jeq .L43
	mulu.w #9,%d7
	cmp.l #255,%d6
	jeq .L59
.L38:
	moveq #10,%d0
	add.l %d7,%d6
	lsl.l %d0,%d2
	move.l %d3,%d0
	addq.l #1,%a6
	add.l #10,%d0
	move.l %a3,%d1
	or.l %d6,%d2
	jra .L39
.L58:
	moveq #10,%d0
	add.l #756,%d6
	lsl.l %d0,%d2
	move.l %d3,%d0
	addq.l #1,%a6
	add.l #10,%d0
	move.l %a3,%d1
	or.l %d6,%d2
	jra .L39
.L42:
	moveq #10,%d0
	addq.l #1,%a6
	lsl.l %d0,%d2
	move.l #764,%d6
	move.l %d3,%d0
	move.l %a3,%d1
	add.l #10,%d0
	or.l %d6,%d2
	jra .L39
.L43:
	move.l #756,%d7
	cmp.l #255,%d6
	jne .L38
.L59:
	moveq #10,%d0
	addq.l #1,%a6
	lsl.l %d0,%d2
	move.l %d7,%d6
	addq.l #8,%d6
	move.l %d3,%d0
	move.l %a3,%d1
	add.l #10,%d0
	or.l %d6,%d2
	jra .L39
.L36:
	movem.l (%sp),#31996
	clr.l %d0
	lea (48,%sp),%sp
	rts
	.size	hd_pack_c, .-hd_pack_c
	.align	2
	.globl	hd_packed_valid_c
	.type	hd_packed_valid_c, @function
hd_packed_valid_c:
	move.l 4(%sp),-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	jsr decode
	lea (12,%sp),%sp
	rts
	.size	hd_packed_valid_c, .-hd_packed_valid_c
	.align	2
	.globl	hd_unpack_c
	.type	hd_unpack_c, @function
hd_unpack_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	move.l 24(%sp),%d2
	move.l 16(%sp),4(%sp)
	move.l 20(%sp),8(%sp)
	move.l %d2,-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	jsr decode
	lea (12,%sp),%sp
	tst.l %d0
	jne .L66
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L66:
	move.l %d2,24(%sp)
	move.l 8(%sp),20(%sp)
	move.l 4(%sp),16(%sp)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra decode
	.size	hd_unpack_c, .-hd_unpack_c
