| Generated by generate.py; edit recording.c / core.h.
#NO_APP
	.file	"recording.c"
	.text
	.align	2
	.type	convert, @function
convert:
	lea (-28,%sp),%sp
	movem.l #3100,(%sp)
	move.l 32(%sp),%d2
	move.l 36(%sp),%d3
	lea captures,%a3
	mvz.w %d2,%d0
	lsl.l #4,%d0
	move.l %d0,%a2
	add.l #ch_messages,%a2
	move.b 15(%a2),%d1
	move.b %d1,27(%sp)
	mvz.b %d1,%d4
	tst.b 1(%a3,%d2.l*4)
	jne .L9
	lea hd_scale_c,%a0
.L2:
	moveq #3,%d0
	and.l %d3,%d0
	move.l 40(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d3,%d0
	lsr.l #2,%d0
	move.l %d0,-(%sp)
	jsr (%a0)
	lea (12,%sp),%sp
	move.l %d0,%d1
	tst.l 44(%sp)
	jeq .L3
	moveq #127,%d0
	cmp.l %d4,%d0
	jcs .L12
.L4:
	move.w %d1,2(%a3,%d2.l*4)
	move.b %d3,(%a3,%d2.l*4)
	move.l 40(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_context_replacing_c
	tst.l %d0
	seq %d0
	neg.l %d0
	move.b %d0,1(%a3,%d2.l*4)
	movem.l 8(%sp),#3100
	lea (36,%sp),%sp
	rts
.L3:
	moveq #83,%d0
	cmp.l %d4,%d0
	jcs .L4
	mvz.w 2(%a3,%d2.l*4),%d0
	move.l %d0,-(%sp)
	move.l %d4,-(%sp)
	move.l %d1,28(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	move.l 20(%sp),%d1
	tst.l %d0
	jlt .L13
	moveq #-128,%d4
	or.l %d4,%d0
	move.b %d0,15(%a2)
.L14:
	move.w %d1,2(%a3,%d2.l*4)
	move.b %d3,(%a3,%d2.l*4)
	move.l 40(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_context_replacing_c
	tst.l %d0
	seq %d0
	neg.l %d0
	move.b %d0,1(%a3,%d2.l*4)
	movem.l 8(%sp),#3100
	lea (36,%sp),%sp
	rts
.L9:
	move.b (%a3,%d2.l*4),%d0
	moveq #3,%d1
	move.l 40(%sp),-(%sp)
	lea hd_scale_c,%a0
	and.l %d0,%d1
	lsr.l #2,%d0
	move.l %d1,-(%sp)
	moveq #63,%d1
	and.l %d0,%d1
	move.l %d1,-(%sp)
	move.l %a0,32(%sp)
	jsr (%a0)
	lea (12,%sp),%sp
	move.w %d0,2(%a3,%d2.l*4)
	move.l 20(%sp),%a0
	jra .L2
.L12:
	move.l %d1,-(%sp)
	move.b 31(%sp),%d4
	and.l %d0,%d4
	move.l %d4,-(%sp)
	move.l %d1,28(%sp)
	jsr hd_encode_c
	addq.l #8,%sp
	move.b %d0,15(%a2)
	move.l 20(%sp),%d1
	move.b %d3,(%a3,%d2.l*4)
	move.w %d1,2(%a3,%d2.l*4)
	move.l 40(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_context_replacing_c
	tst.l %d0
	seq %d0
	neg.l %d0
	move.b %d0,1(%a3,%d2.l*4)
	movem.l 8(%sp),#3100
	lea (36,%sp),%sp
	rts
.L13:
	moveq #6,%d0
	cmp.l %d4,%d0
	jcs .L7
	moveq #-128,%d0
	move.b %d0,15(%a2)
	jra .L14
.L7:
	st %d0
	move.b %d0,15(%a2)
	jra .L14
	.size	convert, .-convert
	.align	2
	.globl	hd_capture_c
	.type	hd_capture_c, @function
hd_capture_c:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	move.l 16(%sp),%d2
	move.l 12(%sp),4(%sp)
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L17
	moveq #7,%d1
	cmp.l %d2,%d1
	jcs .L17
	moveq #3,%d1
	and.l %d0,%d1
	lsr.l #2,%d0
	move.l %d2,-(%sp)
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr hd_scale_c
	lea (12,%sp),%sp
	move.l 4(%sp),12(%sp)
	move.l %d0,16(%sp)
	move.l (%sp)+,%d2
	addq.l #4,%sp
	jra hd_encode_c
.L17:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	addq.l #4,%sp
	rts
	.size	hd_capture_c, .-hd_capture_c
	.align	2
	.globl	hd_capture_message_c
	.type	hd_capture_message_c, @function
hd_capture_message_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	move.l 16(%sp),%d3
	sub.l #ch_messages,%d3
	cmp.l #4095,%d3
	jhi .L24
	moveq #15,%d0
	and.l %d3,%d0
	tst.l %d0
	jne .L24
	jsr hd_ui_context_c
	move.l %d0,%d2
	tst.l %d0
	jlt .L33
	moveq #7,%d0
	cmp.l 24(%sp),%d0
	jcs .L33
	moveq #127,%d1
	cmp.l 20(%sp),%d1
	jcs .L33
	moveq #3,%d0
	lsr.l #4,%d3
	and.l %d2,%d0
	move.l 24(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d2,%d0
	lsr.l #2,%d0
	move.l %d0,-(%sp)
	jsr hd_scale_c
	move.l %d0,20(%sp)
	move.l 36(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr hd_context_replacing_c
	lea (20,%sp),%sp
	lea (10,%sp),%a1
	tst.l %d0
	seq %d1
	move.l %d2,%d0
	lsl.l #8,%d0
	lea captures,%a0
	move.w (%a1),2(%a0,%d3.l*4)
	neg.l %d1
	move.b %d1,%d0
	move.w %d0,(%a0,%d3.l*4)
	move.l 8(%sp),-(%sp)
	move.l 24(%sp),-(%sp)
	jsr hd_encode_c
	addq.l #8,%sp
	lea hd_busy,%a0
	move.l 24(%sp),%d1
	move.l %d0,%d3
	tst.b (%a0,%d1.l)
	jeq .L21
	lea hd_busy_context,%a0
	mvz.b (%a0,%d1.l),%d0
	cmp.l %d2,%d0
	jne .L21
	lea hd_target,%a0
	tst.b (%a0,%d1.l)
	jeq .L36
.L21:
	move.l (%sp)+,%d2
	move.l %d3,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L24:
	jsr hd_ui_context_c
.L33:
	move.l (%sp)+,%d2
	move.l #255,%d3
	move.l %d3,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L36:
	move.l 8(%sp),-(%sp)
	move.l %d3,-(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L37
	move.l %d0,%d3
	bset #7,%d3
	move.l (%sp)+,%d2
	move.l %d3,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L37:
	moveq #6,%d0
	cmp.l %d3,%d0
	jcs .L33
	move.l (%sp)+,%d2
	move.l #128,%d3
	move.l %d3,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
	.size	hd_capture_message_c, .-hd_capture_message_c
	.align	2
	.globl	hd_record_modes_c
	.type	hd_record_modes_c, @function
hd_record_modes_c:
	lea (-20,%sp),%sp
	movem.l #3100,(%sp)
	move.l 24(%sp),%d3
	jsr hd_ui_context_c
	move.l %d0,%d4
	tst.l %d0
	jlt .L38
	moveq #7,%d0
	cmp.l %d3,%d0
	jcs .L38
	moveq #2,%d0
	cmp.l 28(%sp),%d0
	jcs .L38
	lea ch_messages+13,%a2
	clr.l %d2
	lea captures,%a3
.L41:
	tst.b 1(%a2)
	jeq .L40
	mvz.b (%a2),%d1
	cmp.l %d1,%d3
	jeq .L45
.L40:
	addq.l #1,%d2
	lea (16,%a2),%a2
	addq.l #4,%a3
	cmp.l #256,%d2
	jne .L41
.L38:
	movem.l (%sp),#3100
	lea (20,%sp),%sp
	rts
.L45:
	mvz.b (%a3),%d1
	cmp.l %d1,%d4
	jne .L40
	move.l 28(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l %d4,-(%sp)
	move.l %d2,-(%sp)
	jsr convert
	lea (16,%sp),%sp
	addq.l #1,%d2
	lea (16,%a2),%a2
	addq.l #4,%a3
	cmp.l #256,%d2
	jne .L41
	jra .L38
	.size	hd_record_modes_c, .-hd_record_modes_c
	.align	2
	.globl	hd_record_part_before_c
	.type	hd_record_part_before_c, @function
hd_record_part_before_c:
	lea (-24,%sp),%sp
	movem.l #15372,(%sp)
	move.l 28(%sp),%d3
	lea ch_messages+13,%a3
	lea captures,%a2
	lea hd_context_depends_c,%a4
	lea hd_scale_c,%a5
.L48:
	tst.b 1(%a3)
	jeq .L47
	tst.b 1(%a2)
	jne .L55
.L47:
	lea (16,%a3),%a3
	addq.l #4,%a2
	cmp.l #captures+1024,%a2
	jne .L48
.L56:
	movem.l (%sp),#15372
	lea (24,%sp),%sp
	rts
.L55:
	mvz.b (%a3),%d2
	mvz.b (%a2),%d0
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	move.l %d0,-(%sp)
	jsr (%a4)
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L47
	move.b (%a2),%d0
	moveq #3,%d1
	addq.l #4,%a2
	move.l %d2,-(%sp)
	lea (16,%a3),%a3
	and.l %d0,%d1
	lsr.l #2,%d0
	move.l %d1,-(%sp)
	moveq #63,%d1
	and.l %d0,%d1
	move.l %d1,-(%sp)
	jsr (%a5)
	lea (12,%sp),%sp
	move.w %d0,-2(%a2)
	clr.b %d0
	move.b %d0,-3(%a2)
	cmp.l #captures+1024,%a2
	jne .L48
	jra .L56
	.size	hd_record_part_before_c, .-hd_record_part_before_c
	.align	2
	.globl	hd_record_consume_c
	.type	hd_record_consume_c, @function
hd_record_consume_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	move.l 16(%sp),%d2
	sub.l #ch_messages,%d2
	cmp.l #4095,%d2
	jhi .L59
	moveq #15,%d0
	and.l %d2,%d0
	tst.l %d0
	jne .L59
	jsr hd_ui_context_c
	move.l %d0,%d1
	tst.l %d0
	jlt .L57
	lsr.l #4,%d2
	lea ch_messages,%a0
	mvs.w %d2,%d0
	lsl.l #4,%d0
	mvz.b 13(%a0,%d0.l),%d0
	move.l %d0,%a0
	moveq #7,%d0
	cmp.l %a0,%d0
	jcc .L63
.L57:
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L63:
	moveq #3,%d0
	and.l %d1,%d0
	move.l %a0,-(%sp)
	move.l %d0,-(%sp)
	move.l %d1,%d0
	lsr.l #2,%d0
	move.l %d0,-(%sp)
	move.l %d1,16(%sp)
	move.l %a0,20(%sp)
	jsr hd_part_type_c
	move.l %d0,-(%sp)
	move.l 24(%sp),%a0
	move.l %a0,-(%sp)
	move.l 24(%sp),%d1
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr convert
	lea (28,%sp),%sp
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L59:
	move.l (%sp)+,%d2
	addq.l #8,%sp
	jra hd_ui_context_c
	.size	hd_record_consume_c, .-hd_record_consume_c
	.local	captures
	.comm	captures,1024,2
