| Generated by generate.py; edit roots.c / roots.h.
#NO_APP
	.file	"roots.c"
	.text
	.align	2
	.globl	hd_mirror_c
	.type	hd_mirror_c, @function
hd_mirror_c:
	move.l %d2,-(%sp)
	moveq #83,%d1
	move.l 8(%sp),%d0
	cmp.l %d0,%d1
	jcs .L4
	moveq #7,%d2
	remu.l %d2,%d1:%d0
	divu.l %d2,%d0
	moveq #12,%d2
	lea (major.0),%a0
	subq.l #1,%d0
	muls.l %d2,%d0
	mvz.b (%a0,%d1.l),%d1
	add.l %d1,%d0
	tst.l %d0
	jlt .L5
	moveq #127,%d1
	cmp.l %d0,%d1
	jge .L1
	moveq #127,%d0
.L1:
	move.l (%sp)+,%d2
	rts
.L5:
	move.l (%sp)+,%d2
	clr.l %d0
	rts
.L4:
	move.l (%sp)+,%d2
	move.l #255,%d0
	rts
	.size	hd_mirror_c, .-hd_mirror_c
	.align	2
	.globl	hd_roots_reset_c
	.type	hd_roots_reset_c, @function
hd_roots_reset_c:
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #64,%d0
.L9:
	st %d1
	move.b %d1,64(%a0)
	move.b #-1,(%a0)+
	cmp.l %a0,%d0
	jne .L9
	clr.w %d0
	move.b %d1,130(%a1)
	move.w %d0,128(%a1)
	rts
	.size	hd_roots_reset_c, .-hd_roots_reset_c
	.align	2
	.globl	hd_roots_valid_c
	.type	hd_roots_valid_c, @function
hd_roots_valid_c:
	lea (-12,%sp),%sp
	moveq #2,%d1
	movem.l #28,(%sp)
	move.l 16(%sp),%a0
	move.b 128(%a0),%d0
	mvz.b %d0,%d3
	cmp.l %d3,%d1
	jcs .L14
	mvz.b 129(%a0),%d1
	moveq #83,%d2
	cmp.l %d1,%d2
	jcs .L14
	move.b 130(%a0),%d2
	move.l %d2,%d1
	add.l #-64,%d1
	mvz.b %d1,%d1
	cmp.l #190,%d1
	jls .L14
	tst.b %d0
	jne .L17
	mvz.b %d2,%d2
	cmp.l #255,%d2
	jeq .L17
.L14:
	movem.l (%sp),#28
	clr.l %d0
	lea (12,%sp),%sp
	rts
.L17:
	moveq #-3,%d4
	and.l %d0,%d4
	move.l %a0,%d2
	add.l #64,%d2
	move.l %d4,%a1
.L21:
	mvz.b (%a0)+,%d0
	moveq #83,%d4
	mvz.b 63(%a0),%d1
	cmp.l %d0,%d4
	jcs .L18
	moveq #127,%d0
	cmp.l %d1,%d0
	jcs .L14
	moveq #2,%d1
	cmp.l %d3,%d1
	jne .L14
	cmp.l %a0,%d2
	jne .L21
.L29:
	movem.l (%sp),#28
	moveq #1,%d0
	lea (12,%sp),%sp
	rts
.L18:
	cmp.l #255,%d0
	jne .L14
	moveq #127,%d4
	cmp.l %d1,%d4
	jcc .L20
	cmp.l %d1,%d0
	jne .L14
	cmp.l %a0,%d2
	jne .L21
	jra .L29
.L20:
	move.w %a1,%d0
	tst.b %d0
	jeq .L14
	cmp.l %a0,%d2
	jne .L21
	jra .L29
	.size	hd_roots_valid_c, .-hd_roots_valid_c
	.align	2
	.globl	hd_roots_sync_c
	.type	hd_roots_sync_c, @function
hd_roots_sync_c:
	lea (-56,%sp),%sp
	moveq #2,%d0
	movem.l #31996,(%sp)
	move.l 72(%sp),%d3
	move.l 60(%sp),%a3
	cmp.l %d3,%d0
	jcs .L31
	moveq #63,%d1
	cmp.l 80(%sp),%d1
	jcs .L31
	moveq #3,%d4
	and.l 76(%sp),%d4
	tst.l %d4
	jne .L31
	move.l 76(%sp),%d0
	lsr.l #2,%d0
	moveq #15,%d2
	and.l %d0,%d2
	moveq #11,%d0
	move.l %d2,48(%sp)
	cmp.l %d2,%d0
	jcs .L31
	move.l 76(%sp),%d1
	lsr.l #6,%d1
	moveq #6,%d2
	move.l %d1,52(%sp)
	cmp.l %d1,%d2
	jcs .L31
	move.l %a3,-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L31
	move.l 64(%sp),%a5
	move.l %a5,%d1
	move.l %a5,%a1
	add.l #64,%d1
.L34:
	move.b (%a1),%d0
	addq.l #1,%a1
	moveq #126,%d2
	add.l #-128,%d0
	mvz.b %d0,%d0
	cmp.l %d0,%d2
	jcc .L31
	cmp.l %a1,%d1
	jne .L34
	mvz.b 129(%a3),%d0
	moveq #12,%d1
	move.l 68(%sp),%a6
	move.l %a3,%d5
	move.l %a3,%a2
	add.l #64,%d5
	remu.l %d1,%d6:%d0
	divu.l %d1,%d0
	lea hd_encode_c,%a4
	lsl.l #4,%d0
	add.l %d0,%d6
	lsl.l #2,%d6
	move.l %d6,44(%sp)
.L56:
	move.b (%a5)+,%d7
	mvz.b 128(%a3),%d0
	move.l %a2,%a1
	addq.l #1,%a2
	subq.l #2,%d0
	mvz.b %d7,%d6
	tst.l %d0
	jeq .L73
.L35:
	tst.l %d3
	jne .L37
	move.l 44(%sp),-(%sp)
	move.l %d6,-(%sp)
	jsr (%a4)
	mvz.b 128(%a3),%d2
	addq.l #8,%sp
	subq.l #2,%d2
	tst.l %d2
	jeq .L74
.L41:
	move.b %d7,(%a6)
	st %d0
.L51:
	move.b %d7,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a6
	cmp.l %d5,%a2
	jne .L56
.L77:
	tst.l %d3
	jeq .L58
	move.l 52(%sp),%d1
	moveq #12,%d2
	moveq #2,%d0
	move.b 83(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 48(%sp),%d1
	move.b %d0,128(%a3)
	move.l %d4,%d0
	move.b %d1,129(%a3)
.L30:
	movem.l (%sp),#31996
	lea (56,%sp),%sp
	rts
.L31:
	movem.l (%sp),#31996
	moveq #-1,%d0
	lea (56,%sp),%sp
	rts
.L73:
	mvz.b 63(%a2),%d0
	cmp.l %d6,%d0
	jne .L35
	move.b (%a1),%d0
	mvz.b %d0,%d2
	tst.l %d3
	jne .L40
.L39:
	moveq #83,%d0
	cmp.l %d2,%d0
	jcs .L41
	move.l 44(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L75
	move.b %d0,%d7
	cmp.l %d6,%d0
	jeq .L76
	move.b %d0,(%a6)
	st %d0
	addq.l #1,%d4
.L79:
	move.b %d7,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a6
	cmp.l %d5,%a2
	jne .L56
	jra .L77
.L74:
	move.l %d0,%d2
	jra .L39
.L37:
	move.l 76(%sp),-(%sp)
	move.l %d6,-(%sp)
	jsr (%a4)
	addq.l #8,%sp
	move.l %d0,%d2
.L40:
	moveq #83,%d1
	cmp.l %d2,%d1
	jcs .L47
	moveq #7,%d1
	remu.l %d1,%d7:%d2
	divu.l %d1,%d2
	moveq #12,%d1
	lea (major.0),%a0
	subq.l #1,%d2
	muls.l %d1,%d2
	mvz.b (%a0,%d7.l),%d7
	add.l %d7,%d2
	tst.l %d2
	jlt .L48
	moveq #127,%d1
	cmp.l %d2,%d1
	jge .L49
	moveq #127,%d2
.L49:
	move.b %d2,%d7
	cmp.l %d6,%d2
	jeq .L78
	move.b %d2,(%a6)
	move.b %d7,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%d4
	addq.l #1,%a6
	cmp.l %d5,%a2
	jne .L56
	jra .L77
.L48:
	clr.b (%a6)
	clr.b %d7
	tst.l %d6
	jeq .L51
	addq.l #1,%d4
	jra .L79
.L47:
	move.b #-1,(%a6)
	st %d7
	cmp.l #255,%d6
	jeq .L51
	addq.l #1,%d4
	jra .L79
.L78:
	move.b %d6,(%a6)
	move.b %d7,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a6
	cmp.l %d5,%a2
	jne .L56
	jra .L77
.L75:
	moveq #6,%d1
	cmp.l %d2,%d1
	jcs .L80
	clr.b (%a6)
	clr.b %d7
	st %d0
	tst.l %d6
	jeq .L51
	addq.l #1,%d4
	jra .L79
.L58:
	move.l 52(%sp),%d1
	moveq #12,%d2
	moveq #1,%d0
	move.b 83(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 48(%sp),%d1
	move.b %d0,128(%a3)
	move.l %d4,%d0
	move.b %d1,129(%a3)
	jra .L30
.L76:
	st %d0
	move.b %d6,(%a6)
	move.b %d7,63(%a2)
	addq.l #1,%a6
	move.b %d0,-1(%a2)
	cmp.l %d5,%a2
	jne .L56
	jra .L77
.L80:
	move.b #127,(%a6)
	moveq #127,%d7
	st %d0
	moveq #127,%d2
	cmp.l %d6,%d2
	jeq .L51
	addq.l #1,%d4
	jra .L79
	.size	hd_roots_sync_c, .-hd_roots_sync_c
	.align	2
	.globl	hd_roots_detach_c
	.type	hd_roots_detach_c, @function
hd_roots_detach_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #63,%d0
	cmp.l 20(%sp),%d0
	jcs .L84
	moveq #3,%d0
	and.l 24(%sp),%d0
	tst.l %d0
	jne .L84
	move.l 24(%sp),%d0
	lsr.l #2,%d0
	moveq #15,%d1
	moveq #11,%d2
	and.l %d0,%d1
	move.l %d1,8(%sp)
	cmp.l %d1,%d2
	jcs .L84
	move.l 24(%sp),%d0
	lsr.l #6,%d0
	moveq #6,%d1
	move.l %d0,4(%sp)
	cmp.l %d0,%d1
	jcs .L84
	move.l 16(%sp),-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L84
	move.l 16(%sp),%a0
	tst.b 128(%a0)
	jeq .L86
	move.l 16(%sp),%a0
	mvz.b 130(%a0),%d1
	cmp.l 20(%sp),%d1
	jne .L86
	move.l 4(%sp),%d2
	moveq #12,%d1
	muls.l %d2,%d1
	st %d2
	add.l 8(%sp),%d1
	move.b %d2,130(%a0)
	move.b %d1,129(%a0)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L84:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	addq.l #8,%sp
	rts
.L86:
	move.l (%sp)+,%d2
	clr.l %d0
	addq.l #8,%sp
	rts
	.size	hd_roots_detach_c, .-hd_roots_detach_c
	.section	.rodata
	.type	major.0, @object
	.size	major.0, 7
major.0:
	.base64	"AAIEBQcJCw=="
