| Generated by generate.py; edit roots.c / roots.h.
#NO_APP
	.file	"roots.c"
	.text
	.align	2
	.globl	hd_mirror_c
	.type	hd_mirror_c, @function
hd_mirror_c:
	move.l 4(%sp),%d0
	moveq #83,%d1
	cmp.l %d0,%d1
	jcs .L3
	lea (mirror.0),%a0
	mvz.b (%a0,%d0.l),%d0
	rts
.L3:
	move.l #255,%d0
	rts
	.size	hd_mirror_c, .-hd_mirror_c
	.align	2
	.globl	hd_roots_reset_c
	.type	hd_roots_reset_c, @function
hd_roots_reset_c:
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #64,%d0
.L7:
	st %d1
	move.b %d1,64(%a0)
	move.b #-1,(%a0)+
	cmp.l %a0,%d0
	jne .L7
	clr.w %d0
	move.b %d1,130(%a1)
	move.w %d0,128(%a1)
	rts
	.size	hd_roots_reset_c, .-hd_roots_reset_c
	.align	2
	.globl	hd_roots_valid_c
	.type	hd_roots_valid_c, @function
hd_roots_valid_c:
	lea (-12,%sp),%sp
	moveq #2,%d1
	movem.l #28,(%sp)
	move.l 16(%sp),%a0
	move.b 128(%a0),%d0
	mvz.b %d0,%d3
	cmp.l %d3,%d1
	jcs .L12
	mvz.b 129(%a0),%d1
	moveq #83,%d2
	cmp.l %d1,%d2
	jcs .L12
	move.b 130(%a0),%d2
	move.l %d2,%d1
	add.l #-64,%d1
	mvz.b %d1,%d1
	cmp.l #190,%d1
	jls .L12
	tst.b %d0
	jne .L15
	mvz.b %d2,%d2
	cmp.l #255,%d2
	jeq .L15
.L12:
	movem.l (%sp),#28
	clr.l %d0
	lea (12,%sp),%sp
	rts
.L15:
	moveq #-3,%d4
	and.l %d0,%d4
	move.l %a0,%d2
	add.l #64,%d2
	move.l %d4,%a1
.L19:
	mvz.b (%a0)+,%d0
	moveq #83,%d4
	mvz.b 63(%a0),%d1
	cmp.l %d0,%d4
	jcs .L16
	moveq #127,%d0
	cmp.l %d1,%d0
	jcs .L12
	moveq #2,%d1
	cmp.l %d3,%d1
	jne .L12
	cmp.l %a0,%d2
	jne .L19
.L27:
	movem.l (%sp),#28
	moveq #1,%d0
	lea (12,%sp),%sp
	rts
.L16:
	cmp.l #255,%d0
	jne .L12
	moveq #127,%d4
	cmp.l %d1,%d4
	jcc .L18
	cmp.l %d1,%d0
	jne .L12
	cmp.l %a0,%d2
	jne .L19
	jra .L27
.L18:
	move.w %a1,%d0
	tst.b %d0
	jeq .L12
	cmp.l %a0,%d2
	jne .L19
	jra .L27
	.size	hd_roots_valid_c, .-hd_roots_valid_c
	.align	2
	.globl	hd_roots_sync_c
	.type	hd_roots_sync_c, @function
hd_roots_sync_c:
	lea (-56,%sp),%sp
	moveq #2,%d0
	movem.l #31996,(%sp)
	move.l 72(%sp),%d3
	move.l 60(%sp),%a3
	cmp.l %d3,%d0
	jcs .L29
	moveq #63,%d1
	cmp.l 80(%sp),%d1
	jcs .L29
	moveq #3,%d4
	and.l 76(%sp),%d4
	tst.l %d4
	jne .L29
	move.l 76(%sp),%d0
	lsr.l #2,%d0
	moveq #15,%d2
	and.l %d0,%d2
	moveq #11,%d0
	move.l %d2,48(%sp)
	cmp.l %d2,%d0
	jcs .L29
	move.l 76(%sp),%d1
	lsr.l #6,%d1
	moveq #6,%d2
	move.l %d1,52(%sp)
	cmp.l %d1,%d2
	jcs .L29
	move.l %a3,-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L29
	move.l 64(%sp),%a4
	move.l %a4,%d1
	move.l %a4,%a1
	add.l #64,%d1
.L32:
	move.b (%a1),%d0
	addq.l #1,%a1
	moveq #126,%d2
	add.l #-128,%d0
	mvz.b %d0,%d0
	cmp.l %d0,%d2
	jcc .L29
	cmp.l %d1,%a1
	jne .L32
	mvz.b 129(%a3),%d0
	moveq #12,%d1
	move.l 68(%sp),%a5
	move.l %a3,%d5
	move.l %a3,%a2
	add.l #64,%d5
	remu.l %d1,%d6:%d0
	divu.l %d1,%d0
	lea (mirror.0),%a6
	lsl.l #4,%d0
	add.l %d0,%d6
	lsl.l #2,%d6
	move.l %d6,44(%sp)
.L50:
	move.b (%a4)+,%d2
	mvz.b 128(%a3),%d0
	move.l %a2,%a1
	addq.l #1,%a2
	subq.l #2,%d0
	mvz.b %d2,%d6
	tst.l %d0
	jeq .L67
.L33:
	tst.l %d3
	jne .L35
	move.l 44(%sp),-(%sp)
	move.l %d6,-(%sp)
	jsr hd_encode_c
	mvz.b 128(%a3),%d7
	addq.l #8,%sp
	subq.l #2,%d7
	tst.l %d7
	jeq .L68
.L41:
	move.b %d2,(%a5)
.L62:
	st %d0
.L40:
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a5
	cmp.l %d5,%a2
	jne .L50
.L71:
	tst.l %d3
	jeq .L52
	move.l 52(%sp),%d1
	moveq #12,%d2
	moveq #2,%d0
	move.b 83(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 48(%sp),%d1
	move.b %d0,128(%a3)
	move.l %d4,%d0
	move.b %d1,129(%a3)
.L28:
	movem.l (%sp),#31996
	lea (56,%sp),%sp
	rts
.L29:
	movem.l (%sp),#31996
	moveq #-1,%d0
	lea (56,%sp),%sp
	rts
.L67:
	mvz.b 63(%a2),%d0
	cmp.l %d6,%d0
	jne .L33
	move.b (%a1),%d0
	mvz.b %d0,%d7
	tst.l %d3
	jne .L38
.L39:
	moveq #83,%d0
	cmp.l %d7,%d0
	jcs .L41
	move.l 44(%sp),-(%sp)
	move.l %d7,-(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L69
	move.b %d0,%d2
	cmp.l %d6,%d0
	jeq .L70
	move.b %d0,(%a5)
	st %d0
	move.b %d2,63(%a2)
	addq.l #1,%d4
	addq.l #1,%a5
	move.b %d0,-1(%a2)
	cmp.l %d5,%a2
	jne .L50
	jra .L71
.L68:
	move.l %d0,%d7
	jra .L39
.L35:
	move.l 76(%sp),-(%sp)
	move.l %d6,-(%sp)
	jsr hd_encode_c
	addq.l #8,%sp
	move.l %d0,%d7
.L38:
	moveq #83,%d1
	cmp.l %d7,%d1
	jcs .L72
	move.b (%a6,%d7.l),%d2
	mvz.b %d2,%d7
	move.b %d2,(%a5)
	cmp.l %d6,%d7
	jeq .L40
	addq.l #1,%d4
.L73:
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a5
	cmp.l %d5,%a2
	jne .L50
	jra .L71
.L72:
	move.b #-1,(%a5)
	st %d2
	cmp.l #255,%d6
	jeq .L40
	addq.l #1,%d4
	jra .L73
.L69:
	moveq #6,%d1
	cmp.l %d7,%d1
	jcs .L43
	clr.b (%a5)
	clr.b %d2
	st %d0
	tst.l %d6
	jeq .L40
	addq.l #1,%d4
	jra .L73
.L52:
	move.l 52(%sp),%d1
	moveq #12,%d2
	moveq #1,%d0
	move.b 83(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 48(%sp),%d1
	move.b %d0,128(%a3)
	move.l %d4,%d0
	move.b %d1,129(%a3)
	jra .L28
.L70:
	st %d0
	move.b %d6,(%a5)
	move.b %d2,63(%a2)
	addq.l #1,%a5
	move.b %d0,-1(%a2)
	cmp.l %d5,%a2
	jne .L50
	jra .L71
.L43:
	move.b #127,(%a5)
	moveq #127,%d2
	cmp.l %d6,%d2
	jeq .L62
	moveq #127,%d2
	st %d0
	addq.l #1,%d4
	addq.l #1,%a5
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	cmp.l %d5,%a2
	jne .L50
	jra .L71
	.size	hd_roots_sync_c, .-hd_roots_sync_c
	.align	2
	.globl	hd_roots_detach_c
	.type	hd_roots_detach_c, @function
hd_roots_detach_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #63,%d0
	cmp.l 20(%sp),%d0
	jcs .L77
	moveq #3,%d0
	and.l 24(%sp),%d0
	tst.l %d0
	jne .L77
	move.l 24(%sp),%d0
	lsr.l #2,%d0
	moveq #15,%d1
	moveq #11,%d2
	and.l %d0,%d1
	move.l %d1,8(%sp)
	cmp.l %d1,%d2
	jcs .L77
	move.l 24(%sp),%d0
	lsr.l #6,%d0
	moveq #6,%d1
	move.l %d0,4(%sp)
	cmp.l %d0,%d1
	jcs .L77
	move.l 16(%sp),-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L77
	move.l 16(%sp),%a0
	tst.b 128(%a0)
	jeq .L79
	move.l 16(%sp),%a0
	mvz.b 130(%a0),%d1
	cmp.l 20(%sp),%d1
	jne .L79
	move.l 4(%sp),%d2
	moveq #12,%d1
	muls.l %d2,%d1
	st %d2
	add.l 8(%sp),%d1
	move.b %d2,130(%a0)
	move.b %d1,129(%a0)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L77:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	addq.l #8,%sp
	rts
.L79:
	move.l (%sp)+,%d2
	clr.l %d0
	addq.l #8,%sp
	rts
	.size	hd_roots_detach_c, .-hd_roots_detach_c
	.section	.rodata
	.type	mirror.0, @object
	.size	mirror.0, 84
mirror.0:
	.base64	"AAAAAAAAAAACBAUHCQsMDhARExUXGBocHR8hIyQmKCkrLS8wMjQ1Nzk7PD5AQUNFR0hKTE1PUVNUVlhZW11fYGJkZWdpa2xucHFzdXd4enx9f39/"
