| Generated by generate.py; edit roots.c / roots.h.
#NO_APP
	.file	"roots.c"
	.text
	.align	2
	.globl	hd_roots_reset_c
	.type	hd_roots_reset_c, @function
hd_roots_reset_c:
	move.l 4(%sp),%a1
	move.l %a1,%d0
	move.l %a1,%a0
	add.l #64,%d0
.L2:
	st %d1
	move.b %d1,64(%a0)
	move.b #-1,(%a0)+
	cmp.l %a0,%d0
	jne .L2
	clr.w %d0
	move.b %d1,130(%a1)
	move.w %d0,128(%a1)
	rts
	.size	hd_roots_reset_c, .-hd_roots_reset_c
	.align	2
	.globl	hd_roots_valid_c
	.type	hd_roots_valid_c, @function
hd_roots_valid_c:
	lea (-12,%sp),%sp
	moveq #2,%d1
	movem.l #28,(%sp)
	move.l 16(%sp),%a0
	move.b 128(%a0),%d0
	mvz.b %d0,%d3
	cmp.l %d3,%d1
	jcs .L7
	mvz.b 129(%a0),%d1
	moveq #83,%d2
	cmp.l %d1,%d2
	jcs .L7
	move.b 130(%a0),%d2
	move.l %d2,%d1
	add.l #-64,%d1
	mvz.b %d1,%d1
	cmp.l #190,%d1
	jls .L7
	tst.b %d0
	jne .L10
	mvz.b %d2,%d2
	cmp.l #255,%d2
	jeq .L10
.L7:
	movem.l (%sp),#28
	clr.l %d0
	lea (12,%sp),%sp
	rts
.L10:
	moveq #-3,%d4
	and.l %d0,%d4
	move.l %a0,%d2
	add.l #64,%d2
	move.l %d4,%a1
.L14:
	mvz.b (%a0)+,%d0
	moveq #83,%d4
	mvz.b 63(%a0),%d1
	cmp.l %d0,%d4
	jcs .L11
	moveq #127,%d0
	cmp.l %d1,%d0
	jcs .L7
	moveq #2,%d1
	cmp.l %d3,%d1
	jne .L7
	cmp.l %a0,%d2
	jne .L14
.L22:
	movem.l (%sp),#28
	moveq #1,%d0
	lea (12,%sp),%sp
	rts
.L11:
	cmp.l #255,%d0
	jne .L7
	moveq #127,%d4
	cmp.l %d1,%d4
	jcc .L13
	cmp.l %d1,%d0
	jne .L7
	cmp.l %a0,%d2
	jne .L14
	jra .L22
.L13:
	move.w %a1,%d0
	tst.b %d0
	jeq .L7
	cmp.l %a0,%d2
	jne .L14
	jra .L22
	.size	hd_roots_valid_c, .-hd_roots_valid_c
	.align	2
	.globl	hd_roots_sync_c
	.type	hd_roots_sync_c, @function
hd_roots_sync_c:
	lea (-64,%sp),%sp
	moveq #2,%d0
	movem.l #31996,(%sp)
	move.l 80(%sp),%d3
	move.l 68(%sp),%a3
	move.l 84(%sp),%d6
	cmp.l %d3,%d0
	jcs .L24
	moveq #63,%d1
	cmp.l 88(%sp),%d1
	jcs .L24
	moveq #3,%d2
	and.l %d6,%d2
	move.l %d2,52(%sp)
	tst.l %d2
	jne .L24
	move.l %d6,%d0
	lsr.l #2,%d0
	moveq #15,%d1
	moveq #11,%d2
	and.l %d0,%d1
	move.l %d1,56(%sp)
	cmp.l %d1,%d2
	jcs .L24
	move.l %d6,%d1
	lsr.l #6,%d1
	moveq #6,%d2
	move.l %d1,60(%sp)
	cmp.l %d1,%d2
	jcs .L24
	move.l %a3,-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L24
	move.l 72(%sp),%a6
	move.l %a6,%d1
	move.l %a6,%a0
	add.l #64,%d1
.L27:
	move.b (%a0),%d0
	addq.l #1,%a0
	moveq #126,%d2
	add.l #-128,%d0
	mvz.b %d0,%d0
	cmp.l %d0,%d2
	jcc .L24
	cmp.l %d1,%a0
	jne .L27
	mvz.b 129(%a3),%d0
	moveq #12,%d1
	move.l 76(%sp),%a5
	move.l %a3,%d4
	move.l %a3,%a2
	add.l #64,%d4
	remu.l %d1,%d5:%d0
	divu.l %d1,%d0
	lea hd_encode_c,%a4
	move.l %d6,44(%sp)
	lsl.l #4,%d0
	add.l %d0,%d5
	lsl.l #2,%d5
.L42:
	move.b (%a6)+,%d2
	mvz.b 128(%a3),%d0
	move.l %a2,%a0
	moveq #2,%d6
	addq.l #1,%a2
	mvz.b %d2,%d7
	cmp.l %d0,%d6
	jeq .L51
.L28:
	tst.l %d3
	jne .L30
	move.l %d5,-(%sp)
	move.l %d7,-(%sp)
	jsr (%a4)
	mvz.b 128(%a3),%d1
	addq.l #8,%sp
	subq.l #2,%d1
	tst.l %d1
	jeq .L56
.L31:
	move.b %d2,(%a5)
	st %d0
.L39:
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a5
	cmp.l %a2,%d4
	jne .L42
.L59:
	tst.l %d3
	jeq .L44
	move.l 60(%sp),%d1
	moveq #12,%d2
	moveq #2,%d0
	move.b 91(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 56(%sp),%d1
	move.b %d0,128(%a3)
	move.l 52(%sp),%d0
	move.b %d1,129(%a3)
.L23:
	movem.l (%sp),#31996
	lea (64,%sp),%sp
	rts
.L24:
	movem.l (%sp),#31996
	moveq #-1,%d0
	lea (64,%sp),%sp
	rts
.L51:
	mvz.b 63(%a2),%d0
	cmp.l %d7,%d0
	jne .L28
	move.b (%a0),%d0
	tst.l %d3
	jne .L33
	mvz.b %d0,%d1
.L32:
	moveq #83,%d0
	cmp.l %d1,%d0
	jcs .L31
	move.l %d5,-(%sp)
	move.l %d1,-(%sp)
	move.l %d1,56(%sp)
	jsr hd_decode_c
	addq.l #8,%sp
	tst.l %d0
	jlt .L57
	move.b %d0,%d2
	cmp.l %d7,%d0
	jeq .L58
	move.b %d0,(%a5)
	st %d0
	move.b %d2,63(%a2)
	addq.l #1,52(%sp)
	addq.l #1,%a5
	move.b %d0,-1(%a2)
	cmp.l %a2,%d4
	jne .L42
	jra .L59
.L56:
	move.l %d0,%d1
	jra .L32
.L30:
	move.l 44(%sp),-(%sp)
	move.l %d7,-(%sp)
	jsr (%a4)
	addq.l #8,%sp
.L33:
	addq.l #1,%a5
	move.b %d2,-1(%a5)
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	cmp.l %a2,%d4
	jne .L42
	jra .L59
.L57:
	moveq #6,%d2
	cmp.l 48(%sp),%d2
	jcs .L60
	clr.b (%a5)
	clr.b %d2
	st %d0
	tst.l %d7
	jeq .L39
	addq.l #1,52(%sp)
.L61:
	move.b %d2,63(%a2)
	move.b %d0,-1(%a2)
	addq.l #1,%a5
	cmp.l %a2,%d4
	jne .L42
	jra .L59
.L44:
	move.l 60(%sp),%d1
	moveq #12,%d2
	moveq #1,%d0
	move.b 91(%sp),130(%a3)
	muls.l %d2,%d1
	add.l 56(%sp),%d1
	move.b %d0,128(%a3)
	move.l 52(%sp),%d0
	move.b %d1,129(%a3)
	jra .L23
.L58:
	st %d0
	move.b %d7,(%a5)
	move.b %d2,63(%a2)
	addq.l #1,%a5
	move.b %d0,-1(%a2)
	cmp.l %a2,%d4
	jne .L42
	jra .L59
.L60:
	move.b #127,(%a5)
	moveq #127,%d2
	st %d0
	moveq #127,%d6
	cmp.l %d7,%d6
	jeq .L39
	addq.l #1,52(%sp)
	jra .L61
	.size	hd_roots_sync_c, .-hd_roots_sync_c
	.align	2
	.globl	hd_roots_detach_c
	.type	hd_roots_detach_c, @function
hd_roots_detach_c:
	subq.l #8,%sp
	move.l %d2,-(%sp)
	moveq #63,%d0
	cmp.l 20(%sp),%d0
	jcs .L65
	moveq #3,%d0
	and.l 24(%sp),%d0
	tst.l %d0
	jne .L65
	move.l 24(%sp),%d0
	lsr.l #2,%d0
	moveq #15,%d1
	moveq #11,%d2
	and.l %d0,%d1
	move.l %d1,8(%sp)
	cmp.l %d1,%d2
	jcs .L65
	move.l 24(%sp),%d0
	lsr.l #6,%d0
	moveq #6,%d1
	move.l %d0,4(%sp)
	cmp.l %d0,%d1
	jcs .L65
	move.l 16(%sp),-(%sp)
	jsr hd_roots_valid_c
	addq.l #4,%sp
	tst.l %d0
	jeq .L65
	move.l 16(%sp),%a0
	tst.b 128(%a0)
	jeq .L67
	move.l 16(%sp),%a0
	mvz.b 130(%a0),%d1
	cmp.l 20(%sp),%d1
	jne .L67
	move.l 4(%sp),%d2
	moveq #12,%d1
	muls.l %d2,%d1
	st %d2
	add.l 8(%sp),%d1
	move.b %d2,130(%a0)
	move.b %d1,129(%a0)
	move.l (%sp)+,%d2
	addq.l #8,%sp
	rts
.L65:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	addq.l #8,%sp
	rts
.L67:
	move.l (%sp)+,%d2
	clr.l %d0
	addq.l #8,%sp
	rts
	.size	hd_roots_detach_c, .-hd_roots_detach_c
