| Generated by generate.py; edit storage.c / packed.h.
#NO_APP
	.file	"storage.c"
	.text
	.align	2
	.globl	hd_nv_dirty_c
	.type	hd_nv_dirty_c, @function
hd_nv_dirty_c:
	move.l 4(%sp),%d0
	moveq #15,%d1
	cmp.l %d0,%d1
	jcs .L1
	cmp.l ch_nv_bank.l,%d0
	jeq .L5
.L1:
	rts
.L5:
	clr.l 269473120
	moveq #1,%d0
	addq.l #1,generation
	move.l %d0,pending
	rts
	.size	hd_nv_dirty_c, .-hd_nv_dirty_c
	.align	2
	.globl	hd_payload_valid_c
	.type	hd_payload_valid_c, @function
hd_payload_valid_c:
	jra hd_packed_valid_c
	.size	hd_payload_valid_c, .-hd_payload_valid_c
	.align	2
	.globl	hd_payload_hash_c
	.type	hd_payload_hash_c, @function
hd_payload_hash_c:
	move.l %d2,-(%sp)
	move.l #-2128831035,%d0
	move.l 8(%sp),%d1
	move.l %d1,%a1
	lea (10368,%a1),%a1
.L9:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l %d1,%a1
	jne .L9
	move.l (%sp)+,%d2
	rts
	.size	hd_payload_hash_c, .-hd_payload_hash_c
	.align	2
	.globl	hd_export_c
	.type	hd_export_c, @function
hd_export_c:
	lea (-36,%sp),%sp
	moveq #15,%d0
	movem.l #7420,(%sp)
	move.l 40(%sp),%d4
	move.l 44(%sp),%a3
	cmp.l %d4,%d0
	jcc .L23
	clr.l %d2
.L13:
	move.l %d2,%d0
	movem.l (%sp),#7420
	lea (36,%sp),%sp
	rts
.L23:
	move.l %d4,-(%sp)
	move.l #16768,%d7
	jsr hd_checkpoint_c
	move.l %d4,%d6
	addq.l #4,%sp
	muls.l %d4,%d7
	lea hd_revision_c,%a2
	moveq #13,%d0
	lsl.l %d0,%d6
	lea hd_pack_c,%a4
	add.l #hd_banks,%d7
	add.l #ch_lock_table,%d6
.L15:
	move.l %d4,-(%sp)
	move.l generation,%d3
	jsr (%a2)
	move.l %a3,-(%sp)
	move.l %d6,-(%sp)
	move.l %d7,-(%sp)
	move.l %d0,%d5
	jsr (%a4)
	lea (16,%sp),%sp
	move.l %d0,%d2
	cmp.l generation.l,%d3
	jne .L15
.L24:
	move.l %d4,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	cmp.l %d0,%d5
	jeq .L13
	move.l %d4,-(%sp)
	move.l generation,%d3
	jsr (%a2)
	move.l %a3,-(%sp)
	move.l %d6,-(%sp)
	move.l %d7,-(%sp)
	move.l %d0,%d5
	jsr (%a4)
	lea (16,%sp),%sp
	move.l %d0,%d2
	cmp.l generation.l,%d3
	jne .L15
	jra .L24
	.size	hd_export_c, .-hd_export_c
	.align	2
	.globl	hd_import_c
	.type	hd_import_c, @function
hd_import_c:
	subq.l #4,%sp
	move.l %d2,-(%sp)
	moveq #15,%d2
	move.l 12(%sp),%d1
	move.l 16(%sp),%d0
	cmp.l %d1,%d2
	jcc .L32
.L25:
	move.l (%sp)+,%d2
	addq.l #4,%sp
	rts
.L32:
	move.l %d0,-(%sp)
	moveq #13,%d2
	move.l %d1,%d0
	lsl.l %d2,%d0
	add.l #ch_lock_table,%d0
	move.l %d0,-(%sp)
	move.l #16768,%d0
	muls.l %d1,%d0
	add.l #hd_banks,%d0
	move.l %d0,-(%sp)
	move.l %d1,16(%sp)
	jsr hd_unpack_c
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L25
	move.l 4(%sp),12(%sp)
	move.l (%sp)+,%d2
	addq.l #4,%sp
	jra hd_bank_loaded_c
	.size	hd_import_c, .-hd_import_c
	.align	2
	.globl	hd_native_hash_c
	.type	hd_native_hash_c, @function
hd_native_hash_c:
	moveq #15,%d0
	cmp.l 4(%sp),%d0
	jcs .L35
	move.l 8(%sp),%d0
	rts
.L35:
	clr.l %d0
	rts
	.size	hd_native_hash_c, .-hd_native_hash_c
	.align	2
	.globl	hd_nv_save_c
	.type	hd_nv_save_c, @function
hd_nv_save_c:
	lea (-32,%sp),%sp
	moveq #15,%d0
	movem.l #3324,(%sp)
	move.l 36(%sp),%d2
	cmp.l %d2,%d0
	jcc .L51
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L51:
	move.l %d2,-(%sp)
	jsr hd_checkpoint_c
#APP
| 19 "storage.c" 1
	move.w %sr,%d0
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	move.l %d2,ch_nv_bank
	addq.l #4,%sp
	addq.l #1,generation
	tst.l available
	jeq .L52
	clr.l available
	clr.l 269473120
#APP
| 23 "storage.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	move.l generation,%d5
	lea hd_revision_c,%a2
	lea hd_pack_c,%a3
	move.l ch_nv_bank,%d3
	move.l %d3,-(%sp)
	jsr (%a2)
	move.l #269473152,-(%sp)
	move.l %d3,%d1
	move.l %d0,%d6
	moveq #13,%d0
	lsl.l %d0,%d1
	move.l #16768,%d0
	muls.l %d3,%d0
	add.l #hd_banks,%d0
	add.l #ch_lock_table,%d1
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr (%a3)
	lea (16,%sp),%sp
	move.l %d0,%d4
	tst.l %d0
	jne .L53
.L46:
	clr.l %d2
.L41:
#APP
| 19 "storage.c" 1
	move.w %sr,%d7
	move.w #0x2700,%sr
| 0 "" 2
#NO_APP
	cmp.l generation.l,%d5
	jeq .L54
.L43:
#APP
| 23 "storage.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	move.l generation,%d5
	move.l ch_nv_bank,%d3
	move.l %d3,-(%sp)
	jsr (%a2)
	move.l #269473152,-(%sp)
	move.l %d3,%d1
	move.l %d0,%d6
	moveq #13,%d0
	lsl.l %d0,%d1
	move.l #16768,%d0
	muls.l %d3,%d0
	add.l #hd_banks,%d0
	add.l #ch_lock_table,%d1
	move.l %d1,-(%sp)
	move.l %d0,-(%sp)
	jsr (%a3)
	lea (16,%sp),%sp
	move.l %d0,%d4
	tst.l %d0
	jeq .L46
.L53:
	move.l #-2128831035,%d2
	move.l #269473152,%d0
.L42:
	move.l %d0,%a0
	addq.l #1,%d0
	mvz.b (%a0),%d1
	eor.l %d1,%d2
	move.l #16777619,%d1
	muls.l %d1,%d2
	cmp.l #269483520,%d0
	jeq .L41
	move.l %d0,%a0
	addq.l #1,%d0
	mvz.b (%a0),%d1
	eor.l %d1,%d2
	move.l #16777619,%d1
	muls.l %d1,%d2
	cmp.l #269483520,%d0
	jne .L42
	jra .L41
.L54:
	move.l %d3,-(%sp)
	jsr (%a2)
	addq.l #4,%sp
	cmp.l %d6,%d0
	jne .L43
	tst.l %d4
	jne .L44
	moveq #1,%d0
	move.l %d0,available
#APP
| 23 "storage.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L44:
	moveq #3,%d1
	move.l %d1,269473124
	move.l #10368,%d0
	move.l %d3,269473128
	move.l %d0,269473132
	move.l %d2,269473136
	move.l %d5,269473140
	lea ch_lock_status,%a0
	mvz.b (%a0,%d3.l),%d0
	move.l %d0,269473144
	move.l #1212436019,%d0
	move.l 269473144,%d1
	not.l %d1
	move.l %d1,269473148
	moveq #1,%d1
	move.l %d0,269473120
	clr.l pending
	move.l %d1,available
#APP
| 23 "storage.c" 1
	move.w %d7,%sr
| 0 "" 2
#NO_APP
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
.L52:
#APP
| 23 "storage.c" 1
	move.w %d0,%sr
| 0 "" 2
#NO_APP
	movem.l (%sp),#3324
	lea (32,%sp),%sp
	rts
	.size	hd_nv_save_c, .-hd_nv_save_c
	.align	2
	.globl	hd_nv_poll_c
	.type	hd_nv_poll_c, @function
hd_nv_poll_c:
	tst.l pending
	jeq .L55
	moveq #15,%d0
	cmp.l ch_nv_bank.l,%d0
	jcc .L62
.L55:
	rts
.L62:
	move.l ch_nv_bank,-(%sp)
	jsr hd_nv_save_c
	addq.l #4,%sp
	rts
	.size	hd_nv_poll_c, .-hd_nv_poll_c
	.align	2
	.globl	hd_nv_restore_c
	.type	hd_nv_restore_c, @function
hd_nv_restore_c:
	move.l %d2,-(%sp)
	moveq #15,%d0
	cmp.l 8(%sp),%d0
	jcs .L66
	move.l #1212436019,%d1
	cmp.l 269473120.l,%d1
	jeq .L74
.L66:
	clr.l %d0
.L63:
	move.l (%sp)+,%d2
	rts
.L74:
	moveq #3,%d2
	cmp.l 269473124.l,%d2
	jne .L66
	move.l 8(%sp),%d0
	cmp.l 269473128.l,%d0
	jne .L66
	move.l #10368,%d1
	cmp.l 269473132.l,%d1
	jne .L66
	moveq #4,%d2
	cmp.l 269473144.l,%d2
	jcs .L66
	move.l 269473148,%d1
	move.l 269473144,%d0
	not.l %d0
	cmp.l %d1,%d0
	jne .L66
	move.l 269473136,%a1
	move.l #-2128831035,%d0
	move.l #269473152,%d1
.L67:
	move.l %d1,%a0
	addq.l #1,%d1
	mvz.b (%a0),%d2
	eor.l %d2,%d0
	move.l #16777619,%d2
	muls.l %d2,%d0
	cmp.l #269483520,%d1
	jne .L67
	cmp.l %a1,%d0
	jne .L66
	move.l 8(%sp),%d1
	moveq #13,%d0
	move.l #16768,%d2
	lsl.l %d0,%d1
	move.l 8(%sp),%d0
	move.l #269473152,-(%sp)
	muls.l %d2,%d0
	add.l #ch_lock_table,%d1
	move.l %d1,-(%sp)
	add.l #hd_banks,%d0
	move.l %d0,-(%sp)
	jsr hd_unpack_c
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L63
	move.l 8(%sp),%d1
	move.l 269473144,%d0
	lea ch_lock_status,%a0
	move.l %d1,ch_nv_bank
	move.b %d0,(%a0,%d1.l)
	move.l %d1,-(%sp)
	jsr hd_bank_loaded_c
	addq.l #4,%sp
	move.l (%sp)+,%d2
	moveq #1,%d0
	rts
	.size	hd_nv_restore_c, .-hd_nv_restore_c
	.data
	.align	2
	.type	pending, @object
	.size	pending, 4
pending:
	.long	1
	.align	2
	.type	available, @object
	.size	available, 4
available:
	.long	1
	.align	2
	.type	generation, @object
	.size	generation, 4
generation:
	.long	1
