| Generated by generate.py; edit ui.c / core.h.
#NO_APP
	.file	"ui.c"
	.text
	.align	2
	.globl	hd_ui_value_c
	.type	hd_ui_value_c, @function
hd_ui_value_c:
	subq.l #4,%sp
	move.l %d3,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L5
	move.b 269161680,%d1
	move.l %d0,%d2
	lsr.l #2,%d2
	mvz.b 269161676,%d3
	tst.l 16(%sp)
	jlt .L8
	mvz.b %d1,%d1
	move.l %d1,8(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	tst.l %d0
	jlt .L4
	bset #8,%d0
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L8:
	moveq #3,%d1
	and.l %d0,%d1
	move.l %d3,-(%sp)
	move.l %d1,-(%sp)
	move.l %d2,-(%sp)
	jsr hd_base_c
	move.l %d0,-(%sp)
	clr.l -(%sp)
	jsr hd_scene_ui_c
	lea (20,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L4:
	move.l 16(%sp),-(%sp)
	move.l %d3,-(%sp)
	move.l 16(%sp),-(%sp)
	move.l %d2,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l (%sp)+,%d2
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
.L5:
	move.l (%sp)+,%d2
	moveq #-1,%d0
	move.l (%sp)+,%d3
	addq.l #4,%sp
	rts
	.size	hd_ui_value_c, .-hd_ui_value_c
	.align	2
	.globl	hd_ui_advance_c
	.type	hd_ui_advance_c, @function
hd_ui_advance_c:
	lea (-12,%sp),%sp
	moveq #83,%d0
	move.l 16(%sp),%d1
	movem.l #28,(%sp)
	cmp.l %d1,%d0
	jcc .L10
	moveq #35,%d1
.L10:
	move.l 20(%sp),%d0
	moveq #-83,%d2
	cmp.l %d0,%d2
	jle .L11
	moveq #-83,%d0
.L12:
	move.b 1175456541,%d4
	move.w %d4,%a0
	move.l %a0,%d2
	btst #5,%d2
	jne .L22
.L13:
	add.l %d1,%d0
	moveq #83,%d3
	cmp.l %d0,%d3
	jlt .L23
	tst.l %d0
	jlt .L24
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L11:
	moveq #83,%d3
	cmp.l %d0,%d3
	jge .L12
	move.b 1175456541,%d4
	moveq #83,%d0
	move.w %d4,%a0
	move.l %a0,%d2
	btst #5,%d2
	jeq .L13
.L22:
	move.l %d1,%d3
	moveq #7,%d4
	divs.l %d4,%d3
	add.l %d3,%d0
	moveq #11,%d3
	cmp.l %d0,%d3
	jlt .L25
	tst.l %d0
	jlt .L26
	moveq #7,%d4
	rems.l %d4,%d2:%d1
	muls.w #7,%d0
	add.l %d2,%d0
.L27:
	movem.l (%sp),#28
	lea (12,%sp),%sp
	rts
.L23:
	movem.l (%sp),#28
	moveq #83,%d0
	lea (12,%sp),%sp
	rts
.L24:
	movem.l (%sp),#28
	clr.l %d0
	lea (12,%sp),%sp
	rts
.L25:
	moveq #7,%d4
	moveq #11,%d0
	rems.l %d4,%d2:%d1
	muls.w #7,%d0
	add.l %d2,%d0
	jra .L27
.L26:
	moveq #7,%d4
	clr.l %d0
	rems.l %d4,%d2:%d1
	muls.w #7,%d0
	add.l %d2,%d0
	jra .L27
	.size	hd_ui_advance_c, .-hd_ui_advance_c
	.align	2
	.globl	hd_ui_edit_c
	.type	hd_ui_edit_c, @function
hd_ui_edit_c:
	lea (-36,%sp),%sp
	movem.l #3324,(%sp)
	jsr hd_ui_context_c
	tst.l %d0
	jlt .L29
	move.b 269161680,%d2
	mvz.b 269161676,%d5
	moveq #7,%d1
	cmp.l %d5,%d1
	jcc .L30
.L29:
	clr.l %d0
.L28:
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L30:
	moveq #3,%d3
	and.l %d0,%d3
	lsr.l #2,%d0
	move.l %d5,-(%sp)
	move.l %d0,%a3
	move.l %d3,-(%sp)
	move.l %d0,-(%sp)
	jsr hd_part_type_c
	lea (12,%sp),%sp
	tst.l %d0
	jeq .L29
	move.l 40(%sp),%d0
	or.l 44(%sp),%d0
	jeq .L28
	tst.l 48(%sp)
	jeq .L70
	mvz.b %d2,%d2
	mvz.w 1175263050,%d7
	move.l 1175263052,%d3
	clr.l %d0
	move.l %d2,32(%sp)
	clr.l %d2
.L57:
	move.l %d7,%d6
	lsr.l %d2,%d6
	btst #0,%d6
	jeq .L43
	moveq #63,%d1
	cmp.l %d3,%d1
	jcs .L43
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 40(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_degree_c
	lea (16,%sp),%sp
	move.l %d0,%a2
	tst.l 44(%sp)
	jeq .L49
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 40(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_lock_c
	lea (16,%sp),%sp
	tst.l %d0
	jlt .L49
	move.l #255,%d1
.L48:
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d6,%d0
.L43:
	addq.l #1,%d2
	addq.l #1,%d3
	moveq #16,%d1
	cmp.l %d2,%d1
	jne .L57
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L49:
	moveq #83,%d4
	cmp.l %a2,%d4
	jcc .L46
	move.w #35,%a2
.L46:
	move.l 40(%sp),%a0
	moveq #-83,%d0
	cmp.l %a0,%d0
	jle .L50
	move.w #-83,%a0
.L51:
	move.b 1175456541,%d0
	btst #5,%d0
	jne .L71
.L52:
	move.l %a0,%d1
	moveq #83,%d0
	add.l %a2,%d1
	cmp.l %d1,%d0
	jge .L55
	moveq #83,%d1
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d6,%d0
	jra .L43
.L50:
	moveq #83,%d1
	cmp.l 40(%sp),%d1
	jge .L51
	move.b 1175456541,%d0
	move.w #83,%a0
	btst #5,%d0
	jeq .L52
.L71:
	moveq #7,%d4
	move.l %a2,%d0
	divs.l %d4,%d0
	moveq #11,%d4
	lea (%a0,%d0.l),%a1
	cmp.l %a1,%d4
	jge .L53
	move.w #11,%a1
.L54:
	moveq #7,%d1
	move.l %a2,%d0
	rems.l %d1,%d4:%d0
	move.w %a1,%d1
	muls.w #7,%d1
	add.l %d4,%d1
.L72:
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d6,%d0
	jra .L43
.L55:
	tst.l %d1
	jge .L48
	clr.l %d1
	move.l %d1,-(%sp)
	move.l %d3,-(%sp)
	move.l %d5,-(%sp)
	move.l 44(%sp),-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_step_c
	lea (20,%sp),%sp
	moveq #1,%d0
	and.l %d6,%d0
	jra .L43
.L53:
	tst.l %a1
	jge .L54
	moveq #7,%d1
	sub.l %a1,%a1
	move.l %a2,%d0
	rems.l %d1,%d4:%d0
	move.w %a1,%d1
	muls.w #7,%d1
	add.l %d4,%d1
	jra .L72
.L70:
	move.l %d5,-(%sp)
	moveq #83,%d2
	move.l %d3,-(%sp)
	move.l %a3,-(%sp)
	jsr hd_base_c
	lea (12,%sp),%sp
	cmp.l %d0,%d2
	jcc .L33
	moveq #35,%d0
.L33:
	move.l 40(%sp),%d6
	moveq #-83,%d4
	cmp.l %d6,%d4
	jle .L34
	moveq #-83,%d6
.L35:
	move.b 1175456541,%d1
	btst #5,%d1
	jne .L73
	add.l %d0,%d6
	moveq #83,%d4
	cmp.l %d6,%d4
	jge .L40
	moveq #83,%d6
.L39:
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
.L74:
	movem.l (%sp),#3324
	lea (36,%sp),%sp
	rts
.L34:
	moveq #83,%d7
	cmp.l %d6,%d7
	jge .L35
	moveq #83,%d6
	jra .L35
.L40:
	tst.l %d6
	jge .L39
	clr.l %d6
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
	jra .L74
.L73:
	move.l %d0,%d1
	moveq #7,%d4
	divs.l %d4,%d1
	moveq #11,%d7
	add.l %d1,%d6
	cmp.l %d6,%d7
	jge .L37
	moveq #11,%d6
.L38:
	moveq #7,%d2
	rems.l %d2,%d1:%d0
	muls.w #7,%d6
	add.l %d1,%d6
.L75:
	move.l %d6,-(%sp)
	move.l %d5,-(%sp)
	move.l %d3,-(%sp)
	move.l %a3,-(%sp)
	jsr hd_edit_base_c
	lea (16,%sp),%sp
	moveq #1,%d0
	jra .L74
.L37:
	tst.l %d6
	jge .L38
	moveq #7,%d2
	clr.l %d6
	rems.l %d2,%d1:%d0
	muls.w #7,%d6
	add.l %d1,%d6
	jra .L75
	.size	hd_ui_edit_c, .-hd_ui_edit_c
