#!/usr/bin/env python3
"""Generate fixed-size voicing assembly using the existing freestanding pattern."""
import pathlib
import subprocess
import sys
import tempfile
from degrees.generate import FLAGS

HERE = pathlib.Path(__file__).resolve().parent

def main():
    with tempfile.TemporaryDirectory(prefix='harmony-size-') as tmp:
        dest = pathlib.Path(tmp)/'size.s'
        subprocess.run(['m68k-elf-gcc', *FLAGS, '-S', '-o', str(dest), 'size.c'],
                       cwd=HERE, check=True)
        body = '| Generated by generate.py; edit size.c / size.h.\n'+dest.read_text()
    target = HERE/'size.s'
    if '--check' in sys.argv:
        if not target.exists() or target.read_text()!=body:
            raise SystemExit(f'stale generated assembly: {target}')
        print('Harmony SIZE generated assembly matches')
    else:
        target.write_text(body)

if __name__ == '__main__':
    main()
