"""Scale-degree MIDI roots and generated chords before the stock arpeggiator."""
from remix.schema import Category, Claims, Detour, Gate, Kind, Linked, Module, Proof, Poke, SymbolRef


def follow_inc(modules):
    return ('.set HAVE_FOLLOW,1\n' if 'MIDI FOLLOW' in modules else '') + ('.set HAVE_SCALES,1\n' if 'MIDI SCALES' in modules else '')


MODULE = Module(
    name='midi-harmony', key='MIDI HARMONY', kind=Kind.CF_PATCH,
    category=Category.MIDI_USB, author='Mattias Wolff',
    author_url='https://github.com/mattiaswolff/octabam', proof=Proof.PORT,
    proof_note='Development candidate; hardware untested',
    doc='Scale-degree roots, generated chords and CHORD PLAY using native ARP KEY; optional MIDI Follow.',
    requires=('MIDI PART STATE',),
    linked=(Linked('chordpart', 'modules/midi-harmony/chord-part.s', dram=True),
            Linked('harmonyownership', 'modules/midi-harmony/ownership.s', dram=True),
            Linked('harmonysettings', 'modules/midi-harmony/settings.s', dram=True, include=follow_inc),
            Linked('midiharmony', 'modules/midi-harmony/harmony.s', dram=True, include=follow_inc),
            Linked('harmonyvoice', 'modules/midi-harmony/voicing.s', dram=True),
            Linked('harmonysize', 'modules/midi-harmony/size.s', dram=True),
            Linked('harmonypage', 'modules/midi-harmony/page.s', dram=True),
            Linked('harmonychords', 'modules/midi-harmony/chords.s', dram=True),
            Linked('chorddisplay', 'modules/midi-harmony/chord-display.s', dram=True, include=follow_inc),
            Linked('chordname', 'modules/midi-harmony/chord-name.s', dram=True),
            Linked('chordoperations', 'modules/midi-harmony/chord-operations.s', dram=True, include=follow_inc),
            Linked('chordfiles', 'modules/midi-harmony/chord-files.s', dram=True, include=follow_inc),
            Linked('chordrecord', 'modules/midi-harmony/chord-record.s', dram=True, include=follow_inc),
            Linked('chordsequence', 'modules/midi-harmony/chord-sequence.s', dram=True, include=follow_inc),
            Linked('chordui', 'modules/midi-harmony/chord-ui.s', dram=True, include=follow_inc),
            Linked('chordlocks', 'modules/midi-harmony/locks.s', dram=True, include=follow_inc),
            Linked('harmonyplay', 'modules/midi-harmony/play.s', dram=True, include=follow_inc),
            Linked('degreecodec', 'modules/midi-harmony/degrees/codec.s', dram=True),
            Linked('degreeroots', 'modules/midi-harmony/degrees/roots.s', dram=True),
            Linked('degreeaccess', 'modules/midi-harmony/degrees/part-access.s', dram=True,
                   include=lambda modules: '.set HD_FOLLOW,' + str(int('MIDI FOLLOW' in modules)) +
                   '\n.set HD_SCALES,' + str(int('MIDI SCALES' in modules)) +
                   '\n.set HD_SCENES,' + str(int('MIDI SCENES' in modules)) + '\n'),
            Linked('degreescenes', 'modules/midi-harmony/degrees/scenes.s', dram=True),
            Linked('degreesceneaccess', 'modules/midi-harmony/degrees/scene-access.s', dram=True,
                   include=lambda modules: '.set HD_SCENES,' + str(int('MIDI SCENES' in modules)) + '\n'),
            Linked('degreecore', 'modules/midi-harmony/degrees/core.s', dram=True),
            Linked('degreepacked', 'modules/midi-harmony/degrees/packed.s', dram=True),
            Linked('degreestorage', 'modules/midi-harmony/degrees/storage.s', dram=True),
            Linked('degreeevents', 'modules/midi-harmony/degrees/events.s', dram=True),
            Linked('degreerecording', 'modules/midi-harmony/degrees/recording.s', dram=True),
            Linked('degreeui', 'modules/midi-harmony/degrees/ui.s', dram=True),
            Linked('degreepanel', 'modules/midi-harmony/degrees/panel.s', dram=True),
            Linked('degreeoperations', 'modules/midi-harmony/degrees/operations.s', dram=True),
            Linked('degreeedit', 'modules/midi-harmony/degrees/edit-hooks.s', dram=True),
            Linked('degreepool', 'modules/midi-harmony/degrees/pool.s', dram=True),
            Linked('degreehooks', 'modules/midi-harmony/degrees/hooks.s', dram=True)),
    symbol_refs=(
        *(SymbolRef(addr, 0x400a74c0, 'harmonyplay', 'ch_play_modes', 'MIDI trig modes include CHORD PLAY') for addr in (0x40035a24,0x40051efc,0x40051f6c)),
        *(SymbolRef(addr, 0x400beb72, 'harmonyplay', 'ch_mode_names', 'mode names with CHORD PLAY') for addr in (0x400359fc,0x40036048)),
        *(SymbolRef(addr, 0x400beb8a, 'harmonyplay', 'ch_mode_icons', 'mode glyph table bound') for addr in (0x40035856,0x40035a46)),
        SymbolRef(0x400d3f34, 0, 'midiharmony', 'mh_type_format', 'NOTE SETUP F TYPE formatter'),
        SymbolRef(0x400bc5d8, 0x4004ae08, 'harmonypage', 'mh_page_open', 'NOTE SETUP F press opens Harmony'),
        SymbolRef(0x400bc5dc, 0x4004ae08, 'harmonypage', 'mh_page_noop', 'NOTE SETUP F release has no native commit')),
    pokes=(
        Poke(0x400d43a6, bytes.fromhex('00000080'), bytes.fromhex('00000020'), 'Part CHRD and SIZE packed range in disabled CTRL1 SETUP A'),
        Poke(0x4005872e, bytes.fromhex("7003"), bytes.fromhex("7004"), "four MIDI trig modes"),
        Poke(0x400d3e96, b'----\0\0', b'HARM\0\0', 'NOTE SETUP F label'),
        Poke(0x400d3f04, bytes.fromhex('00000080'), bytes.fromhex('00000003'), 'OFF NOTE CHORD values'),
        Poke(0x400d3f64, bytes(4), bytes.fromhex('400467a4'), 'TYPE text widget'),
        Poke(0x400d3fca, b'\x01', b'\x11', 'enable NOTE SETUP F only'),
        Poke(0x400d4092, bytes.fromhex('00000001'), bytes.fromhex('00000080'), 'packed Harmony Part settings range'),
        Poke(0x400d4359, b'\x00', b'\x23', 'Native Part DEG default 1:3'),
        Poke(0x400d43aa, bytes.fromhex('00000080'), bytes.fromhex('00000054'), 'Native Part DEG range 0..83')),
    claims=Claims(sram=((0x100fd560, 10400, 'Packed CHRD, DEG and NOTE snapshot current-bank mirror'),),
                  part_window=tuple((0x4e2+36*t+f, 1, 'Harmony Part setting') for t in range(8) for f in (5,16,18,19))),
    detours=(
        *(Detour(addr, bytes.fromhex('41f946c78d70'), 'harmonyownership', symbol,
                 'track-owned generated keyboard release slot') for addr,symbol in (
                     (0x4009eab4,'mh_key_slot_on'), (0x4009eaea,'mh_key_slot_arp'),
                     (0x4009eb02,'mh_key_slot_off'), (0x4009eb6e,'mh_key_slot_clear'))),
        Detour(0x40056c7c, bytes.fromhex("2040588f7110"), "chorddisplay", "ch_display_tick", "UI task refresh of changed sounding chords after queue receive"),
        Detour(0x4004878a, bytes.fromhex("41f94007e998"), "harmonyplay", "ch_grid_toggle", "release CHORD PLAY notes before entering grid"),
        Detour(0x40062aac, bytes.fromhex('4eb940041784'), 'chordrecord', 'ch_record_off', 'record release on captured physical track', kind='jsr'),
        Detour(0x40062a82, bytes.fromhex('4eb94004ef54'), 'chordrecord', 'ch_record_grid_off', 'grid release on captured physical track', kind='jsr'),
        Detour(0x4005040c, bytes.fromhex('4fefffb448d77cfc'), 'chordui', 'ch_step_push', 'toggle only the dedicated held-step CHRD lock', pad_to=8),
        Detour(0x40033aac, bytes.fromhex('4cd77cfc4fef002c'), 'chordoperations', 'ch_bitmap_all', 'include CHRD in current-pattern lock indicators', pad_to=8),
        Detour(0x40033bba, bytes.fromhex('4cd7001c4fef000c'), 'chordoperations', 'ch_bitmap_step', 'include CHRD in step lock indicator', pad_to=8),
        Detour(0x40043728, bytes.fromhex("4feffff048d70c0c"), "harmonyplay", "ch_release_track", "release CHORD PLAY ownership on native mode/grid/project cleanup", pad_to=8),
        Detour(0x400267e8, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40026884, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40026ece, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40026f5e, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40027764, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40027834, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x4002924c, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40029280, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40029316, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40029352, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40029980, bytes.fromhex('4eb940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='jsr'),
        Detour(0x40029652, bytes.fromhex('49f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002978e, bytes.fromhex('49f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002b370, bytes.fromhex('45f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002b42e, bytes.fromhex('45f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002b4b2, bytes.fromhex('49f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002b692, bytes.fromhex('49f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4002b9da, bytes.fromhex('45f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4003de14, bytes.fromhex('47f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4003e036, bytes.fromhex('47f940020898'), 'chordoperations', 'ch_memcpy', 'CHRD pattern and MIDI track copies', kind='lea'),
        Detour(0x4005fd8a, bytes.fromhex('e98e260dd686'), 'chordoperations', 'ch_place', 'CHRD MIDI edit lifecycle', pad_to=6),
        Detour(0x40040d44, bytes.fromhex('4fefffd448d77cfc'), 'chordoperations', 'ch_clear_locks', 'CHRD MIDI edit lifecycle', pad_to=8),
        Detour(0x40039b00, bytes.fromhex('4fefffc848d77cfc'), 'chordoperations', 'ch_clear_track', 'CHRD MIDI edit lifecycle', pad_to=8),
        Detour(0x4002bd2c, bytes.fromhex('4fefffc848d77cfc'), 'chordoperations', 'ch_step_copy', 'CHRD MIDI edit lifecycle', pad_to=8),
        Detour(0x4002c736, bytes.fromhex('d3fc1001614e'), 'chordoperations', 'ch_step_paste', 'CHRD MIDI edit lifecycle', pad_to=6),
        Detour(0x400918aa, bytes.fromhex('45f9400e21e0'), 'chordfiles', 'ch_saveb', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x4008ee42, bytes.fromhex('4eb940016388'), 'chordfiles', 'ch_fcopy', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4008f14e, bytes.fromhex('4eb940016388'), 'chordfiles', 'ch_fcopy', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4008ef9a, bytes.fromhex('2a3c40016388'), 'chordfiles', 'ch_d5_ef9a', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x4008f02e, bytes.fromhex('2a3c40016388'), 'chordfiles', 'ch_d5_f02e', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x4008f2a6, bytes.fromhex('2a3c40016388'), 'chordfiles', 'ch_d5_f2a6', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x4008f33a, bytes.fromhex('2a3c40016388'), 'chordfiles', 'ch_d5_f33a', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x400852ce, bytes.fromhex('4fef00104a80'), 'chordfiles', 'ch_loaded_all', 'CHRD after native full bank load'),
        Detour(0x40084d66, bytes.fromhex('4fef00104a80'), 'chordfiles', 'ch_loaded_resume', 'CHRD after native resume bank load'),
        Detour(0x400853de, bytes.fromhex('4fef001c4a80'), 'chordfiles', 'ch_loaded_project', 'CHRD after native project bank load'),
        Detour(0x40085458, bytes.fromhex('4fef00144a80'), 'chordfiles', 'ch_loaded_bank', 'CHRD after native bank reload'),
        Detour(0x40085170, bytes.fromhex('4eb9400909d8'), 'chordfiles', 'ch_newproj', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4008534c, bytes.fromhex('4eb9400909d8'), 'chordfiles', 'ch_newproj', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4008548e, bytes.fromhex('4eb9400909d8'), 'chordfiles', 'ch_newproj', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x400854c2, bytes.fromhex('4eb9400909d8'), 'chordfiles', 'ch_newproj', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4009159a, bytes.fromhex('4ebaf43c2003'), 'chordfiles', 'ch_newproj2', 'CHRD companion lifecycle', kind='jmp', pad_to=6),
        Detour(0x4000faf0, bytes.fromhex('2f0a2f022f3c0008ed80'), 'chordfiles', 'ch_tocs1', 'CHRD companion lifecycle', kind='jmp', pad_to=10),
        Detour(0x40025808, bytes.fromhex('4eb94000fbb4'), 'chordfiles', 'ch_fromcs1', 'CHRD companion lifecycle', kind='jsr'),
        Detour(0x4009ec58, bytes.fromhex('4cd704fc4fef001c'), 'chordrecord', 'ch_record_post', 'snapshot recorded physical root quality', pad_to=8),
        Detour(0x40062ab6, bytes.fromhex('4eb940045614'), 'chordrecord', 'ch_record_free', 'release consumed key message', kind='jsr'),
        Detour(0x40062a4e, bytes.fromhex('4eb940041bc4'), 'chordrecord', 'ch_record_on', 'record captured CHRD alongside NOTE', kind='jsr'),
        Detour(0x40041f72, bytes.fromhex('41f9400e6ae0'), 'chordrecord', 'ch_record_commit', 'last physical chord change wins a recorded step'),
        Detour(0x4009d180, bytes.fromhex('2203eb8941f51800'), 'chordsequence', 'ch_stage_fill', 'schedule exact MIDI step CHRD', pad_to=8),
        Detour(0x4009b91c, bytes.fromhex('d1fc46c78960'), 'chordsequence', 'ch_stage_copy_a', 'MIDI staged CHRD to pending'),
        Detour(0x4009c108, bytes.fromhex('d1fc46c78960'), 'chordsequence', 'ch_stage_copy_b', 'MIDI staged CHRD to pending on start'),
        Detour(0x400a19ce, bytes.fromhex('2c2f00882f460030'), 'chordsequence', 'ch_pending_entry', 'publish fired MIDI chord identity before native/scene pending copy', pad_to=8),
        Detour(0x4004e1f6, bytes.fromhex('2d40ffb02040'), 'chordui', 'ch_descriptor', 'CHRD descriptor for CHORD tracks'),
        Detour(0x4004e382, bytes.fromhex('226effcc20690030'), 'chordui', 'ch_draw_value', 'CHRD held-step or live value', pad_to=8),
        Detour(0x40055008, bytes.fromhex('4fefffd048d77cfc'), 'chordui', 'ch_encoder', 'live CHRD selection without native writes', pad_to=8),
        Detour(0x400508e4, bytes.fromhex('4fefffb048d77cfc'), 'chordui', 'ch_step_encoder', 'dedicated CHRD held-step editor', pad_to=8),
        Detour(0x40043fdc, bytes.fromhex('4fefffbc48d73c7c'), 'harmonyplay', 'ch_play_leds', 'root and variation LED groups outside grid recording', pad_to=8),
        Detour(0x40044920, bytes.fromhex('4fefffd448d77cfc'), 'harmonyplay', 'ch_play_guide', 'CHORD PLAY key layout guide', pad_to=8),
        Detour(0x400501d8, bytes.fromhex('2f02206f0008'), 'harmonyplay', 'ch_play_key', 'CHORD PLAY trig dispatch'),
        *(Detour(addr, bytes.fromhex('b0b9460d16f0'), 'harmonyplay', 'ch_octave_compare', 'CHORD PLAY uses native FUNC LEFT/RIGHT octave controls', kind='jsr') for addr in (0x400458b2,0x400458e6)),
        Detour(0x4009fb3a, bytes.fromhex("102d022c2241"), "midiharmony", "mh_transpose", "sequenced pools bypass duplicate TRAN; live arp uses stock"),
        Detour(0x4009fb86, bytes.fromhex("77012006d083"), "midiharmony", "mh_output", "final scale correction before note ownership"),
        Detour(0x40036682, bytes.fromhex('2001e9882040'), 'midiharmony', 'mh_draw_type', 'NOTE SETUP F module value'),
        Detour(0x4003a8e8, bytes.fromhex('4feffff048d70c0c'), 'midiharmony', 'mh_note_encoder', 'NOTE SETUP F TYPE encoder', pad_to=8),
        Detour(0x4007a1b0, bytes.fromhex('181020037403'), 'midiharmony', 'mh_draw_key', 'show source KEY when following'),
        Detour(0x4009fad2, bytes.fromhex("102800316606"), "midiharmony", "mh_scale", "avoid second stock scale correction"),
        Detour(0x4009fa2a, bytes.fromhex('240e59822f02'), 'midiharmony', 'mh_sequence', 'generate working chord before stock arp'),
        Detour(0x4009e9a8, bytes.fromhex('4fefffe448d704fc'), 'midiharmony', 'mh_keyboard', 'live MIDI notes with release ownership', pad_to=8),
        Detour(0x4007a2ec, bytes.fromhex('4fefffdc48d71cfc'), 'midiharmony', 'mh_arp_encoder', 'inherited native KEY is read-only', pad_to=8),
        Detour(0x40025ac8, bytes.fromhex('42b9100b14d8'), 'midiharmony', 'mh_defaults', 'new project settings defaults'),
        Detour(0x40010224, bytes.fromhex('7139100b14ae'), 'midiharmony', 'mh_boot', 'validate battery-backed settings'),
    Detour(0x400a44ee, bytes.fromhex('23c080006628'), 'degreesceneaccess', 'hd_scene_commit_stack',
                    'Reserve the pinned MIDISC2.1 pattern-commit stack window'),
             Detour(0x4002c76c, bytes.fromhex('103c0001e7a8'), 'degreeedit', 'hd_step_apply',
                    'Degree identity after native step paste'),
             Detour(0x4009f9c6, bytes.fromhex('206effdc7110'), 'degreepool', 'hd_tick',
                    'Rebuild a sequence arp pool after a mode boundary'),
             Detour(0x400534c2, bytes.fromhex('4eb94006dbcc'), 'degreesceneaccess', 'hd_scene_hold_a',
                    'Degree scene A seed/range before unchanged MIDISC hold', kind='jsr'),
             Detour(0x40052ec2, bytes.fromhex('4eb94006dbcc'), 'degreesceneaccess', 'hd_scene_hold_b',
                    'Degree scene B seed/range before unchanged MIDISC hold', kind='jsr')),
    gates=(Gate('tools/verify/verify_midi_harmony_stress.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_size.py', stage='image', venv=True),
           Gate('tools/verify/verify_midi_part.py', stage='image', venv=True),
           Gate('tools/verify/verify_chord_part.py', stage='image', venv=True),
           Gate('tools/verify/verify_midi_harmony.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_playability.py', stage='image', venv=True),
           Gate('tools/verify/verify_chord_play.py', stage='image', venv=True),
           Gate('tools/verify/verify_chord_display.py', stage='image', venv=True),
           Gate('tools/verify/verify_chord_storage.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_scenes.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_codec.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_roots.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_packed.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_core.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_integration.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_part_state.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_publication.py', stage='image', venv=True),
           Gate('tools/verify/verify_harmony_degree_files.py', stage='image', venv=True)),
)
