| Generated by generate.py; edit size.c / size.h.
#NO_APP
	.file	"size.c"
	.text
	.align	2
	.type	sort, @function
sort:
	lea (-20,%sp),%sp
	moveq #1,%d1
	move.l 28(%sp),%d0
	movem.l #7180,(%sp)
	move.l 24(%sp),%a4
	cmp.l %d0,%d1
	jcc .L1
	lea (%a4,%d0.l*4),%a3
	lea (4,%a4),%a2
	moveq #1,%d3
.L6:
	move.l (%a2),%d2
	move.l %a2,%a0
	move.l %d3,%d0
	addq.l #4,%a2
.L3:
	move.l -4(%a0),%d1
	move.l %a0,%a1
	subq.l #1,%d0
	cmp.l %d1,%d2
	jge .L4
	move.l %d1,(%a0)
	lea (-4,%a1),%a0
	tst.l %d0
	jne .L3
	move.l %a4,%a1
.L4:
	move.l %d2,(%a1)
	addq.l #1,%d3
	cmp.l %a2,%a3
	jne .L6
.L1:
	movem.l (%sp),#7180
	lea (20,%sp),%sp
	rts
	.size	sort, .-sort
	.align	2
	.type	clarify, @function
clarify:
	lea (-32,%sp),%sp
	moveq #1,%d0
	movem.l #7292,(%sp)
	move.l 40(%sp),%d2
	move.l 36(%sp),%a3
	move.l 44(%sp),%d3
	cmp.l %d2,%d0
	jeq .L28
	moveq #-1,%d4
	cmp.l 48(%sp),%d4
	jeq .L12
	move.l (%a3),%d1
	moveq #12,%d4
	rems.l %d4,%d0:%d1
	cmp.l 48(%sp),%d0
	jeq .L20
.L12:
	moveq #1,%d4
	cmp.l %d2,%d4
	jeq .L28
	moveq #12,%d6
	lea sort,%a2
.L24:
	move.l (%a3),%d1
	moveq #47,%d0
	move.w #1,%a0
	lea (4,%a3),%a1
	cmp.l %d1,%d0
	jlt .L18
	moveq #7,%d0
.L26:
	move.l %d1,%d4
	addq.l #4,%a1
	move.l -4(%a1),%d1
	move.l %d1,%d5
	sub.l %d4,%d5
	cmp.l %d5,%d0
	jgt .L15
.L39:
	addq.l #1,%a0
	moveq #5,%d0
	cmp.l %d2,%a0
	jeq .L28
	moveq #47,%d4
	cmp.l %d1,%d4
	jge .L26
.L18:
	moveq #3,%d0
	moveq #59,%d4
	cmp.l %d1,%d4
	jge .L26
	move.l %d1,%d4
	moveq #1,%d0
	move.l (%a1),%d1
	addq.l #4,%a1
	move.l %d1,%d5
	sub.l %d4,%d5
	cmp.l %d5,%d0
	jle .L39
.L15:
	cmp.l %a0,%d2
	jeq .L28
	lea (%a3,%a0.l*4),%a4
	move.l (%a4),%a1
	cmp.l %a1,%d3
	jeq .L20
.L22:
	lea (12,%a1),%a1
	clr.l %d1
	move.l %a3,%a0
.L23:
	addq.l #1,%d1
	cmp.l (%a0)+,%a1
	jeq .L22
	cmp.l %d2,%d1
	jne .L23
	moveq #127,%d0
	cmp.l %a1,%d0
	jlt .L20
	move.l %a1,(%a4)
	move.l %d2,-(%sp)
	move.l %a3,-(%sp)
	jsr (%a2)
	subq.l #1,%d6
	addq.l #8,%sp
	tst.l %d6
	jne .L24
	move.l %d6,%d0
	movem.l (%sp),#7292
	lea (32,%sp),%sp
	rts
.L28:
	moveq #1,%d6
	move.l %d6,%d0
	movem.l (%sp),#7292
	lea (32,%sp),%sp
	rts
.L20:
	clr.l %d6
	move.l %d6,%d0
	movem.l (%sp),#7292
	lea (32,%sp),%sp
	rts
	.size	clarify, .-clarify
	.align	2
	.type	candidate.part.0, @function
candidate.part.0:
	lea (-60,%sp),%sp
	movem.l #31996,(%sp)
	move.l 68(%sp),%d5
	move.l 76(%sp),%d3
	move.l 64(%sp),%a0
	move.l 72(%sp),%d4
	move.l 88(%sp),%a4
	move.l 96(%sp),%a6
	cmp.l %d5,%d3
	jcs .L41
	move.l %d5,%d3
	subq.l #1,%d3
.L41:
	move.l (%a0,%d3.l*4),%d7
	move.l 80(%sp),%a1
	add.l %d7,%a1
	move.l %a1,%d0
	move.l %a6,%a2
	move.l %a6,%a3
	clr.l %d2
	add.l #11,%d0
.L47:
	move.l (%a0),%d6
	move.l 80(%sp),%d1
	add.l %d6,%d1
	tst.l %d3
	jne .L124
.L42:
	moveq #127,%d6
	cmp.l %d1,%d6
	jcs .L74
	addq.l #4,%a0
	move.l %d1,(%a3)+
	addq.l #1,%d2
	cmp.l %d5,%d2
	jne .L47
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	lea sort,%a3
	jsr (%a3)
	addq.l #8,%sp
	moveq #1,%d0
	cmp.l %a4,%d0
	jcc .L48
	lea (%a6,%d2.l*4),%a1
	move.l %a6,%a0
	clr.l %d2
.L50:
	move.l (%a0)+,%d1
	move.l %d1,%d0
	sub.l 92(%sp),%d0
	moveq #12,%d5
	rems.l %d5,%d3:%d0
	tst.l %d3
	jeq .L49
	move.l %d1,(%a6,%d2.l*4)
	addq.l #1,%d2
.L49:
	cmp.l %a0,%a1
	jne .L50
	move.l %a4,%d0
	subq.l #1,%d0
	mulu.w #12,%d0
	move.l 92(%sp),%d1
	sub.l %d0,%d1
	jmi .L51
	move.l %d1,(%a6,%d2.l*4)
	addq.l #1,%d2
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	addq.l #8,%sp
.L48:
	cmp.l %d2,%d4
	jls .L112
	tst.l %d2
	jeq .L54
	lea (%a6,%d2.l*4),%a0
	move.l %a0,%d3
	move.l %a0,%a1
.L60:
	move.l %a6,%a4
	move.l #128,%d1
.L59:
	move.l (%a4)+,%d0
	move.l %a6,%a0
	add.l #12,%d0
.L57:
	cmp.l (%a0)+,%d0
	jeq .L56
	cmp.l %a1,%a0
	jne .L57
	cmp.l %d1,%d0
	jge .L58
	move.l %d0,%d1
.L58:
	cmp.l %a4,%d3
	jne .L59
	moveq #127,%d0
	cmp.l %d1,%d0
	jlt .L54
	addq.l #1,%d2
	move.l %d1,(%a1)+
	cmp.l %d2,%d4
	jne .L60
.L112:
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	addq.l #8,%sp
	move.l %a6,%a4
	move.l %d2,%d0
	lsl.l #2,%d0
	lea (44,%sp),%a0
	move.l %a0,%d1
	lea (%a6,%d0.l),%a1
.L64:
	move.l %d1,%a5
	move.l (%a4)+,(%a5)+
	move.l %a5,%d1
	cmp.l %a1,%a4
	jne .L64
	moveq #1,%d1
	cmp.l 84(%sp),%d1
	jeq .L125
	moveq #2,%d1
	cmp.l 84(%sp),%d1
	jeq .L114
.L119:
	add.l %a0,%d0
.L66:
	move.l %a0,%a4
	moveq #1,%d3
.L71:
	moveq #127,%d5
	cmp.l (%a4)+,%d5
	sge %d1
	mvs.b %d1,%d1
	neg.l %d1
	and.l %d1,%d3
	cmp.l %a4,%d0
	jne .L71
	tst.l %d3
	jeq .L63
.L73:
	move.l (%a0)+,(%a2)+
	cmp.l %a1,%a2
	jne .L73
.L63:
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	addq.l #8,%sp
	move.l %d2,%d0
	movem.l (%sp),#31996
	lea (60,%sp),%sp
	rts
.L124:
	cmp.l %d7,%d6
	jge .L117
.L44:
	add.l #12,%d1
	cmp.l %a1,%d1
	jlt .L44
.L117:
	cmp.l %d1,%d0
	jge .L42
	add.l #-12,%d1
	jra .L117
.L56:
	add.l #12,%d0
	move.l %a6,%a0
	jra .L57
.L74:
	clr.l %d2
	move.l %d2,%d0
	movem.l (%sp),#31996
	lea (60,%sp),%sp
	rts
.L54:
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	addq.l #8,%sp
	tst.l %d2
	jeq .L63
	move.l %d2,%d0
	move.l %a6,%a4
	lsl.l #2,%d0
	lea (44,%sp),%a0
	move.l %a0,%d1
	lea (%a6,%d0.l),%a1
	jra .L64
.L114:
	moveq #1,%d4
	cmp.l %d2,%d4
	jeq .L119
	lea (4,%a0),%a4
	add.l %a0,%d0
.L70:
	move.l (%a4),%d1
	add.l #12,%d1
	move.l %d1,(%a4)+
	cmp.l %d0,%a4
	jeq .L66
	move.l (%a4),%d1
	add.l #12,%d1
	move.l %d1,(%a4)+
	cmp.l %d0,%a4
	jne .L70
	jra .L66
.L125:
	cmp.l %d2,%d1
	jeq .L119
	move.l 48(%sp),%d3
	add.l #12,%d3
	move.l %d3,48(%sp)
	move.l %a0,%a4
	clr.l %d5
	clr.l %d4
.L68:
	moveq #1,%d6
	cmp.l %d4,%d6
	jeq .L67
	cmp.l (%a4),%d3
	seq %d1
	mvs.b %d1,%d1
	neg.l %d1
	or.l %d1,%d5
.L67:
	addq.l #1,%d4
	addq.l #4,%a4
	cmp.l %d2,%d4
	jne .L68
	add.l #12,%d3
	tst.l %d5
	jeq .L119
	move.l %d3,48(%sp)
	move.l %a0,%a4
	clr.l %d5
	clr.l %d4
	jra .L68
.L51:
	move.l %d2,-(%sp)
	move.l %a6,-(%sp)
	jsr (%a3)
	subq.l #1,%d4
	addq.l #8,%sp
	jra .L48
	.size	candidate.part.0, .-candidate.part.0
	.align	2
	.globl	mh_size_voice_c
	.type	mh_size_voice_c, @function
mh_size_voice_c:
	lea (-160,%sp),%sp
	moveq #3,%d1
	move.l 172(%sp),%d0
	lsr.l #7,%d0
	movem.l #19708,(%sp)
	move.l 164(%sp),%a2
	moveq #2,%d3
	move.l 168(%sp),%a3
	and.l %d1,%d0
	move.l %d0,%a0
	subq.l #1,%a0
	cmp.l %a0,%d3
	jcc .L239
	movem.l (%sp),#19708
	lea (160,%sp),%sp
	rts
.L239:
	move.l 180(%sp),%d5
	moveq #7,%d3
	and.l 172(%sp),%d3
	moveq #9,%d1
	lsl.l %d1,%d5
	move.l %d0,%d4
	addq.l #1,%d4
	move.b 5(%a3),%d1
	move.b (%a2),71(%sp)
	move.l 172(%sp),%d2
	lsr.l #5,%d2
	move.l 176(%sp),%a0
	subq.l #1,%a0
	move.l %d3,62(%sp)
	move.b 6(%a3),%d3
	move.l %d5,%d0
	and.l #4193792,%d0
	move.b %d1,54(%sp)
	moveq #3,%d1
	and.l %d1,%d2
	mvz.b 71(%sp),%d5
	move.b %d3,58(%sp)
	move.b 7(%a3),%d3
	or.l 172(%sp),%d0
	move.b %d3,66(%sp)
	bset #23,%d0
	move.b 2(%a2),%d3
	move.l %d0,72(%sp)
	moveq #1,%d0
	mvz.b %d3,%d3
	cmp.l %a0,%d0
	jcc .L128
	moveq #7,%d1
	cmp.l 176(%sp),%d1
	jeq .L128
	cmp.l %d5,%d3
	jls .L180
	sub.l %d5,%d3
	moveq #12,%d1
	rems.l %d1,%d0:%d3
	subq.l #7,%d0
	tst.l %d0
	jeq .L180
	move.l 176(%sp),%d0
	moveq #1,%d1
	subq.l #3,%d0
	cmp.l %d0,%d1
	jcc .L240
	move.w #2,%a0
	moveq #2,%d0
	moveq #2,%d1
	move.l %sp,%d6
	add.l #140,%d6
	move.l %d0,148(%sp)
	moveq #1,%d0
	move.l %a0,144(%sp)
	move.l %sp,%d7
	sub.l %a6,%a6
	clr.l 140(%sp)
	move.l %d0,152(%sp)
	move.l %d1,156(%sp)
	move.l %d6,%a0
	add.l #160,%d7
	clr.l %d3
	move.l %d2,%a1
.L137:
	moveq #1,%d1
	move.l (%a0)+,%d0
	cmp.l %a1,%d1
	jeq .L133
.L130:
	btst %d0,%d3
	jne .L134
	moveq #1,%d1
	lsl.l %d0,%d1
	move.b (%a2,%d0.l),%d2
	or.l %d1,%d3
	tst.b %d2
	jlt .L134
	tst.l %d0
	jeq .L136
	mvz.b %d2,%d0
	cmp.l %d5,%d0
	jls .L134
.L136:
	mvz.w %a6,%d0
	mvs.b %d2,%d2
	addq.l #1,%a6
	move.l %d2,108(%sp,%d0.l*4)
.L134:
	cmp.l %d7,%a0
	jeq .L227
	cmp.l %d4,%a6
	jcs .L137
.L226:
	move.l %a6,-(%sp)
	moveq #64,%d3
	move.l %sp,%d7
	add.l #112,%d7
	move.l %d7,-(%sp)
	move.l %a1,%d2
	jsr sort
	and.l 180(%sp),%d3
	addq.l #8,%sp
.L138:
	mvz.b 54(%sp),%d0
	mvz.b 58(%sp),%d1
	lea (124,%sp),%a1
	move.l %a1,42(%sp)
	swap %d0
	clr.w %d0
	move.l %d1,%a0
	move.l 172(%sp),%d1
	lsr.l #3,%d1
	move.l %d0,50(%sp)
	move.l %a0,%d0
	lsl.l #8,%d0
	move.l %d0,%a0
	moveq #3,%d0
	and.l %d1,%d0
	move.l %d0,46(%sp)
	move.l %a1,-(%sp)
	mvz.b 70(%sp),%d1
	move.l %a0,%d0
	move.l %d1,58(%sp)
	move.l %d5,-(%sp)
	move.l %d2,-(%sp)
	or.l 62(%sp),%d0
	move.l 74(%sp),%a1
	move.l 58(%sp),-(%sp)
	clr.l -(%sp)
	or.l %d1,%d0
	move.l %d0,78(%sp)
	tst.l 82(%sp)
	jne .L140
	move.w #1,%a1
.L140:
	pea -1(%a1)
	move.l %d4,-(%sp)
	move.l %a6,-(%sp)
	move.l %d7,-(%sp)
	jsr (candidate.part.0)
	move.l %d0,90(%sp)
	lea (36,%sp),%sp
	tst.l %d0
	jeq .L141
	tst.l %d3
	jne .L142
	moveq #2,%d3
	cmp.l 176(%sp),%d3
	jeq .L189
	moveq #1,%d0
	cmp.l 62(%sp),%d0
	jeq .L186
.L231:
	move.l 54(%sp),%a6
.L139:
	move.l 42(%sp),%a0
	clr.l %d0
.L173:
	cmp.l %a6,%d0
	jcc .L197
	move.b 3(%a0),%d1
.L172:
	move.b %d1,(%a2,%d0.l)
	addq.l #4,%a0
	addq.l #1,%d0
	moveq #4,%d1
	cmp.l %d0,%d1
	jne .L173
	clr.l %d0
.L174:
	lea (%a2,%d0.l),%a0
	moveq #4,%d1
	move.b (%a0),(%a3,%d0.l)
	addq.l #1,%d0
	cmp.l %d0,%d1
	jne .L174
	cmp.l %a6,%d4
	jeq .L241
.L175:
	clr.b %d2
	clr.b %d0
	clr.b %d1
	move.b 71(%sp),4(%a3)
	move.b %d2,7(%a3)
	move.b %d0,6(%a3)
	move.b %d1,5(%a3)
.L242:
	movem.l (%sp),#19708
	lea (160,%sp),%sp
	rts
.L128:
	cmp.l %d5,%d3
	jls .L183
	sub.l %d5,%d3
	moveq #12,%d1
	rems.l %d1,%d0:%d3
	move.w #3,%a0
	moveq #7,%d3
	cmp.l %d0,%d3
	jeq .L229
	moveq #2,%d0
	moveq #2,%d1
	move.l %sp,%d6
	add.l #140,%d6
	move.l %a0,144(%sp)
	move.l %d0,148(%sp)
	moveq #1,%d0
	move.l %sp,%d7
	sub.l %a6,%a6
	clr.l 140(%sp)
	move.l %d0,152(%sp)
	move.l %d1,156(%sp)
	move.l %d6,%a0
	add.l #160,%d7
	clr.l %d3
	move.l %d2,%a1
	jra .L137
.L183:
	move.w #3,%a0
	moveq #1,%d0
	moveq #2,%d1
	move.l %sp,%d6
	add.l #140,%d6
	move.l %d0,148(%sp)
	moveq #1,%d0
	move.l %a0,144(%sp)
	move.l %sp,%d7
	sub.l %a6,%a6
	clr.l 140(%sp)
	move.l %d0,152(%sp)
	move.l %d1,156(%sp)
	move.l %d6,%a0
	add.l #160,%d7
	clr.l %d3
	move.l %d2,%a1
	jra .L137
.L133:
	tst.l %d0
	jne .L130
	cmp.l %d7,%a0
	jeq .L227
	cmp.l %d4,%a6
	jcc .L226
	move.l (%a0)+,%d0
	jra .L133
.L241:
	moveq #1,%d3
	cmp.l 62(%sp),%d3
	jne .L175
	move.l 72(%sp),%d1
	move.b 75(%sp),%d2
	move.l 72(%sp),%d0
	lsr.l #8,%d0
	clr.w %d1
	swap %d1
	move.b 71(%sp),4(%a3)
	move.b %d0,6(%a3)
	move.b %d2,7(%a3)
	move.b %d1,5(%a3)
	jra .L242
.L197:
	st %d1
	jra .L172
.L227:
	move.l %a6,-(%sp)
	moveq #64,%d3
	move.l %sp,%d7
	add.l #112,%d7
	move.l %d7,-(%sp)
	move.l %a1,%d2
	jsr sort
	and.l 180(%sp),%d3
	addq.l #8,%sp
	tst.l %a6
	jne .L138
	lea (124,%sp),%a0
	clr.l %d0
	move.l %a0,42(%sp)
	move.l 42(%sp),%a0
	jra .L173
.L141:
	move.l 42(%sp),-(%sp)
	move.l %d5,-(%sp)
	move.l %d2,-(%sp)
	move.l 58(%sp),-(%sp)
	clr.l -(%sp)
	clr.l -(%sp)
	move.l %d4,-(%sp)
	move.l %a6,-(%sp)
	move.l %d7,-(%sp)
	jsr (candidate.part.0)
	move.l %d0,90(%sp)
	lea (36,%sp),%sp
	tst.l %d3
	jeq .L243
	move.l %d2,%d0
	subq.l #1,%d0
	mulu.w #12,%d0
	move.l %d5,%a0
	sub.l %d0,%a0
	moveq #2,%d0
	cmp.l 176(%sp),%d0
	jeq .L143
	moveq #1,%d1
	cmp.l 62(%sp),%d1
	jne .L231
	tst.l 54(%sp)
	jne .L147
.L150:
	move.l 58(%sp),%d1
	cmp.l 72(%sp),%d1
	jne .L231
.L198:
	moveq #-1,%d3
	move.l %d3,76(%sp)
.L151:
	mvz.b 4(%a3),%d0
	move.l %d5,%d1
	moveq #12,%d3
	sub.l %d0,%d1
	move.l %d1,50(%sp)
	move.l %d1,%d0
	rems.l %d3,%d1:%d0
	moveq #1,%d3
	cmp.l %d2,%d3
	sne %d0
	move.l %d1,%a1
	move.l 50(%sp),%d1
	sub.l %a1,%d1
	move.l %d1,80(%sp)
	neg.l %d0
	tst.b %d0
	jeq .L157
	move.l #2147483647,%d1
	move.l %a2,104(%sp)
	move.l %d7,58(%sp)
	move.l %a0,84(%sp)
	move.l %d1,96(%sp)
	move.l %d2,50(%sp)
	move.l %a0,%a2
	clr.l %d7
	move.l %a3,92(%sp)
	move.l %d5,66(%sp)
.L159:
	clr.l %d5
	clr.l %d0
.L171:
	move.l %d6,-(%sp)
	move.l 70(%sp),-(%sp)
	move.l 58(%sp),-(%sp)
	move.l 58(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l %d7,-(%sp)
	move.l %d4,-(%sp)
	move.l %a6,-(%sp)
	move.l 90(%sp),-(%sp)
	jsr (candidate.part.0)
	lea (36,%sp),%sp
	move.l %d0,%d2
	cmp.l %d4,%d0
	jeq .L179
	addq.l #1,%d5
.L170:
	moveq #-12,%d0
	moveq #1,%d3
	cmp.l %d5,%d3
	jeq .L171
	move.l %d6,-(%sp)
	move.l 70(%sp),-(%sp)
	move.l 58(%sp),-(%sp)
	move.l 58(%sp),-(%sp)
	pea 12.w
	move.l %d7,-(%sp)
	move.l %d4,-(%sp)
	move.l %a6,-(%sp)
	move.l 90(%sp),-(%sp)
	jsr (candidate.part.0)
	lea (36,%sp),%sp
	cmp.l %d0,%d4
	jne .L178
	move.l %d4,%d2
	moveq #2,%d5
.L179:
	move.l 76(%sp),-(%sp)
	move.l 88(%sp),-(%sp)
	move.l %d2,-(%sp)
	move.l %d6,-(%sp)
	jsr clarify
	lea (16,%sp),%sp
	tst.l %d0
	jeq .L163
	move.l 140(%sp),%d0
	sub.l %a2,%d0
	add.l #12,%d0
	moveq #24,%d1
	cmp.l %d0,%d1
	jcs .L163
	moveq #1,%d3
	cmp.l 50(%sp),%d3
	jeq .L165
	move.l %d6,%a0
	clr.l %d0
.L166:
	addq.l #4,%a0
	addq.l #1,%d0
	cmp.l -4(%a0),%a2
	jeq .L165
	cmp.l %d0,%d2
	jhi .L166
.L163:
	addq.l #1,%d5
	moveq #3,%d0
	cmp.l %d5,%d0
	jne .L170
.L178:
	addq.l #1,%d7
	cmp.l %d7,%a6
	jhi .L159
	move.l 104(%sp),%a2
	move.l 92(%sp),%a3
	move.l 54(%sp),%a6
	jra .L139
.L180:
	move.w #1,%a0
.L229:
	moveq #1,%d0
	moveq #2,%d1
	move.l %sp,%d6
	add.l #140,%d6
	move.l %a0,144(%sp)
	move.l %d0,148(%sp)
	moveq #1,%d0
	move.l %sp,%d7
	sub.l %a6,%a6
	clr.l 140(%sp)
	move.l %d0,152(%sp)
	move.l %d1,156(%sp)
	move.l %d6,%a0
	add.l #160,%d7
	clr.l %d3
	move.l %d2,%a1
	jra .L137
.L189:
	move.l %d5,%a0
.L143:
	move.b 3(%a2),%d1
	jmi .L244
	mvz.b %d1,%d1
	moveq #1,%d3
	cmp.l %d5,%d1
	jls .L245
	cmp.l 62(%sp),%d3
	jne .L231
	move.w %d1,%d0
	moveq #19,%d3
	mulu.w #43691,%d0
	lsr.l %d3,%d0
	muls.w #12,%d0
	sub.l %d0,%d1
	mvz.b %d1,%d1
	move.l %d1,76(%sp)
	tst.l 54(%sp)
	jeq .L234
.L144:
	moveq #1,%d0
	cmp.l %d2,%d0
	jeq .L194
	move.l %a0,%d0
	move.l 76(%sp),-(%sp)
	move.l %d0,-(%sp)
	move.l 62(%sp),-(%sp)
	move.l 54(%sp),-(%sp)
	move.l %a0,54(%sp)
	jsr clarify
	lea (16,%sp),%sp
	move.l 38(%sp),%a0
.L234:
	move.l 58(%sp),%d1
	cmp.l 72(%sp),%d1
	jeq .L151
	move.l 54(%sp),%a6
	jra .L139
.L243:
	moveq #2,%d0
	cmp.l 176(%sp),%d0
	jeq .L189
	moveq #1,%d1
	cmp.l 62(%sp),%d1
	jne .L231
	tst.l 54(%sp)
	jeq .L246
	move.l %d5,%a0
.L230:
	moveq #-1,%d3
	move.l %d3,76(%sp)
	jra .L144
.L142:
	move.l %d2,%d0
	subq.l #1,%d0
	mulu.w #12,%d0
	move.l %d5,%a0
	moveq #2,%d1
	sub.l %d0,%a0
	cmp.l 176(%sp),%d1
	jeq .L143
	moveq #1,%d3
	cmp.l 62(%sp),%d3
	jne .L231
.L147:
	pea -1.w
	move.l %a0,-(%sp)
	move.l 62(%sp),-(%sp)
	move.l 54(%sp),-(%sp)
	move.l %a0,54(%sp)
	jsr clarify
	lea (16,%sp),%sp
	move.l 58(%sp),%d3
	move.l 38(%sp),%a0
	cmp.l 72(%sp),%d3
	jeq .L198
	move.l 54(%sp),%a6
	jra .L139
.L244:
	moveq #1,%d0
	cmp.l 62(%sp),%d0
	jne .L231
	tst.l 54(%sp)
	jeq .L150
	moveq #-1,%d3
	move.l %d3,76(%sp)
	jra .L144
.L245:
	cmp.l 62(%sp),%d3
	jne .L231
	tst.l 54(%sp)
	jne .L230
	move.l 58(%sp),%d1
	cmp.l 72(%sp),%d1
	jne .L231
	moveq #-1,%d1
	move.l %d1,76(%sp)
	jra .L151
.L240:
	move.w #1,%a0
	moveq #2,%d0
	moveq #2,%d1
	move.l %sp,%d6
	add.l #140,%d6
	move.l %d0,148(%sp)
	moveq #1,%d0
	move.l %a0,144(%sp)
	move.l %sp,%d7
	sub.l %a6,%a6
	clr.l 140(%sp)
	move.l %d0,152(%sp)
	move.l %d1,156(%sp)
	move.l %d6,%a0
	add.l #160,%d7
	clr.l %d3
	move.l %d2,%a1
	jra .L137
.L186:
	moveq #-1,%d1
	move.l %d5,%a0
	move.l %d1,76(%sp)
	jra .L144
.L165:
	move.l %a2,88(%sp)
	move.l 92(%sp),%a2
	sub.l %a0,%a0
	move.l %d6,100(%sp)
	sub.l %a3,%a3
	move.l %d6,%a1
.L168:
	move.l (%a1)+,%d0
	mvz.b (%a2,%a0.l),%d1
	addq.l #1,%a0
	sub.l %d1,%d0
	move.l %d0,%d3
	sub.l 80(%sp),%d3
	sne %d1
	move.l %d3,%d0
	tst.l %d3
	jlt .L247
.L167:
	lsl.l #3,%d0
	mvs.b %d1,%d1
	sub.l %d1,%d0
	add.l %d0,%a3
	cmp.l %a0,%d2
	jhi .L168
	move.l 88(%sp),%a2
	cmp.l 96(%sp),%a3
	jge .L163
	move.l 42(%sp),%a0
	clr.l %d0
	move.l 100(%sp),%a1
.L169:
	move.l (%a1)+,(%a0)+
	addq.l #1,%d0
	cmp.l %d0,%d2
	jhi .L169
	move.l %a3,96(%sp)
	moveq #3,%d0
	move.l %d2,54(%sp)
	addq.l #1,%d5
	cmp.l %d5,%d0
	jne .L170
	jra .L178
.L247:
	neg.l %d0
	jra .L167
.L194:
	move.l 76(%sp),-(%sp)
	moveq #-1,%d0
	move.l %d0,-(%sp)
	move.l 62(%sp),-(%sp)
	move.l 54(%sp),-(%sp)
	move.l %a0,54(%sp)
	jsr clarify
	lea (16,%sp),%sp
	move.l 38(%sp),%a0
	jra .L234
.L157:
	moveq #-1,%d3
	move.l #2147483647,%d1
	move.l %a2,104(%sp)
	move.l %d7,58(%sp)
	move.l %d3,84(%sp)
	move.l %d1,96(%sp)
	move.l %d2,50(%sp)
	move.l %a0,%a2
	clr.l %d7
	move.l %a3,92(%sp)
	move.l %d5,66(%sp)
	jra .L159
.L246:
	move.l 58(%sp),%d3
	cmp.l 72(%sp),%d3
	jne .L231
	moveq #-1,%d1
	move.l %d5,%a0
	move.l %d1,76(%sp)
	jra .L151
	.size	mh_size_voice_c, .-mh_size_voice_c
